### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by alexjurkiewicz** [jeremygurr/dcssca#1]
When building on Linux, I eventually receive this error:

```
No Git, and util/release_ver doesn't exist.
make: *** [build.h] Error 2
```

I can work around this locally with `echo 1.0 > util/release_ver`, but it would be nice if you could fix permanently.

I believe you can fix this by adding a tag to the repository against a commit in the master branch with a name in the form of '1.0' (eg showing the version).

**Comment by jeremygurr** [comment]
ok I tagged and pushed it. Tell me if it didn't work right. I can't tell because it builds fine for me.

**Comment by alexjurkiewicz** [comment]
It doesn't look like you pushed any tag, it should show up here: https://github.com/jeremygurr/dcssca/tags

**Comment by jeremygurr** [comment]
Okay I pushed all of the tags. Tell me if there is a better way to do it, I've never forked a project before.

**Comment by jeremygurr** [comment]
Does this mean that whatever mechanism you are using to build will only build the version tagged with 1.0? It would be best to build HEAD. I could keep moving the tag, if that is best, but I hear that's not a good practice.

**Comment by alexjurkiewicz** [comment]
I don't think you need to keep moving the tag. I'm not sure how you were
building but the Makefile runs this:

```
SRC_VERSION   := $(shell git describe --tags $(MERGE_BASE) 2>/dev/null
```

|| cat util/release_ver)

`git describe --tags` only works if there's a tag in the release tree,
otherwise the Makefile uses the contents of `util/release_ver`. Since your
local repo was forked from the main DCSS one, you had tags, but until you
pushed a tag, anyone else cloning this repo had no tags and would have had
to write data to `util/release_ver` like I did. Does that make sense?

**Comment by jeremygurr** [comment]
Got it. That makes sense. Thanks.
