### ISSUE TITLE
Weird icons

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#10]
It looks like some icons are misplaced. Please see the picture: 
http://tinypic.com/r/25grneg/9
Cockroach looks like a Soldier Ant, Jackal looks like a Canine. Also I placed exclusions on both monsters and for some reasons 2 tiles were displayed as excluded despite no monsters are visible there (on the picture I am standing right in such place).

**Comment by jeremygurr** [comment]
I've seen that happen when I haven't done a "make clean" first. Usually make clean isn't needed, but some changes apparently throw off the tile assignment. Try a "make clean" followed by your normal make command, and see if that clears it up. 

-- Jeremy

**Comment by Sandman25DCSS** [comment]
It looks like Alex fixed the issue. Thank you both.
