### ISSUE TITLE
Weird message about cursed item

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#103]
"The cursed +9 plate armour of Prudence {*Noise +Rage rElec rPois rN+1411726126
 MR+32767 AC+32767 EV+11065473 RMsl SustAt} has been cursed"

Description of the item is really weird too, for example, it is inscribed with rMut which is not listed in the detailed description:

"F - the cursed +9 plate armour of Prudence (worn) {-Cast *Noise *Corrode +Rage
rElec rPois rN+1411731998 MR+32767 rMut AC+32767 EV+11065473 RMsl SustAt}.

A full suit of solid metal plate: cuirass, pauldrons, vambraces, waist plate and
greaves. It provides excellent protection. 

Base armour rating: 10       Encumbrance rating: 18
Wearing mundane armour of this type will give the following: 16 AC

It affects your evasion (+57631320).
It affects your intelligence (+57631332).
It insulates you from electricity.
It renders you almost immune to poison.
It renders you almost immune to negative energy.
It affects your resistance to hostile enchantments.
It prevents spellcasting.
It may re-curse itself when equipped.

It has a curse placed upon it. (1126) 
This ancient artefact cannot be changed by magic or mundane means.
You bought it in a shop in a bazaar.

**Comment by Sandman25DCSS** [comment]
Fortunately the curse was completely removed via 2 scrolls of remove curse.

**Comment by G0rg0** [comment]
That's a hell of a bonus to Int and EV!

**Comment by Sandman25DCSS** [comment]
It didn't affect actual stats, I still had normal AC/EV/Int. rMut/rElec/sustAbil wasn't listed in # screen either.

**Comment by jeremygurr** [comment]
Fixed.
