### ISSUE TITLE
Troll has weird aptitudes

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#104]
New Troll has -8 aptitude in spellcasting and -1 aptitude in most magic schools. That's weird, Troll has low Int and thus it cannot be a dedicated magic user due to low MP, low spell slots, high spell hunger and also low HP. How about giving it Magic Regeneration 1-3? It would work well with intrinsic HP Regeneration and low HP/MP.

**Comment by Sandman25DCSS** [comment]
Alternatively just revert the changes to magic aptitudes, there is no point in having +1 Earth when you cannot spam spells anyway.

**Comment by jeremygurr** [comment]
I like the magic regen idea. What do you think of splitting troll into two troll sub-races. Cave Trolls and Bridge Trolls (I'm open to better names :) ). The Cave Trolls would be like old trolls, high HP, high regen and hunger needs. The Bridge Trolls are stunted versions of trolls, having more health at first, but never increasing in health, but have magic regen in addition to the health regen. They have natural elemental resistances, but don't have the hunger issues of cave trolls. But they are very limited in magic capacity and spell memorization slots, so their magic usage is quite limited, forcing them to play mostly as a fighter augmented by basic spells.

**Comment by Sandman25DCSS** [comment]
Sounds good. The more species the better IMHO

**Comment by jeremygurr** [comment]
Fixed. We now have Cave Trolls and Moon Trolls

**Comment by Sandman25DCSS** [comment]
Thank you!
I love Moon Troll, it allows a new style which was never possible before: pure caster of Chei. I have only 31 MP and it looks like I regen 1-2 MP per turn, really fun.

**Comment by Sandman25DCSS** [comment]
Oh, it's 3-4 MP per turn now, wow...

**Comment by jeremygurr** [comment]
Sweet. I've been having fun with the Moon Troll too. Quite interesting. You'll have to tell me if the mana regen is too much. It's easy to tweak it.

**Comment by Sandman25DCSS** [comment]
I think MP regen is fine, I still teleported a lot while having high MP due to having low HP despite wearing amulet of regeneration.
I am not sure what the intrinsic mutations are. I had non-intrinsic Str-4, Robust+20%, MP+10% during the whole game, after loading the game today I saw that I am herbivore and have Slow 1 and Powered by Death 1 so I assumed that you are still trying to fix it. So I went ahead and quaffed potions of cure mutations to remove Robust and MP+10%.

**Comment by Sandman25DCSS** [comment]
I do have a +9 vampiric lajatang at min delay but even then it is not OP due to low HP, I barely use it. So I think balance is ok currently

**Comment by Sandman25DCSS** [comment]
I still have some non-intrinsic mutations:
A: unfitting armour, claws 2, fangs 1, cold resistance 1, conserve potions, fire
resistance 1, herbivore 1, gourmand, poison resistance, powered by death 1,
regeneration 2, shaggy fur 1, electricity resistance, slowness 1, tough skin 2,
magic regeneration 3, magic link
http://crawl.homedns.org/crawl/morgue/Sandman25/Sandman25.txt

**Comment by jeremygurr** [comment]
Oh no, there must have been a mutation enum change that scrambled the saved mutations. I'll try and track it down and restore it. That shouldn't have happened.

**Comment by jeremygurr** [comment]
Ok should be fixed now.
