### ISSUE TITLE
Don't generate monsters with blowguns on D:1

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#105]
I got this on D:1 while I was XL 1.

"A kobold comes into view.
 The kobold shouts!
 The kobold wields a runed blowgun. The kobold shoots a poisoned needle.
 The poisoned needle hits you (13)!
_You are lethally poisoned!"

I had just a single stack of potions, fortunately it was heal wounds (really lucky). And I cannot say that I had low HP or bad defense (HP 11, AC 7, EV 12), I got lethally poisoned during autoexplore.

**Comment by jeremygurr** [comment]
Wow that is pretty intense for level 1. Yeah we can push blowguns down a couple of levels.

**Comment by jeremygurr** [comment]
Fixed.
