### ISSUE TITLE
Allow retreating upstairs as first action after entering a new level

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#106]
I entered a new level and got a pack of Killer Bees, a pack of Wraith, a pack of Yaks and Water Moccasin 2 tiles away from me. No monsters were adjacent but I would be stopped by those Killer Bees.
How about allowing player to retreat upstairs immediately after entering a new level even if player is hit while doing it? I can imagine new players can be stopped in Vaults 5 the same way.

**Comment by jeremygurr** [comment]
I agree that it's a problem, and allowing a free return if it is immediate is one approach that would work. 

What if there was a way to look down the stairs first? Would that be too easy? 

Or maybe if you are standing on stairs, and there are a bunch of monsters below you, you hear them, and a message appears "You hear buzzing x3, you hear a bark x2". Or "you overhear orcs from down the stairs", or "you hear an ogre grunting from downstairs." But if it's a silent monster (one that never makes noise ever), then you don't get the warning. This message would occur each time you entered a stair or portal square, giving the player some warning. 

Or monsters don't notice the player when he enters a new floor, until the player either attacks or moves off of the stair square. It would be like the player is peeking down the stairs, and sneaks back up if he sees too much danger.

**Comment by G0rg0** [comment]
I think that last solution makes the most sense and will prevent inescapable insta-deaths.

**Comment by jeremygurr** [comment]
Fixed. You will now be able to escape immediately back up even if you are hit, as long as you don't do anything else first.
