### ISSUE TITLE
Zin should not accept VS

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#111]
Or at least it should request a confirmation. VS cannot use Lignify with Zin:
"Zin protects your body from unnatural transformation!"

**Comment by jeremygurr** [comment]
I made it acceptable to Zin for a VS to lignify, since it's not unnatural for them :)   This should take effect in existing games.

**Comment by Sandman25DCSS** [comment]
Great, thank you! I switched to TSO but will go back to Zin now ;)

Is it intended that even VS cannot regenerate in Tree form?
