### ISSUE TITLE
Using Pakelas' ability should not decrease max charges of a wand

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#114]
Your wand of teleportation (3/5) {!d} glows for a moment and now has 9 charges.

**Comment by jeremygurr** [comment]
I'm not sure about this. Pakellas basically gives you unlimited recharges for very little cost. It seems like it should reduce the lifespan of a wand just like a recharge scroll does. Or are you referring to the super charging ability? It looks like the supercharge ability should fully charge the wand to the maximum possible for the type, no matter how many times it was recharged.

**Comment by Sandman25DCSS** [comment]
I am referring to simple recharging. Pakellas does not give wands that often,  its gift rate is balanced around assumption that wands can be recharged using piety.
Here are my current gifts (including wands which I found on the floor) at XL 16:

g - 25 potions of magic {!q}
h - a wand of disintegration (11/24)
 i - a wand of iceblast (14/8)
 j - a wand of paralysis (1/24)
 p - a wand of hasting (5/9) {!d}
 q - a wand of heal wounds (6/9) {!d}
 r - a wand of paralysis (9/24)
 s - a wand of flame (17/24)
 u - a wand of teleportation (7/9) {!d}
 v - a wand of digging (21/12)
 z - a wand of slowing (25/48)
 D - a wand of acid (7/15)
 H - a wand of hasting (4/9) {!d}
 J - a wand of disintegration (9/24)
 K - a wand of iceblast (9/15)
 L - a wand of teleportation (3/9) {!d}
 O - a wand of polymorph (6/24)
 S - a wand of lightning (2/15)
 T - a wand of teleportation (9/5) {!d}
 U - a wand of iceblast (8/15)
 X - a wand of enslavement (8/24)
 Y - a wand of lightning (5/15)
 Z - a wand of heal wounds (3/9) {!d}

As you can see I got just 2 wands of acid, hasting, heal wounds and that's with faith and almost no piety used on actual abilities:
Invok: Quick Charge      |       |       |     2 |     1 |     3 |       ||     6
       Supercharge       |       |       |       |     1 |       |       ||     1
       Device Surge      |       |       |       |       |       |     1 ||     1
I am just afraid of using any abilities because I need more wands.

**Comment by jeremygurr** [comment]
Pakellas ability no longer degrades wands.
