### ISSUE TITLE
Tree Form is bad for VS middle/late game

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#116]
Tree Form completely stops natural regeneration, including enhanced regeneration of Vine Stalker. It results in Tree Form barely used after finding rPois, it's much better to have AC 13/EV 26/Regen 3 than AC 31/EV 2/No HP regeneration/Doubled HP provided it takes 3 turns to end transformation (that's my current game, I am at XL 16). The only situations where I use Tree Form is when I find a single monster like Menkaure or Curse Skull and no corners nearby and even then I am not sure if it is a good idea.

**Comment by jeremygurr** [comment]
Treeform now has full regen.
