### ISSUE TITLE
I don't like the shortened Orc branch

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#118]
I always had fun hacking through waves of orcs, and now I go one level down and am immediately facing the hardest orcs available. And often the first level of orc is a partial level, with only one downstairs (because the rest can only be reached by going through orc 2). Does anyone have a big problem with orc being 4 floors? I'm tempted to take it back to the way it was before. I don't understand the need to keep shortening the game. If I wanted to just rush to the end of the game, or I was in some kind of competition to complete many games in a short time, then I could understand. But I play the game to have fun with it, and frankly, the longer it goes the better, as long as it doesn't get boring. Long is bad when it's boring. But in that case, the problem isn't the "long" part, but the "boring" part, in my opinion.

**Comment by Sandman25DCSS** [comment]
I have mixed feeling. I liked 4 levels Orc much more than current Orc, now it feels like it's just another portal with shops as loot. On the other hand there is so much XP in the game that even hard mode characters still have XL 27 in 3 rune games. So it's up to you, personally I will be happy in both cases ;)

**Comment by jeremygurr** [comment]
That makes sense. The too much XP issue can be dealt with in better ways I think. If a game gets to the point where the player feels like they have completed all of the challenges, and it still drags on, then the game could either add more challenges, or shorten the game. But adding more challenges increases the lifespan of the game, as long as they aren't boring, and shortening doesn't. 

I'm pretty excited about the rune curses. And also making the lengthening of branches past the rune floor. I think those will add substantial lifespan and depth to the game. That will balance out the other features which will be making some things easier.

**Comment by Sandman25DCSS** [comment]
Looking forward to those changes...
Thank you for your hard work, the mod is really fun!

**Comment by jeremygurr** [comment]
orc is now back to the way it was before
