### ISSUE TITLE
Screen is not updated

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#12]
I am not sure if it has anything to do with the mod but the webtiles screen is not updated sometimes when going upstairs.
This is what I get after going up (I pressed > again and got "You can't go up here"):
http://tinypic.com/r/15wl3iv/9
And this is what I see after saving the game and loading it again:
http://tinypic.com/r/n1pkl0/9

**Comment by jeremygurr** [comment]
Hmm, this is a tricky one. Must be webtiles specific, because I haven't seen that yet in the local tiles version. I will look into it further.

**Comment by Sandman25DCSS** [comment]
I have seen the same issue in standard version so it is not related to your mod. Since it is not fixed there by webtiles specialists I guess you should just ignore the issue and spend your time on something more interesting :)

**Comment by jeremygurr** [comment]
cool. I won't worry about it then.
