### ISSUE TITLE
skill advancement seems a little weak

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#131]
Is it just me, or does it seem to be a lot harder than it used to be to train some decent skill levels? If so, I'll boost that a little. This experience change is huge, and will take some patience and serious testing to get it balanced properly.

**Comment by Sandman25DCSS** [comment]
I am not sure if it is relevant but after you fixed old_experience, my Cave Troll instantly got most skills decreased (Fighting, Armour, Dodging, Shields, Throwing) while UC skill was increased. The former have negative aptitudes, the latter has 0 aptitude.

**Comment by jeremygurr** [comment]
It is as I was explaining earlier, the old crawl mechanic uses a disjoint experience system, which moves fast at some points and slow at others, so for example it may be faster to get to level 10 UC with the old system but faster to get to level 15 UC with the new. Then it is faster to get to 27 UC with the old. The new system uses a smooth curve, so it is more predictable than one that has three arbitrary experience gain zones (less spoilery IMO), and of course it isn't limited to 27 fixed levels.

**Comment by Sandman25DCSS** [comment]
Thank you for the explanations! And for your patience to explain it to me several times ;)
