### ISSUE TITLE
No damage is shown for silver ego

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#139]
I threw silver javelins, just base damage was shown, not the one from silver component.
Not a big deal but would be nice to see, I was surprised that Orb of Fire died after receiving just 47 and 45 damage.

**Comment by jeremygurr** [comment]
Will do.

**Comment by Sandman25DCSS** [comment]
Thank you!

**Comment by Sandman25DCSS** [comment]
Please damage for pain brand also if possible.

b - a +6 scimitar of pain (weapon)
 You hit the giant frog (5). The giant frog writhes in agony.

**Comment by jeremygurr** [comment]
done
