### ISSUE TITLE
Movement penalty for cancelled action

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#143]
I walked a tile, pressed z to cast a spell, pressed Esc to cancel casting and walked another tile in the same direction. Yet I got a movement penalty (2.0 instead of 0.9).

**Comment by jeremygurr** [comment]
Yes that is a bug. I need to dig deeper into that to make it more consistent.

**Comment by jeremygurr** [comment]
fixed.
