### ISSUE TITLE
Hard mode gives 33% penalty to HP instead of 25%

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#144]
I am XL 15 mummy with fighting 12 and 80 HP.
In 0.17 the same mummy has 120 HP so it looks like the penalty is 33%, not 25%.

**Comment by Sandman25DCSS** [comment]
Oh, my math was wrong, I had amulet of vitality (it gives 15 HP) and the penalty affects it too.
So I have 85 HP without amulet and 95 HP with amulet. Still not 25%

**Comment by Sandman25DCSS** [comment]
You remove the amulet of Vitality {Regen+ HP+15}.
Damage: -12%(-10hp)   hp: 100%(85hp)
http://crawl.homedns.org/morgue/Sandman25/Sandman25.txt

**Comment by jeremygurr** [comment]
correct that was changed. Would you prefer 25%?

**Comment by jeremygurr** [comment]
Hard mode doesn't necessarily need any hp penalty at all. It's already heavily penalized with the new experience changes. But I'm not an expert on hard mode. I leave that to you. I'm quite experienced with easy mode though :)

**Comment by Sandman25DCSS** [comment]
33% is fine too as long as README is up to date. HP penalty is needed IMHO.
