### ISSUE TITLE
Line of sight has 5 tiles

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#15]
I have just realized that I can see only 5 tiles instead of normal 7, maybe it is related to diagonal move penalty.

**Comment by jeremygurr** [comment]
that was a bug. I fixed it though already. I had extended the LOS for the glow 3 mutation, but the LOS code is fragile and it broke other things, so I reverted the changes. 

-- Jeremy

**Comment by Sandman25DCSS** [comment]
Ok, thank you
