### ISSUE TITLE
Tomb 3 is unplayable without stairdancing

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#151]
I was a Mummy of Kiku meaning that I was immune to torment and mummy curses. Still I almost died several times, the level is full of monsters so teleporting does not help much.
The level is balanced around stairdancing so I suggest to either make an exception and allow stairdancing or decrease number of monsters.

**Comment by jeremygurr** [comment]
I think it's best to reduce the monsters to balance it, thus preserving the stair mechanics that players would be expecting. 

You would be the best to decide how much and which monsters. Isn't that completely controlled through the dat/des/branch/tomb file? If you could makes some tweaks there, I can make it to where you can push to a change branch on github, or if you'd rather, you can just email it to me. 

-- Jeremy

**Comment by Sandman25DCSS** [comment]
Unfortunately I am not very familiar with des format.
I've just checked tomb.des, it looks like the placement is done by tomb_guardian_set but I don't understand how it works :(

**Comment by jeremygurr** [comment]
Note to self: move the stairs on tomb to be far apart from each other.

**Comment by jeremygurr** [comment]
ok stairs have been moved apart and monsters have been thinned significantly.
