### ISSUE TITLE
Easy mode player ghosts have much more HP

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#153]
I got impression that easy mode player ghosts have more HP than normal mode ghosts and much more HP than hard mode ghosts. I suggest to limit ghosts to corresponding mode (easy for easy, normal for normal, hard for hard) or alternatively just provide a new option to remove ghosts completely.
It is not fun to run into extremely dangerous ghosts every time. In standard crawl they can be dangerous because there is stairdancing, in CA every ghost with ranged attack can lead to unavoidable death.

**Comment by jeremygurr** [comment]
hmm, that is a problem. If anything, easy mode ghosts should be easier than normal :) I'll have to look into that.

**Comment by Sandman25DCSS** [comment]
I suspected something like that but hoped you would not get it :) Now easy game will have hard mode ghosts only and hard game will have easy mode ghosts, right? :)

**Comment by jeremygurr** [comment]
fixed, but this will only apply to new ghosts created. There will still be some tough easy mode ghosts that need to be wiped out...

**Comment by Sandman25DCSS** [comment]
Thank you
