### ISSUE TITLE
Vine Stalkers can currently wear body armor.

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#156]
Also, voluntarily wearing none is no fun in my subjective opinion. This is because relying on tree form is tedious, like making good use of fedhas.

Some sort of way to automatically enter tree form might be less annoying, if risky.

Honestly I believe you could just leave vine stalkers alone, and focus on the really unpopular races like human (vine stalkers are a pretty great race as-is)

But anyway, vine stalkers can currently wear armor on the aussie 357 server, which is a bug. :)

**Comment by jeremygurr** [comment]
I'm not sure what version is on the aussie server, but I don't seem to be able to wear body armour on the latest version on my server. Other armour is allowed on vine stalker, just not body armour. 

What do you mean by voluntarily wearing none? You are referring to the fact that it should be forced, or that we should just do away with that restriction entirely? I'm okay with getting rid of the restriction. 

Some complain that I'm making too many races OP, but they don't realize that other parts of the game have become significantly more difficult, because of lack of stairdancing, kiting, and pillardancing. There are other changes coming soon that will also add substantially to the difficulty, making these seemingly OP characters too weak.

**Comment by yrmvgh** [comment]
I mean that we tried wearing no body armor in order to play the race as intended, due to the bug it was a voluntary restriction. This character: https://crawl.project357.org/morgue/mibe/

I don't think tree form is OP, I just think it's annoying to use repeatedly. :) It's a cool idea, but I wish it happened automatically ((maybe it could use the Tension mechanic to tree up for hard fights, but it would need to allow teleportation or manually disabling the ability to run away)) or was removed ((because vine stalkers are a fine race without the change))

Hope I don't sound too critical, I really really enjoy this fork. I came for the 104 slot inventory, I stayed for playable felids.

**Comment by jeremygurr** [comment]
I will probably make an "old species" option though before long, so that people that really like the original species can play them unmodified.

**Comment by jeremygurr** [comment]
No you don't sound too critical, this is helpful. Yeah I don't want it to be too annoying. The idea is that it should be similar to berserking, in that you shouldn't need it for every fight, but it's meant to give you an edge in the more intense ones, but to have an associated price with it like berserk. So I think I will add body armour back to the VS, and maybe increase the cost of using lignify somehow. The automatic thing wouldn't work if there's a significant negative cost to it, and also takes away the strategic decision of whether it's worth it to pay the price in a given situation or not.

**Comment by yrmvgh** [comment]
OH and another thing, it is saddening / unintuitive that you lose your VS body features (draining bite etc) when you tree form

**Comment by jeremygurr** [comment]
hmm... interesting idea. That makes sense that a VS should keep their features when in tree form.

**Comment by Sandman25DCSS** [comment]
Relying on tree form is not necessary for VS, it's possible to rely on EV.

**Comment by Sandman25DCSS** [comment]
I am not sure about increased cost of lignify. If anything, I didn't use it in intense fights, being able to blink/teleport/run is more important.

**Comment by jeremygurr** [comment]
Ok so maybe we can just give body armour back then and see how that plays.

**Comment by yrmvgh** [comment]
Maybe restrict them from metal armor, or heavy armor, or some other restriction, like a troll/ogre, to incentivize using tree form without forcing the player to activate it quite so often

**Comment by yrmvgh** [comment]
I am currently playing a "normal vine stalker" (barring myself from using lignify) on project357 to better familiarize myself with the race, as I haven't played it much

**Comment by jeremygurr** [comment]
ok vine stalkers can now wear armour.

**Comment by jeremygurr** [comment]
vine stalkers can use all mutations now while in tree form. So they get their bite back.
