### ISSUE TITLE
If I don't set any xp options in your rcfile, I seem to level unusually fast

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#157]
See the currently level 31 two-rune felid on the homedns server.

Also the dead kobold seemed to be leveling too fast as well.

When I enabled level 27 cap = true, the game appeared to take away a bunch of my skill points which freaked me out, so I reverted it and am now hiding from my mistakes, sneakind around in pandemonium (I thought it was an abyss portal, oops)

**Comment by jeremygurr** [comment]
Already fixed. I toned down the experience gain curve a few levels, which would affect your game when you went back in. I don't think it would change skill levels, since that is a different mechanism, but you should notice xp levels drop a few.
