### ISSUE TITLE
A short chat about movement

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#158]
-X-: what do you think about the movement speed changes?
  -O-: I think I'ma disable the movement changes cuz like... pillar dancing only works at low levels
  -O-: unless you manage to kill all the speedies, and still need to flee from the normies
  -O-: if you pull that off, well, go you. good job!
  -O-: plus like, combat movement is unnecessarily penalized in the attempt to quash pillar dancing
  -O-: minor repositioning shouldn't cost 2 turns
  -X-: it is inconvenient
  -X-: but, i think i might get used to it
  -X-: i do like being able to open up a space when fleeing
  -O-: if the values were exposed to rcfile editing, I could see doing like
  -X-: lol
  -O-: "movement change penalty += 0.3"
  -O-: instead of the current
  -O-: "movement change penalty == 2.0"
  -X-: i could see that
  -O-: but it's not exposed to editing like that so it's just all or nothing right now
  -X-: i think you might get a lot of the plus and less of the minus with a more moderate penalty
  -X-: jeremy said he likes to go big at first and then moderate over time
  -X-: i like that too
  -O-: I would probably remove the plus if I reduced the movement penalty that nuch. or make it super tiny, like 0.03
  -O-: the game can track very small fractional stuff already via randround

**Comment by jeremygurr** [comment]
This is fine. I like the idea of putting the movement penalty amount in an option. At least during the experimental phase.

**Comment by yrmvgh** [comment]
My original formatting made one line disappear and be treated as code, updated! Thanks for reading. :)

**Comment by jeremygurr** [comment]
ok there is now a movement_penalty option.
