### ISSUE TITLE
(misc small feature requests) Formicid can throw large rocks, but

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#161]
due to their smaller body size, they must (w)ield large rocks in order to throw them! :)

(just a silly feature request, don't be angry!)

**Comment by yrmvgh** [comment]
Remove mottled dracs from the list, or let us do so with an rcfile flag? Per an IRC discussion about drac colors: http://dpaste.unisolinc.us/mPg1

**Comment by yrmvgh** [comment]
Would it be possible to split wanderer into two (or three) backgrounds? One that's guaranteed to get at least one crappy spellbook, one that's guaranteed to get no spellbook, and possibly one with the existing fullrandom behavior?

(The reason for this being that Wn is great and fun for flexible races but tends to force reroll/scumming on the very specialized races.)

**Comment by jeremygurr** [comment]
It would be easier if each feature request was in a separate issue, then it can be discussed more cleanly, and marked closed when it is either rejected, or implemented. I will create the issues for these three.
