### ISSUE TITLE
Felids are now amazing, thank you!

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#162]
I have no issue with them. Cool stuff:

ONE, ru is now a plausible god for felid, because you can more safely afford to sacrifice hand, which is good because felids don't have a lot of non-crippling big sacrifice options

TWO, gozag is now plausible because he doesn't poop al the meat into gold

THREE, well obviously, equipment and getting your needful resists/passives is non awful now :P

**Comment by jeremygurr** [comment]
glad to hear it!

**Comment by Sandman25DCSS** [comment]
I've spectated a game with Fe of Ru and it looks like sacrificing a hand does not result in rings loss, Felid still could use 4 rings. Am I missing something?

**Comment by jeremygurr** [comment]
That's definitely a bug.

**Comment by yrmvgh** [comment]
People thought that I had 4 ring slots when looking at my % screen, but I finally found enough rings (took a long time, thanks Crawl!) and I definitely have only 3 ring slots.

**Comment by jeremygurr** [comment]
Cool.
