### ISSUE TITLE
Ds fart gas is significantly less useful than spiny

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#167]
Spiny damage:

is pretty high
takes effect instantly
kills stuff while you're paralyzed

Fart gas:

doesn't do a lot
requires a turn to spawn, then further turn(s) to take effect
mildly annoys monsters and the player

A recent commit on Crawl or CA (can't find it now, my bad) had a nerf to early-game spiny, slight buff to late-game, stating "at its current strength Spiny 1 will ensure you make it to Temple intact"

**Comment by jeremygurr** [comment]
what do you suggest here? What can be done to make the gas more useful?

**Comment by G0rg0** [comment]
Perhaps increase its damage or make it confuse? Maybe allow the player to lay down a cloud at will from the ability menu (in addition to the spawn on attack)?

**Comment by yrmvgh** [comment]
I believe that it should be either hacked to somehow immediately affect the monster when it pops up, or deal as much damage as spiny does (PLUS the cc side effects) as recompense for the 1 turn delay

**Comment by G0rg0** [comment]
An additional possibility - have the cloud grow bigger each time you're hit, up to say 3x3 or 4x4.

**Comment by yrmvgh** [comment]
The reason I couldn't find the trunk nerf to spiny... is because it is a PR not a commit, and at the time I didn't know the difference!

https://github.com/crawl/crawl/pull/249

**Comment by alexjurkiewicz** [comment]
On this, foul stench can apply significantly better effects to monsters than spiny, like irresistible slow. It's significantly better in late/extended since spiny damage against panlords/oofs is negligible while slowing them is ultra-valuable.
