### ISSUE TITLE
allow better management of save games in web site

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#169]
Allow user to create multiple games and when running an existing game, should automatically launch with the correct game version, to avoid crashes.

**Comment by G0rg0** [comment]
This would be great, very much like some of the other vanilla servers.

**Comment by jeremygurr** [comment]
hmm, which would you say is the best one in this regard? Maybe I can ask them for their config script and that would save me some time.

**Comment by jeremygurr** [comment]
Ok I now have it to where if you have a game already saved and try to start a different crawl version, it automatically selects the right one for you, until you have completed that game. This should save a lot of crashes and headaches. 

Warning: if you had a game started before this release, make sure you select the correct version that you started that game with. From then on, you will never be able to select the wrong version again. But if you choose the wrong version, the system will keep you on the wrong version, and you'll have to send me a message to fix your character. So get it right this one last time.
