### ISSUE TITLE
Crash when lignifying - ASSERT(eq == EQ_RINGS) in 'player-equip.cc' at line 147 failed.

### ISSUE THREAD

**Issue by alexjurkiewicz** [jeremygurr/dcssca#17]
cc @Sandman25DCSS 

```
ASSERT(eq == EQ_RINGS) in 'player-equip.cc' at line 147 failed.
```

Crashlog here: http://dpaste.com/13TFPYV

**Comment by jeremygurr** [comment]
This is for the character that had the armor in the wrong slot, right? I'm thinking that I fixed this already, but since you have the armor in the wrong slot, it will crash until a new character is started without that bug. Or is this a character with code built within the last few days?

**Comment by alexjurkiewicz** [comment]
I'm not sure, sorry, but the code is a few days old.

**Comment by jeremygurr** [comment]
did you start the character fresh with code that is a few days old? I think this is the result of a bug that is already fixed, but it's hard to tell for sure. I haven't seen it in my tests yet, but I might be missing something. I'll keep looking though.

**Comment by alexjurkiewicz** [comment]
I wouldn't investigate further until sandman25 comments -- it was his game.
I've updated the code on CPO, so we can see if the problem returns. Thanks!

**Comment by Sandman25DCSS** [comment]
Yes, it is the character who has body armour in helmet slot. I think the crash happens only for this character since it tries to meld everything.
