### ISSUE TITLE
replace movement penalty with stamina system

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#170]
Okay the stamina system seems like it will completely take care of the problems that the movement penalty mechanism is meant to solve, do a better job of it, and be easier to understand (maybe...). So once I get this completed and deployed, is there any reason to keep the movement penalty mechanism?

The stamina system will work as follows: 

There will be a pool of stamina, just like hp and mp, with a bar showing up under mp (or maybe between hp and mp). It will recharge much faster than mp or hp. Normal "walking" movement speed for ALL species will be at least 1.1 (higher for nagas of course), which is slightly slower than most monsters. Movement while "walking" will not cost any stamina points. But a player may switch to running, which moves at either 0.9 or the faster speed of a species (0.6 I think for a spriggan). Running burns sp about twice as fast as it normally regenerates. So doing something that doesn't cost sp for 8 turns will generate enough sp for 4 turns of running. The sp pool will be large enough for most species to escape a dangerous situation, but not so big that pillar dancing and kiting become viable strategies. 

Of course there will be sp boosters, and monsters that drain sp, and some abilities may burn sp (berserk would burn sp instead of using the "Exh" status). Maybe breath weapons would also use sp, I'm not sure yet. There is a lot of potential here to enrich the game with new monsters, potions, abilities, randarts, etc. 

Stamina pool size _may_ go up slightly with xp levels, but I'm not sure it's necessary or even a good thing. The pool size likely will vary between species, adding further distinction between them. However, items may extend the sp pool size too (like rings of magic power). 

Maybe "running" mode could be generalized to a "high power" mode, where movement is faster, but attacks are also more damaging, but burn through sp as a result. So if you do a bunch of power attacks, you will be too exhausted to run away, and so are taking a big risk. There will be a status indicator to show "power" mode, which is of course dangerous to leave on. Power mode automatically turns off when stamina runs out, and can't be turned on again until it's at least half full. In power mode, damage, spellpower, and attack speed should be enhanced a little, maybe by 25%, but accuracy would be reduced.

We could have a "careful" mode that is the opposite of "power" mode, but would also burn sp just like power mode, so it couldn't be used forever. But it would lower attack damage and spellpower, but would significantly increase accuracy and spell success rate. It would also increase stealth. 

We can also use sp as a means of better dealing with heavy armour or weapons. Strength weight has been removed, which I'm glad about, but it still lost an important aspect that distinguishes weapons. If you have a character with str 5 trying to hit another with a heavy executioner's axe or great mace, you would think it wouldn't be as effective as an ogre with str of 30 swinging it around. Granted, the way that str increases the damage already handles the damage difference needed here, but for a weak character to be swinging around a heavy weapon, or move around in heavy armour, that's got to be exhausting. So maybe that could translate into slower sp regen, and/or faster sp loss when in "power" mode. 

It's possible we could make vampiric weapons slowly drain stamina regen whenever they do damage, to keep them from being too powerful. Or health regen items could drain stamina when their health is below full. Lots of possibilities here. 

Haste can also be tempered a bit by causing it to burn through stamina also. Maybe it just forces the player to be in "power" mode, and once there isn't enough sp to support "power" mode, the haste effect goes away. Likewise maintaining invisibility or a transmuted form could cost sp. Probably not for a transmuted form.

**Comment by Sandman25DCSS** [comment]
I am not sure we need a reliable way to avoid any fight. Running away from adjacent monster should require some consumable or spell IMHO.

**Comment by jeremygurr** [comment]
Are you saying that even with the stamina system, we should keep the movement penalty? Or that the ability to run away at 0.9 is too much?

**Comment by G0rg0** [comment]
I much prefer the basic idea of a stamina pool over the new movement . I am sorry - I know you put a lot of thought and effort into it, I just don't like how it feels while you are playing and want to run away from something. I primarily play casters, and running away is just something you have to do sometimes.

If you do implement stamina, it should be something not overly complicated to the player. Some simple way to toggle between run and walk basically.

**Comment by jeremygurr** [comment]
Okay, how about this then: the letter 'e' (for exertion) activates "power mode", hitting it again cancels it. It doesn't take any turns, since it just modifies the next action taken. 'E' will switch to "careful mode". That's it. The only other complication is all of the potions, monsters, abilities, etc, that interact with it :), so it will basically be as complicated as hp and mp, plus the extra two keys.

Oh yeah, I know, 'e' is normally used for eating. Eating will be gone soon, so 'e' will be available :)

And although I think the movement penalty thing is a cool solution, I'm happy to remove it to make room for a better.

**Comment by G0rg0** [comment]
I would swap the lower and upper case actions ("E" for Extra-power!) but otherwise perfect.

**Comment by jeremygurr** [comment]
I was just thinking that you would use power mode more often than careful mode, and since 'e' is much easier to hit, that would save keyboard effort. Can that kind of thing be changed in the rc file? I guess it can be changed with a macro if not.

**Comment by G0rg0** [comment]
Oh, I missed the careful mode you had listed, I was thinking of careful as baseline/normal exertion. Your way makes more sense.

**Comment by Sandman25DCSS** [comment]
I assumed that it would be possible to safely run away from every same speed monster by activating power mode. That could result in too easy game.

**Comment by jeremygurr** [comment]
It would be no easier than it is now, since running away now is at 0.9 movement speed for the average species. Well, slightly easier if we remove the movement penalty, since you won't get penalized for rounding corners.

**Comment by G0rg0** [comment]
I was reading it as you get a chance to run away from a fight and if you get to safety, recover your stamina, but you can't just endlessly escape from fights.

**Comment by jeremygurr** [comment]
Correct. If you ran away only to encounter another group of bad guys just when your stamina was about empty, you wouldn't be able to just keep running. You would be forced to use a consumable, like a stamina potion or teleport. 

I'm not sure that we should get rid of the movement penalty entirely. Maybe it could just be reduced to 1.5. I think it adds some valuable depth and strategy. But I'll leave it as an option so it can be turned off for those who really don't like it. I hope everyone is following the commits, or at least the changes to the readme, so they keep on top of the rapid changes I keep making :)

**Comment by yrmvgh** [comment]
> Of course there will be sp boosters, and monsters that drain sp, and some abilities may burn sp

I wouldn't call this a given. Hungry ghosts are more annoying than interesting, and most other "hunger attacks" have been removed from trunk.

> The pool size likely will vary between species, adding further distinction between them.

This risks being a fiddly little difference like the difference between 70 and 80 in the old apt system. Variations are fine, but they should be infrequent enough and big enough to be worth mentioning in the species' traits.

> ALL species will be at least 1.1

Are you sure about this? Frail spriggans **need** to kite right now. They cannot survive protracted games of slappy-fighty. I guess they could stay permanently in run mode if they're doing something every other turn, but they'll probably need some additional help in the stamina game.

> it could just be reduced to 1.5. I think it adds some valuable depth and strategy.

The annoying thing is it seem to care about which direction you STARTED moving, not which direction you've BEEN moving. If, due to dungeon layout, I start out by moving 1 tile SE, then I move S for 15 tiles... logically my momentum is southward and I should be allowed to go SW. But that's not the case, I can actually pull a hard turn E at no penalty since my movement started out with a single tile of SE, but I can't go SW safely even though I've been running south for awhile now.

**Comment by jeremygurr** [comment]
I think spriggans will be helped significantly by the fact that they consume stamina half as quickly as normal. Add that to their movement speed advantage, and they have the best chance of pulling off kiting of any species. Extended kiting is still not possible, but spriggans will definitely be able to get away with a lot more than any other species in this regard.

Yeah maybe the movement penalty speed system just needs to completely go away. I've already defaulted it to off in the latest version. 

As far as stamina differences between species: I agree. I'm not interested in little inconsequential differences (hence most of my changes to species in this fork). 

Spriggans could have half stamina consumption rate for movement, but special abilities would have the normal cost.

Mummies could have no stamina penalties for special abilities. 

Trolls could burn sp twice as fast as normal, to replace their "hunger". So basically they are not so great at long escapes or prolonged "power" mode battles. 

Nagas and Centaurs could have a larger than normal sp pool. Centaurs could use it for short term kiting, or to pull off longer, more difficult escapes. Nagas could use it to dish out a long string of punishing blows against their enemy.

**Comment by jeremygurr** [comment]
done
