### ISSUE TITLE
Logfiles location for Sequell

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#171]
The IRC bot sequell doesn't announce our milestones and deaths - to do so it needs to know where to find a file that looks like this:

https://crawl.project357.org/dcss-logfiles-0.17

**Comment by jeremygurr** [comment]
oh cool. I'm not sure we want to announce them though since this project is so unstable at this point? I think it can get to a stable point before too long though where it would be meaningful to have victories. But I guess I can put up the logfiles easily enough anyway if someone cares about it.

**Comment by yrmvgh** [comment]
On a barely-related note, how would you feel about hosting .17 and/or trunk on your server? Now that cszo is down, a lot of people are looking for a good place to play, and your server seems to be smooth and lag free, for me.

And that'd a few dozen more people who might occasionally check out your fork and have good feedback! :)

**Comment by jeremygurr** [comment]
I would host .17 also if I could afford to cover the server costs, but it's likely with a heavier load I'd have to come up with more money for more network bandwidth and processor power. Maybe at some future time when I'm in a better place financially. As it is, I worry that if this fork does become popular too quickly, the server that I'm using wouldn't be up to the task.

**Comment by yrmvgh** [comment]
Ohhh, okay. I'll stop promoting it and try to keep it hush hush then.

Don't talk about circus club.

**Comment by jeremygurr** [comment]
lol okay. Hopefully I'll be in a better place soon and it won't be a problem to keep the server going even under a heavy load.

**Comment by Sandman25DCSS** [comment]
I'll stop advertising the branch too. Sorry, I didn't know. I will play less, it can help ;)

**Comment by jeremygurr** [comment]
(light laughter) you don't need to stop advertising and you don't need to play less. If it gets popular enough to slow down the server significantly, it will probably pop up on other servers. So far, it is far from being overloaded. Load average 0.05 with 2 active players.

**Comment by Sandman25DCSS** [comment]
Ok, thank you for explanation ;)

**Comment by yrmvgh** [comment]
If you _are_ interested in a few new players, you might want to consider having the movement changes default to off, and then only turn on via one or more of the following:
1. selecting Hard Mode
2. RC file option
3. adding in movement options to the easy/norm/hard mode selection screen

Because when I **was** promoting this fork on IRC, the movement changes were cited repeatedly as a reason that people tried the fork a bit, stopped playing it, and recommend against playing it. These people include mildly-famous player zxc and developer gammafunk, though for all I know it's partially due to his significant personal investment in stone soup trunk.

**Comment by jeremygurr** [comment]
Done. Movement penalty defaults to 0 now. Makes sense since it will be replaced soon with stamina anyway.
