### ISSUE TITLE
Sorting option for inventory letters.

### ISSUE THREAD

**Issue by G0rg0** [jeremygurr/dcssca#175]
I had an idea about the letter management of items. It would be great if there was a "sort" option that would re-order letter assignments everything in your inventory.

As an example, your char has been roaming about picking up and dropping stuff and now all of the letters for things are scrambled. The next two items you pick up could be assigned "g" and "Q" or whatever. It's not overly confusing, but does start to get annoying (for me anyway). I'd love to open my inventory and see everything listed a-z, A-Z. I could see leaving an exception for a,b for weapon switching. 

The command would live under the existing "=" menu. So maybe "=" > (s)ort > (i)tems/(s)pells? Hit it and everything gets shuffled.

The usual reassign command would stay of course.

**Comment by jeremygurr** [comment]
I'm not against this, but it's not interesting enough for me to code it anytime soon. But I'd accept a pull request for it :)

**Comment by Sandman25DCSS** [comment]
It is not needed IMHO

assign_item_slot = (forward | backward)
        When picking up items, the inventory slot into which the item
        goes is normally the first free slot from a-zA-Z (this is the
        default "forward" behaviour). Setting assign_item_slot to
        "backward" changes the slot assignment to the first letter after
        the last slot.
        For instance, if you have items on 'a' and 'c', then with
          assign_item_slot = forward, the next item will go into 'b',
          assign_item_slot = backward, the next item will go to 'd'
        instead.
        With "backward", items dropped/fired and picked up later are
        more likely to get their old slot back.
https://raw.githubusercontent.com/crawl/crawl/master/crawl-ref/docs/options_guide.txt

**Comment by Sandman25DCSS** [comment]
Or maybe I am missing something.

**Comment by G0rg0** [comment]
I'll give the backward option a try and see how it goes. 

It's absolutely not a big deal, I just thought it would be nice to have a "one-button cleanup" to sort things so the inv menu looked like:
![screen shot 2016-04-12 at 11 36 14 am](https://cloud.githubusercontent.com/assets/17931524/14471316/d4cc8814-00a2-11e6-86a5-ed3e9da0f764.png)
rather than this:
![screen shot 2016-04-12 at 11 31 05 am](https://cloud.githubusercontent.com/assets/17931524/14471193/254aca40-00a2-11e6-8904-e99197919e30.png)
