### ISSUE TITLE
what do you think of the new experience modes?

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#179]
See the readme for detail. 

Is there a fun one missing? Is one completely useless? Is one hard to understand?

Here's something you can paste into your rc file to easily switch between them. I'll make a nice in game menu eventually, but I don't want to spend the effort before being sure it will stay. 

```
#experience_mode = classic
#experience_mode = simple_xl
#experience_mode = simple_depth
#experience_mode = balance
experience_mode = serenity
#experience_mode = intensity
#experience_mode = pacifist
#experience_mode = destroyer
```

Just uncomment the one you want to try (like serenity is above). Note: the old experience parameters won't work anymore. This has replaced those.

**Comment by yrmvgh** [comment]
Oops, didn't realize it was a n RC thing. I'll try adding it to my game in progress.

**Comment by yrmvgh** [comment]
In general I find the game much harder with these modes, because when I encounter an early Grinder, the exp is in my inventory, not in my character. ;) I don't think I've made it to Lair yet with any new modes.

Probably just need to adapt my playstyle to it. It would definitely be wise to quaff exp when you're holding more than 1.

**Comment by jeremygurr** [comment]
Yeah I've found that also. I'm getting better at it though and can clear lair at least on a few of them. The hard thing to learn is not to carry the potions forever. 

Keep in mind though that simple_xl and simple_depth don't use potions at all, so they have quite a different playstyle (a "simpler" one :) )

I'm particularly liking serenity though because I can still hold on to potions to make the game harder, and obtain a better long term reward, but I'm also getting a fair bit of experience from monsters and new floors during that waiting time. It's probably the most easy going of the bunch, except for maybe the two simples.

**Comment by yrmvgh** [comment]
My latest character (the fresh kobold in the server morgue!) died to a worm on D:2 despite a sweet dagger of protection... I was still XL1 despite diving to floor 3 (just for the xp) and quaffing both exp pots I'd found. Yeah, I'm gonna call that one not my fault. I'm not gonna use consumables on a worrrrrrm! :)

But do let me know if you see what I was doing wrong! Gonna try another mode.

**Comment by jeremygurr** [comment]
which mode did you try? It's quite possible that some (or most) of these modes need further balancing. They are fresh off the press with very little real testing behind them. 

The hardest part to balance though is those first few levels, since many of these modes get very powerful by about mid game (maybe too powerful in some cases), it's tricky to keep that in check, and still make surviving early game possible.

**Comment by jeremygurr** [comment]
Maybe I will make a hard minimum for levels and potions, so that it doesn't affect later game, but still gives early players a needed boost.

**Comment by yrmvgh** [comment]
I think it was on serenity. I can't figure out which morgue file it is. Lotsa KoWn in there. :(
