### ISSUE TITLE
Crash when reading scroll of summoning

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#18]
Got a crash with message "spell of 4294957303 out of range 0 (0) .. NUM_SPELLS (337)" when reading unknown scroll which turned out scroll of summoning.

**Comment by jeremygurr** [comment]
can you attach the crash dump?

**Comment by Sandman25DCSS** [comment]
Sorry, I didn't know I can access them.
https://crawl.project357.org/morgue/Sandman25/crash-Sandman25-20160302-002131.txt

**Comment by jeremygurr** [comment]
Fixed.
