### ISSUE TITLE
fix hunger

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#180]
Ok I think it's time to fix hunger, to prepare for the stamina feature. Or maybe it will go out at the same time as the stamina feature, since they may rely on each other. Of course we'll have to do something about the vampire, and probably mummy.

This probably won't be an option, so I want to be sure to get it right. 

What good does hunger and food currently accomplish? We want to keep as much of the good as possible and eliminate the bad. 

As far as I can tell, hunger avoids some scumming practices and compels the player to move forward. But it is so long term that it rarely creates any meaningful decisions for the player, and often creates tedium. 

Hunger also provides some nice flavor distinction for the undead species. 

Hunger also supposedly limits high powered spells, but I really don't see the need to limit spells both with mp and hunger. If they need to be more limited, we can make higher level spells cost more (coming later...)

So...
Option A: keep hunger, but implement auto-chopping and eating of corpses when resting. 

Option B: remove hunger and chopping, but keep eating. Eating can still be used for some special effects (giving health or removing rot from ghouls), restoring stamina more quickly?

Option C: remove hunger, chopping, and eating. 

I'm having trouble finding any significant losses from implementing C that can't easily be given back by a different mechanism. For example, ghouls eating corpses to heal rot. When a monster dies, there is a chance that the corpse doesn't drop, and instead the ghoul gets healed. No effort at all on the part of the player. Mutagenic corpses can of course be replaced by mutation potions. Hunger costs of high level spells instead consume sp (if that's even necessary). 

We can keep fruits in the game for fedhas and fun flavor for various vaults. And eating a fruit can give a fixed boost of stamina. Maybe royal jelly could have some special effect like making all stamina costs be 0 for a limited time after eating it. But other food would be gone. So I guess this would be more like option B. Seems a little silly to have an important keyboard spot taken by something so rarely used. They would be effectively the same as potions, since they are one time use consumables. So maybe the 'q' command can also list these food items. Quaff a fruit?

For the vampire, they could keep their "blood meter", and still quaff potions of blood to increase it. So they wouldn't change at all. 

For mummies, maybe they don't have stamina at all. They wouldn't be able to switch to "power" mode to run away or "careful" mode to sneak, but they would be able to spam channel energy and high powered spells just like before. 

Spriggans low food requirement could just translate into their actions requiring half as much stamina as normal.

**Comment by G0rg0** [comment]
I love these ideas, and I say go full on option C and instead of fruits for Fedhas, put in seeds. Instead of royal jellies, add a honey potion with the stamina boost effect.

Mummies already get hit pretty hard with no potions, I'd say give them stamina to allow for power/careful modes. It can always be tweaked if it turns out to be too powerful.

**Comment by jeremygurr** [comment]
Hmm, makes sense.

**Comment by yrmvgh** [comment]
A friend of mine who plays mostly casters and I (who play mostly warriors) trade tips now and then. _(that is a boring story, but it illustrates that I'm about to repeat unverified hearsay ;)_

He told me that spell hunger balances the highest level conjurations, which can't be spammed unless you periodically eat, or give up a slot to wield the -hunger spell staff. YMMV, but that's the only thing I know of that might need to be adjusted if food was removed.

**Comment by G0rg0** [comment]
If the mana pool turns out to not be enough of a limiter, the highest lvl stuff could get a stamina cost tacked on. It'd be essentially the same as the mana/hunger mechanism. 

Also - even the highest lvl spells can be cast hungerless once you've got your int and skills up so the hunger issues just slow down your power growth. 

Hrm, now that I say that, I wonder if removal of hunger would help address some of the issues with casters and the new movement?

**Comment by jeremygurr** [comment]
I was thinking that the cost of spells is odd, fitting an arbitrary linear scale. This creates the weird situation that a level 2 spell costs 100% more than as a level 1, but a level 5 spell only costs 25% more than a level 4 spell, and a level 9 is 12% more than a level 8. 

It makes a lot more sense to me that although a level 1 spell may cost 1 mp, a level 4 spell should be closer to 16, and a level 9 spell possibly costing 100. But I think it should scale with spellcasting skill also. There's a lot of fun things I want to try with the magic. But those are for after I've implemented stamina, identification rework, and rune curses.

Yeah I was thinking that too about the stamina. We could easily add a stamina cost that scales up exponentially with spell level if necessary. It will take some experimenting.

**Comment by jeremygurr** [comment]
But the trend in vanilla crawl has been to simplify many of these kinds of things (which I like). The str weight change, for example, was a nice cleanup of a muddy mechanic. If we could fit magic usage to mostly using mp (except maybe for some rare cases), and fighter activities and abilities to mostly sp, that might make for a better gameplay experience overall. It never made sense to me that many abilities have an mp cost associated, especially ones that would almost exclusively be used by non-magic users.

**Comment by yrmvgh** [comment]
> It never made sense to me that many abilities have an mp cost associated, especially ones that would almost exclusively be used by non-magic users. 

These are kinda nice in that they give nonmages "something interesting to do" with their mana, and have a sort of natural limit to spamming not achieved by most hunger and piety costs.

If you switch those abilities to a stamina cost, they'll actually become "something interesting to do" with an unused stamina pool, good for nonwarriors. ;)

**Comment by jeremygurr** [comment]
I can understand an ability that actually used a meaningful amount mp, where mp was used to limit it in a real way, but losing the 2 or 3 mp for many abilities doesn't impact my game at all in many cases. 

For example, it costs 5 mp to forget a spell with Sif. How would that ever affect real gameplay? Is it just so that it can have a cost, so it feels more substantial? Are we worried about people spamming spell forgetfulness? Is anyone going to ever be in the middle of battle, low on mp, and need to be able to forget a spell, but can't because they don't have sufficient mp? There are many abilities that are like this.

Take fedhas' growth, requiring 2 mp and a fruit. Why? What impact does the 2 mp cost make? It only adds needless complexity IMO. 

Now some abilities are really spells in disguise, and so it makes perfect sense that the cost for them would be in mp.

But I think all abilities should have 1 cost, not a combination of 3 (in many cases). Combination costs do make sense if there are different game situations where each cost actually becomes a meaningful limiting factor, and would affect the player's strategy somehow. I really doubt that is the case for may of these abilities. 

So abilities should either cost piety, mp, hp, sp, pmp, php, psp, or an item (like fruit or a remove curse scroll). Pick exactly one. And the piety ones should tell you how much piety they require. I don't think that keeping piety numbers shrouded in mystery is doing the player any favors. One ability uses "a little piety", another uses "a lot of piety". What does that mean? Is it 1 vs 20 points, or is it 1 vs 2 points?

**Comment by yrmvgh** [comment]
Haha, you have some great points on those abilities. I was thinkin the ones that cost mose like 8... whatever god that is. And the opaque piety costs drive me nuts too, since I rarely play the same god twice in a row.

**Comment by jeremygurr** [comment]
done
