### ISSUE TITLE
unknown monster: "deep dwarf necromancer"

### ISSUE THREAD

**Issue by alexjurkiewicz** [jeremygurr/dcssca#186]
Startup error:

```
../dat/des/branches/dwarf.des:158: unknown monster: "deep dwarf necromancer"
```

**Comment by alexjurkiewicz** [comment]
Looks like the problem is the dwarven branch resurrected refers to deep dwarf monsters, but the only remaining dd monster is "deep dwarf". There are several "deep dwarf foo" entries that need to be fixed up.

**Comment by jeremygurr** [comment]
yeah that is work in progress. From master, right? If you just checkout from the release branches it will work. Checkout v1.2.3 for the latest.

**Comment by alexjurkiewicz** [comment]
ah. here's a quick and dirty edit of the DES files so the game works: http://sprunge.us/AXCQ

**Comment by alexjurkiewicz** [comment]
fwiw, CPO will be compiling trunk daily from now on -- is there a better target I should compile daily instead? I don't want to have to pay attention to changing release tags because i'll be slow like the last few weeks, so the alternative would be if you kept a branch running called 'stable' or something...

**Comment by jeremygurr** [comment]
it's nice that you are automating trunk deployment. I will get master compiling and I will put bigger changes onto branches and then merge those into master once stable.
