### ISSUE TITLE
Invisibility spell is unusable for Halfling

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#19]
I casted Invisibility spell as Halfling, it was at 5% (light red) with wizardry without extra enhancers so I guess it is pretty minimal spell power (123) you can ever get. Still I got a mutation from contamination which is extremely bad since Halflings cannot cure mutations.
I suggest to either block mutations from contamination, make them curable or at least provide a warning before casting Invisibility.

**Comment by jeremygurr** [comment]
Definitely sounds like something is wrong there. I will test that out. 5% failure rate and it still gave immediate mutation? Or were you contaminated beforehand?

I don't understand why Halflings can't cure mutations. Cure mutation potions don't work on them? I don't think I did that intentionally. They are highly resistant to mutations but if anything that should mean cure mutation potions work better.

**Comment by jeremygurr** [comment]
Fixed. Now cure mutation works just as well for mutation resistant players as normal.

**Comment by Sandman25DCSS** [comment]
Thank you!
