### ISSUE TITLE
Food shops carry muta meat

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#194]
This fork is about making boring things non-boring, and what's more boring than a food shop?

Granted food seems to be on the way out of circusfork, but until that time it'd be cool if food shops sold the only interesting food in the game!

A fruit guarantee wouldn't hurt either, to be less disappointing to fedhas worshippers. (but I'm never playing fedhas again so I don't care :laughing: )

**Comment by yrmvgh** [comment]
Muta meat has been added to food shops, please keep an eye out for it! If you don't see it, or if food shops seem understocked, then it's possible that the chunks are rotting away, but I'm hoping that rot doesn't happen in shops.

**Comment by jeremygurr** [comment]
only problem is that it will go out with the next deployment, which also includes eliminating food... sorry. Maybe we can add more mutation potions to shops? It might be interesting to see if we can come up with a fun replacement for food shops.

**Comment by yrmvgh** [comment]
Yeah, that was a potential conflict I was aware of. No problem, it's really fun just messing with code and feeling like a glimmer of understanding is coming to me.

My thoughts on purple chunks/pots: if food is going the way of the dodo, obviously so should chunks. The problem this introduces is that chunks were a safe(ish) way to give yourself one mut at a time and (probably) not hyper-screw your character. Whereas a potion of mut may blow you right up.

In the future, so that they're not a terrible idea to use, mutation potions should only give you 1 mut at a time, cost less gold, and tend to be found in stacks of 2 to 4 in shops. They should be a bit more common on the ground, or "distillable" from purple corpses - there used to be a spell that did that, maybe the code can be re-used.

Or, you know, whatever solution is less work for you. "Good enough" is better than "ideal-but time consuming" when we're not talking about big things like the stamina system.

Might also be nice if cure mut had a small, say 5 or 10%, preference towards removing bad muts over good ones. Hell, maybe it already does.
