### ISSUE TITLE
Could wands, or books, be kept in inventory 2?

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#196]
So far, I have plenty of space if I dump off all my spellbooks somewhere. But if I want to tote around wands AND books, inventory 1 fills up, usually with 15 to 25 slots available in inventory 2.

I think books makes the most sense, as that would allow you to restore books to their old spot in the (r)ead menu, and it keeps all the evocables in one place. But either one would help!

**Comment by jeremygurr** [comment]
Wands can't be in inv2 because all evokables need to be in inv1, but books are a good possibility, since other "readables" are there.

**Comment by G0rg0** [comment]
Inv2 makes sense, having them available with "r" would be good.

What about having a master spellbook? Essentially "goldify" spells by adding any new spells found in spellbooks to your master tome.

**Comment by yrmvgh** [comment]
That sounds pretty complex codewise, gorgo, but who knows - ol' Gurr is a fast-iterating code wizard! Cool idea.

**Comment by jeremygurr** [comment]
I've actually been considering that for a while. The only thing stopping me from goldifying books is that maybe some players don't want to see a long list of possible spells. But it seems like the positives may outweigh the negatives here. Is anyone really against goldifying spellbooks? Maybe I should ask on the forums.

**Comment by yrmvgh** [comment]
Maybe it could be optional instead of forced. All players know the spell "combine books", which is bound to Z and combines the books that are currently in your inventory. Or it's an (a)bility. Or it's a hidden, context-sensitive option that triggers when you drop a book on the ground. "You dropped Fen Folio on a tile that contains The Akashic Record. Would you like to combine them into a Personal Spellbook? Capital Y or N, please." (could break the skill requirements for akashic, so maybe those specific books have to be immune)

**Comment by jeremygurr** [comment]
I'm thinking the only real issue people will have is losing Trog's ability to burn spellbooks. Maybe we can come up with an alternative.

**Comment by G0rg0** [comment]
The combine book ability/spell would take care of it for Trog worshippers. If they didn't combine them, the books would still be in their inventory  for throwing.

**Comment by jeremygurr** [comment]
yeah but it's a bit tedious for the majority of cases where the player just wants it goldified always. Just putting it into the consumables inventory seems to solve the problem here and it's the easiest solution.

**Comment by G0rg0** [comment]
How about the reverse? Trog worshippers can "pull" a book out of their personal spellbook?

**Comment by G0rg0** [comment]
That said, I don't see enough of an advantage over just doing the simple thing and moving books to inv2.

**Comment by jeremygurr** [comment]
done
