### ISSUE TITLE
In WebTiles, scroll/potion/ring icons are all jumbled up

### ISSUE THREAD

**Issue by eyestalker** [jeremygurr/dcssca#199]
Unknown scrolls seem to look okay. Unknown potions (and known ones?) have scroll icon underneath the potion icon, rings too, some scroll symbols seem to be messed up (I recall tele scrolls using scroll of summoning icon in my last game).

**Comment by eyestalker** [comment]
On closer inspection, rings, at least known ones, just use a scroll tile.

**Comment by jeremygurr** [comment]
yeah this one is annoying. But because it's just cosmetic, and because I have no clue what would have caused, it, I have put it at a lower priority than other bugs. But I would welcome any help!

**Comment by jeremygurr** [comment]
fixed
