### ISSUE TITLE
MP don't regenerate

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#20]
My HaEn can no longer regenerate MP, I am stuck at 2 MP.

You see here a club.
You start resting.
You start resting.
You see here a club.
You start resting.
You start resting.

Health: 105/105    AC: 20    Str: 23      XL:     16   Next: 62%
Magic:  2/25       EV: 27    Int: 34      God:    Cheibriados [******]

https://crawl.project357.org/morgue/Sandman25/Sandman25.txt

**Comment by jeremygurr** [comment]
Now that's a weird one. If you can get me the save file, I can attach a debugger and figure out what's going on.

**Comment by jeremygurr** [comment]
Do you have any summons? Does the "release summons" ability appear?

**Comment by Sandman25DCSS** [comment]
I have some undead allies only. I will try destroying them and will see if it helps.

**Comment by Sandman25DCSS** [comment]
Yes, when I destroyed all undead allies, MP started regenerating.

**Comment by jeremygurr** [comment]
Where did the undead allies come from? I need to make a distinction between allies and summoned characters, so this kind of issue doesn't happen. Not exactly sure how just yet...

**Comment by Sandman25DCSS** [comment]
I casted Animate Skeleton a few times to create the allies.

**Comment by Sandman25DCSS** [comment]
Maybe you can create a new flag and set it for Animate Skeleton/Dead/Simulacra/Death's Channel monsters

**Comment by jeremygurr** [comment]
Fixed.
