### ISSUE TITLE
# feature outputs bad URL

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#201]
If you hit #, it generates a dump properly, but gives you a slightly incorrect URL.

Outputs: http://crawl.homedns.org/morgue/itsakobolditsakobold.txt

Should be: http://crawl.homedns.org/morgue/itsakobold/itsakobold.txt

**Comment by jeremygurr** [comment]
fixed.

**Comment by yrmvgh** [comment]
Seems to still be doing it:
http://i.imgur.com/vYLQFrv.png
