### ISSUE TITLE
Issue management

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#205]
Feel free to create issues like you've been, it is working well. Don't close an issue unless you created it and are satisfied that it has been resolved. I'm leaving the ones open that are open because I'm either waiting for more input or am going to make a change to fix/implement it and it serves as a reminder for me. 

If you create an issue for a bug, and you notice that it has been fixed, then go ahead and close it. I will sometimes leave those open to be sure that other's have verified it is working. 

FYI: for bug fixes I will sweep them for easy ones, take care of those, and then deal with the oldest hard one. Little by little they will disappear...

For example, if you have an idea, and it is discussed but not rejected, leave it open, because I probably intend to implement it. But if it is closed, I will forget about it and it probably won't happen.

Sometimes I will close an issue discussing an idea because it seems like the discussion is complete and I decided against implementing it. But if I don't close it, I'm either still considering it, or I want to implement it eventually, and I need it on the issue list until I do. 

Sometimes I will reject an idea that I _would_ like to implement, but it is too hard. Of course I would accept pull requests for these if someone else wanted to do the work. 

For many ideas I don't want to implement, I would still accept a pull request for if someone else implemented it. If I didn't think it fit with my objectives here, I would likely _still_ accept a pull request if it was optionized and it defaulted to off.

**Comment by Sandman25DCSS** [comment]
Probably you can use labels to differentiate open issues (not sure if custom labels are supported).

**Comment by jeremygurr** [comment]
good idea.

**Comment by yrmvgh** [comment]
"Discussion" or "chat" tag?

Also, how do I make a pull request that uses several files? For instance there's a category called "good_weapons" which is referenced by fighter and gladiator.

If I create a category called "ascetic_weapons", and then have Monk refer to that category, all of those changes would (if accepted) need to happen at the same time - done one at a time, they'll break. Ho

**Comment by yrmvgh** [comment]
Also, minor announcement: we have an IRC channel on Freenode. If you _are_ familiar with IRC, just go to **##**circusfork on Freenode. If you're not, you can use the horrible sad ugly thing called webchat, here: http://webchat.freenode.net/?channels=%23%23circusfork

**Comment by jeremygurr** [comment]
I think I'm on it, but I never see anyone else. Maybe I'm on the wrong server.

**Comment by jeremygurr** [comment]
what github does when you try and edit a file is it actually goes to a fork of the repo on your own github account, makes a branch, makes the changes there, then offers to merge the branch into the ca fork here. So if you want to do a more complex change that spans multiple files, just go to the dcss:ca repo in your own github account, create a branch there, make your changes, then submit a pull request from there. 

I can help if you get stuck on any step. It sounds complicated but it's not too bad once you get into the swing of it.

**Comment by yrmvgh** [comment]
You are definitely on the wrong server, because there are 3 humans and a server bot in the room :stuck_out_tongue:

**Comment by jeremygurr** [comment]
hmm, I haven't done any serious irc chatting for close to 2 decades. It looks like I was just trying #circusfork instead of ##circusfork. I now seem to be in the right spot because I can see the message talking about github.com. But I still don't see anyone else in the list on the side? Maybe I'm missing something still.

**Comment by jeremygurr** [comment]
Oh it's working now... finally figured it out.
