### ISSUE TITLE
Start fighters with a buckler?

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#207]
Players who know what they're doing unequip their shield on a fighter start due to the sizable shield penalty that they need to work off with further training.

Anyone who plays circusfork probably knows this, so I'm not too worried about it being a "newbie trap", but it might be a nice convenience for non-large-non-Fo characters to start with a buckler that you can just leave equipped and not worry about.

I'll write the code and pull request myself as a learning exercise, but I want to gather everyone's thoughts.

Also, shield-using characters in general could use some additional role options. I'm thinking about putting a buckler in the skald and warper starting inventories for starters, but why not just toss one into the inventory of every warrior and warrior-mage background?

**Comment by Sandman25DCSS** [comment]
You can use fsim to see that shield helps more than hurts. At least during first XLs. It becomes a problem with fast weapon close to min delay only.

**Comment by Sandman25DCSS** [comment]
Regular shield adds 0.1-0.3 turn delay for player but allows to block a monster attack which is like giving 1.0 turn delay to many monsters.

**Comment by yrmvgh** [comment]
Don't really need to block anything's attacks until D:3 imo, you just want things dead. :) But that's a fair numerical assessment, and the fighter's already one of the easier starts so it doesn't need help necessarily.

What about smaller races being given a buckler, since it takes them so much longer to work off the shield penalty? And how do you feel about bucklers on some warrior mages, zealots, or maybe even gladiator? It can take a surprisingly long time to find a shield on the floor.

**Comment by Sandman25DCSS** [comment]
Buckler is often much worse than regular shield, it still can add 0.1 delay but usually blocks almost no attacks (too low SH)

**Comment by Sandman25DCSS** [comment]
You may want to try using a shield vs Adder to see what I mean, it happens before D3 often ;)

I am fine with providing buckler to warrior-mages (though shield penalty for spellcasting will make me remove the buckler immediately). Also I am fine with using buckler for Ko/Ha (I think SpFi already starts with buckler since it cannot use regular shield). Not sure about Gladiator, shield is the most important difference between it and Fighter.

**Comment by Sandman25DCSS** [comment]
Also Gladiator starts with better weapon than Fighter does as far as I remember.

**Comment by yrmvgh** [comment]
> Buckler is often much worse than regular shield

For me, It's not that bucklers are amazing, it's that you can throw them in your offhand slot almost "for free" if you're wielding a 1 hander because a better 2 hander hasn't dropped, or you don't have 2 hander option (short blades).

If you're focusing on invo/evo/casting for your damage, you can block 1 in 20 (or so) of all incoming attacks with no meaningful skill investment. That's not bad!

As a stepping stone to bigger shields that literally doesn't get in the way of your other plans, I think you're undervaluing the humble buckler. :wink:

**Comment by Sandman25DCSS** [comment]
Don't get me wrong, I had characters who wore buckler all game, who used 2 handed weapon with shields 5, who used 1 handed weapon without buckler. It's all about XP, I won't train Shields for buckler if spending that XP in some other area gives more benefit.

**Comment by yrmvgh** [comment]
> Also Gladiator starts with better weapon than Fighter does as far as I remember.

Interesting that you bring this up! I recently discovered that they actually have the same weapon selection in-game (the wiki is wrong).
HOWEVER,
fighter is special-cased to ban you from picking quarterstaff,
HOWEVER,
**formicid** fighter is special-cased in that special case to **allow** quarterstaff, since they can wield it with a shield.

You can bet your britches I submitted a pull request to have those special cases removed, so that FoFi^Quarterstaff isn't such a secret, hidden thing. :wink:
