### ISSUE TITLE
Special exception to anti stair dance code for Abyss exits

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#209]
Splitting this off of the Kobold topic.

Involuntary abyss citizens need to be able to escape. Also the Abyss is uniquely difficult to "abuse" in the way most normal stairs are.

Should any other special exceptions exist?

**Comment by Sandman25DCSS** [comment]
Should depend on difficulty mode probably. Hard mode should stay hard ;)

**Comment by jeremygurr** [comment]
Ok then guaranteed escape for abyss stairs unless on hard mode.

**Comment by jeremygurr** [comment]
done
