### ISSUE TITLE
Obliterate Occult Obfuscation

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#216]
![feature requesssssst](http://i.imgur.com/xmtJRgM.png)

(see image above)
I don't know how much extra work this is beyond the stamina bar, but I'm hoping that you might be able to reuse a lot of your other code to do this more easily. :) (more easily than if someone were to try to create a piety bar from scratch, that is)

**Comment by jeremygurr** [comment]
it's pretty easy to add a piety bar. The more significant challenge is interface design. Already there is hp bar, sp bar, mp bar, and for lava orc, a temp bar. That's 4 bars! That being said maybe an extra bar isn't too bad of a thing. I would like a better feel for piety. I don't know.

**Comment by yrmvgh** [comment]
Well, just replacing the silly asterisks with a real numerical value would be more than sufficient, in fact it would be lovely! But no rush, I know you've got a lot ToDo.

**Comment by Sandman25DCSS** [comment]
On a related note, my crawl has a way to display AC/EV/MR values for monsters instead of bar.
https://github.com/Sandman25DCSS/difficulty/commit/b17146a33b3210e8468518c6bdd5720f4a4d0aa6

**Comment by Sandman25DCSS** [comment]
Please ignore turn_for_comes_into_view again, it is irrelevant to display_numbers.

**Comment by yrmvgh** [comment]
Oh, we already had an issue for this, it was just buried (and titled badly, and opens with a picture instead of words). What kind of shitposting is the OP up to?
