### ISSUE TITLE
Add HDA config files to the server so we can "+=include" them in our rcfiles

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#219]
These are pretty great, especially if you're playing a caster who would prefer to "autofight" using a spell instead of a weapon.

https://github.com/mattias/DCSSConfigFile

**Comment by G0rg0** [comment]
Yes, please, these are great.

**Comment by jeremygurr** [comment]
I'm not sure where to put these so that they would be available. In the rc folder with the other scripts I would guess? Anyone know?

**Comment by yrmvgh** [comment]
Yeah, wherever our rcfiles are, these go in there

**Comment by yrmvgh** [comment]
@jeremygurr is it rude to ping you on this :shipit:

**Comment by jeremygurr** [comment]
no that's fine. I need to know which things are more important. So maybe I'll work from the top, doing the items more recently discussed first.

**Comment by Sandman25DCSS** [comment]
I wonder if it's enough to register new players with HDA\* names and put corresponding RC content in their files.

**Comment by jeremygurr** [comment]
Ok I put all of these files in the same folder as your rc files, so tell me if that works or not.
