### ISSUE TITLE
Necromancers should not be able to generate with holy wrath weapons.

### ISSUE THREAD

**Issue by G0rg0** [jeremygurr/dcssca#220]
I ran into Josephine & her wraith pack, and she was wielding a holy wrath dagger.

**Comment by Sandman25DCSS** [comment]
I am not sure about it, player Necromancers can use holy weapon unless they worship Kiku or are undead/lichform.

**Comment by G0rg0** [comment]
Yeah true, I just assumed they were worshipping evil gods as they were necromancers, but that's not necessarily true. Just seems wrong in terms of flavor I guess, but it's not going to happen very often.
