### ISSUE TITLE
Scroll of recharging and wand stacking

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#223]
New mechanic of scroll of recharging and wand stacking don't work together. Even if you find 10 wands of hasting you will limit the wand to 5 charges max after a single recharge.

**Comment by jeremygurr** [comment]
hmm... good point. The stacking should stack their maximum amount too, then they will have the same number of recharges.

**Comment by jeremygurr** [comment]
fixed
