### ISSUE TITLE
Impossible to exit power/care mode

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#226]
Earlier today it was working fine but now I cannot exit power/care mode by pressing e again. I am even able to have both power and care mode at the same time and the only way to end it is to spend all SP.
Also sometimes SP is spent even in normal mode.

**Comment by yrmvgh** [comment]
It uses "c" now to enter normal mode, instead of toggling on and off with e

**Comment by Sandman25DCSS** [comment]
I see, thank you! 

Then the only remaining bug is that Power status line is still displayed after entering Care mode right from Power mode.

**Comment by yrmvgh** [comment]
Yes, there are all the bugs. :grin: :grimacing: 

Tip/note: this makes power/care mode a little more macroable, if you want to macro tab/autofight to automatically put you in powermode (and not toggle it off with every other keypress)

**Comment by jeremygurr** [comment]
yes I saw that. It's not actually on, only one can be on at a time, it's just a display bug.

**Comment by jeremygurr** [comment]
Fixed
