### ISSUE TITLE
No butcher means no hide

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#228]
I cannot try to get ice dragon hide by butchering after killing an ice dragon.

**Comment by jeremygurr** [comment]
yeah my plan there is to make a fixture action command that will handle getting hides from corpses, praying at altars, or draining blood from corpses. Or maybe in the case of hides it would be better to just drop the hide on monster death.

**Comment by jeremygurr** [comment]
Fixed. Now monsters will drop hides as often as butchering them did
