### ISSUE TITLE
Allow all races to wear cloaks?

### ISSUE THREAD

**Issue by G0rg0** [jeremygurr/dcssca#231]
It always seemed silly to me that Octopodes and felids couldn't wear cloaks. 

http://www.lam-mpi.com/upload/4/41/4410fb4f757d4040.jpg
http://www.gargoylestore.com/128.jpg
https://s-media-cache-ak0.pinimg.com/736x/27/b3/51/27b35191d925a0a8be1e238d5dd53719.jpg
https://mysticmedusa.com/wp-content/uploads/Audrey-Baschet.jpg

**Comment by yrmvgh** [comment]
I have definitely put cute little capes on my cats.

If a cloak is too big for a Felid, it's probably too big for a wee little Spriggan too. :wink:

**Comment by jeremygurr** [comment]
Done
