### ISSUE TITLE
Stamina points make game too easy

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#232]
I suggest to make character in Power mode have the same speed as most monsters (10), currently it's too easy to escape from most fights.

**Comment by jeremygurr** [comment]
Hmm... that would definitely make power mode less cool. No one likes the movement penalty mechanism though, huh? I'd rather have an option in between just going back to speed 10 and leaving it like it is. But if I can't figure out a better idea I will need to do what you suggest I think.

**Comment by jeremygurr** [comment]
Would this be better solved by cutting the stamina pool in half? It feels a little big to me right now, but I'm not sure how it plays late game yet. High level magic may burn through it fairly quickly.

**Comment by Sandman25DCSS** [comment]
Probably you can make stamina decrease by 1 every turn (not action, 10 auts), it will allow you to easily control effect by setting stamina max to desired value.

**Comment by jeremygurr** [comment]
I cut stamina regen rate in half and cut the stamina pool from 100 down to 50, so you can have a quick burst of speed to get out of a situation, but if you run into any trouble along the way, you will likely run out of stamina before you escape. We could always add a little movement penalty back (maybe 1.3 instead of the 2.0 original), that definitely makes extended escapes quite a bit more difficult.

**Comment by Sandman25DCSS** [comment]
Probably the 1.3 penalty should be applied to Power mode only to avoid penalizing approaching monsters near corners/doors. I mean when player switches to Power mode next movement should have the penalty (even if previous action was a movement too).

**Comment by jeremygurr** [comment]
Oh I like that. A good compromise, and makes sense flavor-wise too. If you are running like mad, you are going to have a bigger movement penalty if you have to stop or make major direction changes. I think it should be a larger penalty though in that case. At least 1.5.

**Comment by yrmvgh** [comment]
I still believe in doing things like += 0.5 instead of == 1.5, so the races aren't speedy/slow only during power mode, also swiftness should do something regardless of mode

**Comment by jeremygurr** [comment]
I'm open to making the movement penalty just add 0.5. It needs to be enough to make a player think twice before kiting, but not so high that it makes escape too hard. 

Swiftness and haste should apply regardless of the mode. But they should have an associated stamina cost to better limit them. Swiftness already worked as if it had a stamina cost, so it won't be much different. But I think haste needed a bit more of a limit than it had in vanilla crawl.

**Comment by jeremygurr** [comment]
fully implemented
