### ISSUE TITLE
Stoneskin not working on lava orc

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#235]
I am not sure if this is a display bug or me being clueless, but it **appears** as if my lava orc doesn't have any sort of low-heat AC bonus as advertised.

**Comment by jeremygurr** [comment]
Yeah I can't seem to find code anywhere that boosts their ac. That means we will probably have to make it then. What should it look like? Just a flat +3 ac bonus?

**Comment by yrmvgh** [comment]
"Should" is that tough question again. :stuck_out_tongue_closed_eyes:

According to the wiki, it used to be "Stoneskin: AC bonus of 2+0.2×XL "

Three would be fine, however. Nice and simple, and since lava orcs were considered "hard to balance", simple is good.

For a bit of related feedback/opinion: as the wiki states, the heat bonus encourages hanging back and passing time until your heat bonuses kick in, maybe less tedious play would be encouraged if the "heating up" effect was, say, 25% faster than present speed when an enemy is adjacent, and 25% slower when at range. But then again that further shoehorns the race into a certain playstyle... but on the third hand, is that a bad thing? Who knows?! Not me.

**Comment by yrmvgh** [comment]
Also it's weird that one particular heat level appears to enhance earth magic, but anything below or above that does not.

**Comment by yrmvgh** [comment]
Maybe you can re-use / make your own version of the physical effect from Qazlal's Storm Shield passive.

It makes your AC nice and blue so you know when it's working and when it's not. :smile:

**Comment by jeremygurr** [comment]
Maybe before we go too much further with Lava Orc changes, we should consider if major changes are needed. No doubt they were axed for a reason. It seems like a lot of it centers around the tension mechanic. 

I definitely don't like the idea of encouraging players to delay to build up their heat first. I think that should be changed to only building up heat when doing damage (ranged, melee, or spell), or receiving damage (from any source). A player can control this somewhat by stepping in water, or maybe drinking a potion of water?

**Comment by yrmvgh** [comment]
Ok buddy, how about you give me my 3 armor NOW for the character I'm playing NOW and we'll open up a new issue for the philosophical discussion of lava orc intangibles. :grinning: 

Tho tbh the game's going just fine right now.

**Comment by yrmvgh** [comment]
you know what. it's possible that the lava orc's "low heat stoneskin" is already a pretty good way to encourage you to jump in instead of dicking around. I wouldn't know... cuz I don't have it!

**Comment by yrmvgh** [comment]
((lava orc rage noises))

**Comment by Sandman25DCSS** [comment]
IMHO LO should become slower as temperature increases. Probably LO was removed because it was encouraging running with monsters in LoS to get high temperature.

**Comment by jeremygurr** [comment]
Maybe we can take out the movement speed changes for LO entirely, just leave them at a fixed movement speed. There is already a lot of movement speed complexity going on with stamina.

**Comment by Sandman25DCSS** [comment]
Maybe give them permanent Slow Movement 1 at XL 1?

**Comment by jeremygurr** [comment]
and then they speed up to normal when hot? I like that.

**Comment by Sandman25DCSS** [comment]
Well, I am not sure about speeding up, I don't remember if adjacent monsters take damage when you are moving at highest temperature. Which is what we are trying to fix: no free damage while moving.

**Comment by jeremygurr** [comment]
you think they should always be slow, even when in power mode? I don't see how they would get free damage while moving, since they have to be adjacent to a monster, and that monster gets to pound on them while they are trying to pass by.

**Comment by yrmvgh** [comment]
I tried killing a hydra with aura damage, it did not seem to hit when moving away (think it's move -> deal effects to what's around -> then monster catches up)

**Comment by Sandman25DCSS** [comment]
I see, then LO does not need to be slow at high temp.

**Comment by yrmvgh** [comment]
I think I've got the fixes coded up and Pull Requested.
- Low temp AC bonus is in, winds up 1 point lower than that described on the wiki
- Rather than sometimes having Lava Bonus and other times having Fire Bonus, they simply have lava bonus whenever warm.
- No speed boost at high temp anymore, but they do have a small speed penalty at low temp.

More involved and philosophical changes (like being only partially Tension-based, or not Tension-based at all) are still likely in the future.
