### ISSUE TITLE
remove ammo?

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#242]
What if ammo were removed from the game? Ranged combat would be far less tedious, and more viable even in early game. I think it's a little silly that when I pick a ranged character, I only use melee for a while until I collect enough ammo to feel like it's worth it. It may need to come with a damage nerf to ranged combat, or some other kind of limitation. But I think it's worth considering. 

Branding would go with the launcher. You would have poison blowguns, sleep blowguns, curare blowguns. Yes, curare blowguns would need to be limited somehow. Maybe they would have a very slow firing rate. Or maybe using a blowgun activates the breath status, so you have to wait a few turns before using it again.

**Comment by Sandman25DCSS** [comment]
I am not sure if you are aware but crawl removed ammo brands a couple of days ago. Maybe it is enough, I don't know.

**Comment by jeremygurr** [comment]
cool. What do you think about removing ammo then?

**Comment by yrmvgh** [comment]
The way throwing/slings works is great imo - an infinite supply of crapammo, and some quality ammo that you bring out of the cupboard when you have a nice guest. (whether due to coding it as "infinite" or the current scads of crapammo)

The "problem" to me is that arrow/bolt crapammo is not infinite enough and does maybe 2 too much base damage. Well, that and the double brand thing. Double brands should not be!

**Comment by G0rg0** [comment]
I say go for it, remove ammo and adjust damage if needed. Scrounging for ammo as a ranged char is a pain in the ass unless you worship trog/oka. 

On that note, those gods gifs would need to be adjusted.

**Comment by Sandman25DCSS** [comment]
I am not sure what I think about removing ammo. I was one of few players who enjoyed choosing ammo of freezing to shoot at Fire Dragon and ammo of flaming to shoot at Ice Dragon. I still hated to pick up ammo after shooting of course.

**Comment by G0rg0** [comment]
How about adding some scrolls/spells that give a temporary brand your launcher to make up for the loss of branded ammo?

**Comment by jeremygurr** [comment]
I thought of another approach to this problem, that would solve several issues and be super simple to implement at the same time. 

Basically all branded ammo remains in the game, but standard ammo is removed. So if you have freezing arrows quivered, firing your bow launches the branded arrow. When they run out, your bow just keeps firing normal arrows, never to run out. Branded ammo mulches 100%. But you are never out of ammo for any launcher. Even throwing without anything quivered would just throw a rock, which just immediately mulches. But players could still pick up rocks and use them for sandblast. 

Blowguns of course would shoot poison needles, unless a different kind of needle is quivered.

Branded ammo spawn rate can be boosted to compensate for the 100% mulching. 

Branded ammo overrides launcher brand. Once ammo runes out, or nothing is quivered, the launcher brand applies again.

God ammo gifts retain their value.

**Comment by jeremygurr** [comment]
unbranded thrown items should never run out (just as if they had a launcher). A single large rock should remain in an inventory no matter how many times it is thrown. Now this makes large rocks way too powerful, so I suggest we compensate by increasing throw delay of large rocks. Small rocks are probably fine as is. Sandblast would need to change a bit, since rocks are no longer a consumable resource. 

Or we could go the other direction. Like branded arrows, each launch mulches the large rock. So maybe more large rocks spawn than before, but once thrown they are gone. In that case, they could be made even stronger than they are now, since you don't get a second chance with them. This sounds better.

**Comment by yrmvgh** [comment]
large rocks are weird.

_ammo_ is weird, it's both a weapon and a consumable.

It should pick one and stick to that.

Some ranged weapons could be consumable-style, some could be weapon-style. l think large rocks make an excellent candidate for consumable style and (INCOMING CONTROVERSY) should not be gifted by any deity. (this opens up god choice and makes the # of rocks a player has access to more predictable)

Tomahawks under this model would be infinite, and maybe javelins too.

Bows and slings should for sure have infinite ammo. Xbows could go either way, in D&D they're a classic "backup weapon" when your main shtick is ineffective or exhausted.

**Comment by yrmvgh** [comment]
also as a reminder, this is theoretically the plan in crawl 0.19:

> ranged reform[1/1]: 1) give launchers their own equipment slot; 2) ammo always mulches; 3) keep skills the same (at least for now); 4) goldify ammo. Optional: overhaul throwing & blowguns & ammo brands; condense skills; maybe remove slings for ammo consistency in condensed skills.

**Comment by jeremygurr** [comment]
Did vanilla crawl really move ammo brands? Maybe I'm missing something but I'm still seeing it in the code, and I just merged from trunk a few days ago.

**Comment by yrmvgh** [comment]
I did not see branded ammo when I popped over there to play some tourney the other day. But I was playing VM and Fi

**Comment by yrmvgh** [comment]
Hm. Changelog:

https://github.com/crawl/crawl/blob/stone_soup-0.18/crawl-ref/docs/changelog.txt#L3891

Maybe it was out, but went back in.

**Comment by jeremygurr** [comment]
oh they removed brands from just some ammo. That makes sense. I think I want to do the reverse. I want to bring arrow brands back.

**Comment by jeremygurr** [comment]
done
