### ISSUE TITLE
summoning should reduce max magic instead of continually draining it

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#257]

**Comment by Sandman25DCSS** [comment]
I'd rather return standard crawl summoning. Easy mode might have summon cap removed so player might use any number of Lightning Spires/Hydrae/whatever.

**Comment by Sandman25DCSS** [comment]
I don't see why summoning should reduce max MP. If I choose to respect standard crawl summon cap (1 hydra/canine/lightning, 3 ice beasts etc.), why should I have less MP?

**Comment by Sandman25DCSS** [comment]
Probably you may want to reduce max MP for violating summon cap. I mean player still can have 2 hydra but it will make max MP decrease (and probably max MP can be fixed with EXP only so you cannot use 3 hydrae to kill something and then get all your max MP back after unsummoning hydrae)

**Comment by jeremygurr** [comment]
the summoning cap doesn't make any sense though. Why would a player be able to summon 3 ice beasts but only one canine familiar? It creates a complexity for all players that doesn't add anything to the game. Each player must know how many of each summon can be made. When playing summoners I often pulled out all of the imps I could make, the 1 canine familiar, the 3 ice beasts, sometimes even my small mammals, all at the same time, but I always had to remember how many of each to do, or I wasted mana. 

This is much worse than the players that needed to cast their stoneskin, and then their infusion, and then their ice shield, before each battle. And that tediousness is being actively removed from vanilla crawl. At least with the stoneskin/shield preparation you don't require special knowledge of how many times you need to cast each one for optimal play.

This also forces an artificially narrow gameplay for summoners, reducing interesting options.

What is the point of this tediousness and reduction of options? This is one of the most unnecessary crawl tediums that exist in vanilla crawl if you ask me, and one of the rare instances of straight up poor game crafting in crawl. I can understand a total summon cap across all summons, or any other limiting mechanism. But one that requires the player to have special knowledge that is arbitrarily different for each spell? Why?

I'm open to any mechanism that provides a non-tedious limit to summons that still preserves a high degree of options for the summoner. MP cap reduction is the simplest I've come across so far, easy to understand, meaningful to apply. If a player wants to have more mp for other things, they should maintain a smaller set of summons or find a way to increase their magic pool (which isn't that hard). For the players who want to spam a large number of summons, they can focus all their efforts into maximizing their magic pool and summoning skill. A very different playstyle made possible by removing the per spell summon cap.

**Comment by jeremygurr** [comment]
But if the MP cap reduction really bothers you, we could go for a SP cap reduction instead. Both would impact some playstyle, and force different decisions to be made.

**Comment by Sandman25DCSS** [comment]
There are several reasons for summon cap. 
1) Different summons have different duration. 
http://crawl.chaosforge.org/Summon#Summoning_Limits
Canine familiar at max spell power has max duration so as Summoner I always had a canine active (yes, even during autoexplore, I changed my settings to stop autoexplore when canine was about to expire). Without the cap players like me would travel with multiple canines. In Lair as MuSu of Sif Muna I was traveling with 6-7 Ice Beasts, I was almost surrounded with them all the time.
2) Summoning nerf. Before summon cap existed player could master a single powerful summoning spell and crowd the whole map with those monsters. Now summoner needs to a) train multiple schools b) use weaker summons too
3) Tactics. Lightning spire, Guardian Golem, Forest, Mana Vipers, all of them require special tactics to be most efficient. It results in more fun and hard game IMHO. Without summon cap you could avoid smart tactics and just play brute force style summoning your strongest monsters all the time.

**Comment by Sandman25DCSS** [comment]
Personally I am not bothered by any MP/SP caps, I just refuse to learn any summoning spells, even butterflies. It's my form of protest ;)

**Comment by Sandman25DCSS** [comment]
From wiki:

> Prior to 0.13, Summonings spells had no limit on how many monsters you could summon at a time, barring MP restrictions. This led to players summoning hordes of monsters at all times, rendering them nearly untouchable by most monsters and leading to extremely dull optimal gameplay

**Comment by jeremygurr** [comment]
Different summons having different durations is another spoilery thing that I'm trying to get away from. I've played for a long time and used the wiki extensively, and even then I didn't know that! 

The ability for a summoner to just fill the room with summons is already prevented with the existing mechanic, so that's not an issue here. 

Forcing the summoner to diversify and learn special tactics _is_ valuable. I'm not sure that's really being lost here, since I've always been motivated to study the strengths and weaknesses of each summon so I can best apply them to a situation. Just focussing on one powerful summon isn't optimal or fun play, and I don't see there being a lot of motivation for players to do it. 

The temptation to brute force summons instead of using tactics could be there to a degree, but again I don't think it's optimal, and I think the game already will adequately punish summoners that don't fully unlock their diverse summoning options. Yes it is more likely to be a problem than if there was a summoning cap per spell, but I don't think that is anywhere near enough to counter balance the choice loss of the summon caps. 

I think the mana locking mechanism would quite solidly prevent the brute force approach. Say a player casts a level 5 summon. Their max mp goes down from 30 to 25. Then they fire off 3 more. Their mp is at 10/10. Unless they are a melee fighter, at this point they are very limited in what they can do against the monsters. Maybe use some wands. Say 2 of their summons die. Now they are at 10/20 magic. So they cast two more. Now they are at 0/10 magic. Maybe 2/10 magic with a little big of regen that has gone on. Without a magic potion, they probably won't be able to cast another level 5 summon for this battle. So maybe they bring out a couple of rats to distract the monsters, or a bunch of butterflies. I think there is plenty of limitation going on here that gives the player good reason to make the effort to diversify and maximize the effectiveness of their summons. Maybe a lightning spire, a guardian golem, and a few imps would do a better job, leaving the player with enough mp to recast a few of them should they die.

**Comment by Sandman25DCSS** [comment]
I guess you hate Sif Muna :(

**Comment by Sandman25DCSS** [comment]
By the way how Dragon Call will work?

**Comment by jeremygurr** [comment]
I'm not sure what you mean by hating sif muna. On a related note, what did you think about the recent changes I made to sif? I'm excited to try them if I can keep a caster alive long enough to be able to use them. 

Dragon call currently works by draining more magic the more dragons that are summoned. But with the locking mechanic, it would probably make more sense to just lock a flat amount, probably just the 9 points for the spell.

**Comment by Sandman25DCSS** [comment]
I missed your changes to Sif Muna. Main point of Sif Muna is to give MP which becomes useless when you limit summons by max MP.

**Comment by Sandman25DCSS** [comment]
Oh, you mean gifting books earlier? Yes, sounds good, probably it will happen in standard crawl too

**Comment by jeremygurr** [comment]
I don't think sif is useless for a summoner. If they over summon, and only end up with 5/5 mp, and a few summons die that they need to restore quickly, they will need to desparately channel to get those mp back and then resummon. With a more skilled summoner, they will keep 15 mp or so in reserve, and not over summon, so that when a few die, they can immediately resummon, and then while those summons are dealing with the bad guys, the summoner can channel to prepare should the summon die again. No different than before, except for the new decision / balancing act the player has to do to make sure they aren't leaving themselves with too little mp. If anything, sif is needed more for summoners with this change than before.

**Comment by Sandman25DCSS** [comment]
Standard Sif Muna characters can hide behind summons and channel mana _in advance_. New Sif Muna characters can create N identical summons which will expire at about the same time and character will have like 5/50 MP instead of standard 30/50 if it was able to channel all the time.

**Comment by G0rg0** [comment]
Best way to see if it's problematic is to give it a try. I really like (at least I think I do) this method over the existing one but if it turns out badly it can be changed.

**Comment by eyestalker** [comment]
I don't have any opinions on how summoning should be done in your branch, I just want to say that summoning caps in regular Crawl make a lot of sense to me. There's a difference in positioning and application in how a spell that gives you one strong summon differs from a spell that gives you multiple weaker ones. I use both Spire and Ice Beasts in regular Crawl, both Summon Imps and Canine Familiar. There was no reason to use Ice Beasts in CA when I played it - I can surround myself with spires and they will tank hits and they will waste no time moving - they will demolish everything with their ranged attack! Hell, why would I learn most of level 5 summonings when I have those? Similarly, there's difference between having a level 7 spell that creates predictable, strong but swiftly expiring allies (Summon Hydra, which is often described as a summoning equivalent to orb Orb of destruction) and a spell that creates allies that last between fights (Summon Greater Demon). It's not just some random mechanic that does nothing but add complexity.

Edit: also, spell descriptions will often hint you if a summoning spell has an unusually short duration. For example, here's Summon Hydra description:
"Summons a many-headed hydra to fight alongside the caster for a short time!"
Though I never had trouble noticing that it expires really fast, or that a tier two demon from SGD can stick for 3-4 average-sized fights (similarly for a Canine Familiar).

**Comment by jeremygurr** [comment]
I understand that there are valuable variations to how the summoning spells work in vanilla. And I don't want to lose the strategic motivation that is there if possible. 

If one particular summon is too powerful, and would overshadow the rest, then the limiting factor needs to be increased, regardless of what that limiting factor is. In the case of the proposed change here, that would be solved by increasing the amount of magic that is "frozen" by maintaining a lightning spire. If it takes half of your magic to hold a lightning spire in existence, you won't be able to just surround yourself with them, and will instead combine it with ice beasts just like before. But unlike before you also have the option to beef up your magic pool size and pull out 3 lightning spires, if that better suits your play style or a particular situation. 

vanilla crawl's summoning mechanism takes two decisions away from the player: how many of a given summoned creature they should spawn, and how long to spawn them for. And those decisions are quite different for each spell (greatly increasing the learning required for mastering summoning). There's definitely an advantage and disadvantage to each way. In most cases I find the game to be more fun if I have more decisions I can make. But we'll find out soon from hands on experience how this change will impact actually playing a summoner.

**Comment by jeremygurr** [comment]
Done.
