### ISSUE TITLE
Berserking with Exh status

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#261]
It's possible to start berserking when already having Exh status.

**Comment by Sandman25DCSS** [comment]
It means I can berserk non-stop.

> You feel a strong urge to attack something.
> You are no longer berserk.
> You are exhausted.
> You feel yourself slow down.
> Huge Dmg: -34%(-11hp) hp: 70%(23hp)
> A red film seems to cover your vision as you go berserk!
> You feel yourself moving faster! You feel mighty!

**Comment by jeremygurr** [comment]
fixed.
