### ISSUE TITLE
Tiles are wrong in v1.3.2

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#266]
Hobgoblins have tiles of gnolls, for example.

**Comment by yrmvgh** [comment]
seems to do that every time a new version is made. It's like the icons can't get it right until the second pass. Refresh your browser when you are on the game screen. The browser is caching the tiles and it shouldn't be - when there is a version changes and the tile positions change, then the cached version no longer matches.

Might need to do shift f5 or ctrl f5 depending on your OS/browser to force a cache refresh

**Comment by jeremygurr** [comment]
it's your browser that's actually caching it. Refresh your browser on the game page and it should be fine.

Oh hehe, I'm repeating yrmvgh. How do you say that anyway? yyy eerr mmuvv ghhhuh?

**Comment by Sandman25DCSS** [comment]
Thank you both! ;)

**Comment by yrmvgh** [comment]
yerm v' g' , or if you don't like glottal stops, yerm vuh guh
