### ISSUE TITLE
save game issues

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#268]
Sorry guys, I'm not sure why I've been plagued by so many of these lately. I know it sucks to lose your save game. So I'm going to do a harder change that will take some time, but I'm pretty sure it will make these problems go away completely, as it will make save game breaks mostly obsolete, and even if there was a break, the save game would be easily manually repairable. 

It will get better... thanks for being patient.

**Comment by Sandman25DCSS** [comment]
I started the game as 1.3.1 and trying to load it after a small break results in crash "ERROR in 'tags.cc' at line 3436: save corrupted: canary gone
Version: Dungeon Crawl Stone Soup: Circus Animals v1.3.0-199-g7b8d251" so probably it does not store version number properly.

http://crawl.homedns.org/morgue/Sandman25/crash-Sandman25-20160420-222710.txt

**Comment by jeremygurr** [comment]
Is your game currently playable, or did this just happen and it no longer works?

**Comment by Sandman25DCSS** [comment]
Just happened, no longer works.

**Comment by jeremygurr** [comment]
Hmm, that means this bug existed before the last release. That gives me a valuable clue.

**Comment by jeremygurr** [comment]
I have a theory. Sandman, try a quick experiment for me: set the level 27 cap off (level_27_cap=false), and try to load your game. Tell me what happens.

**Comment by jeremygurr** [comment]
Ok that was the issue. You can put the cap back on now, I deployed a fix for v1.3.1. I will deploy v1.3.2 later and that will work with new characters as intended. That's a big relief to know that it wasn't the new version breaking things. This bug has been around for a while (since the level 27 cap option was made), so it's no wonder it has tormented us so much.

**Comment by yrmvgh** [comment]
Yep, uncapping worked for me!

**Comment by Sandman25DCSS** [comment]
It helped me too, thank you!
