### ISSUE TITLE
Wands are unloading themselves

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#274]
Most of the following wands have never been fired by me. It's mostly affecting the "largest" wands, but not strictly. And it's not affecting all unfired wands, because I haven't used tele or para yet.

![](http://i.imgur.com/rZzi9jx.png)

http://crawl.homedns.org/morgue/RumpyFlump/RumpyFlump.txt

**Comment by Sandman25DCSS** [comment]
It happens in my games too. I tried paying attention to see when it happens but failed, adding a new wand did not empty the wand.

**Comment by yrmvgh** [comment]
I always notice it after a load from save. Doesn't necessarily mean that's when it happens, but that's when I notice it. Gonna just keep the window open until I finish this character, out of paranoia, cuz evo's a big deal for a DD!

**Comment by jeremygurr** [comment]
fixed.
