### ISSUE TITLE
HP scaling

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#277]
I entered Zot 1 with 4 runes at nightmare and it looks like monsters have more than 160% HP. According to wiki draconian can have 48-80 HP but my draconian had about 171 HP

> You reach to attack! You hit the yellow draconian (1).
>  The yellow draconian is lightly wounded.
> _The yellow draconian misses you.
>  You reach to attack! You impale the yellow draconian (35)!!
> _The yellow draconian is moderately wounded.
>  You reach to attack! You puncture the yellow draconian (11)!
>  The yellow draconian is moderately wounded.
> _The yellow draconian hits you (5) from afar with a glaive of protection.
>  Damage: -4%(-7hp)   hp: 86%(125hp)
>  You reach to attack! You impale the yellow draconian (21)!!
> _The yellow draconian is heavily wounded.
>  You reach to attack!
>  You skewer the yellow draconian like a kebab (49)!!!
>  The yellow draconian is severely wounded.
> _The yellow draconian hits you but does no damage.
>  You reach to attack!
>  You catch the helpless yellow draconian completely off-guard!
>  You impale the yellow draconian (25)!!
> _The yellow draconian is almost dead.
>  You reach to attack! You impale the yellow draconian (28)!!
>  You kill the yellow draconian!

**Comment by Sandman25DCSS** [comment]
Oh, I think 1.15^runes is too cruel. That's 813%HP with 15 runes.
Though I still don't understand how 1.15^4 resulted in 200+%HP, it should be just 174%

**Comment by jeremygurr** [comment]
well at 80 hp 1.15^4 gives 139 hp. Maybe the damage numbers are before ac is fully applied or something. I'll have to look into that. Unfortunately the way crawl spreads out these damage calculations all over the place (instead of just doing it in one place), makes it rather difficult to hunt each case down.

So what about 2/4/6 or even 1/2/3 then? 1.06^15 vies 2.39x original.

**Comment by Sandman25DCSS** [comment]
I agree, 2/4/6 seems more reasonable. Difference between 3 and 15 runes would be 1.02^12=1.26 and 1.06^12=2.01

**Comment by Sandman25DCSS** [comment]
Please let me know when it is deployed. It is very hard as is so I am waiting for the fix before entering Zot 2 ;)

**Comment by jeremygurr** [comment]
Hmm I thought I already deployed it. You should notice a difference I think. 

-- Jeremy

**Comment by Sandman25DCSS** [comment]
Ok, thank you!

**Comment by Sandman25DCSS** [comment]
I am not sure it is deployed, I have just entered a new level (so monsters were generated with new rules) and killed a draconian with 196 damage in 6 attacks. Draconian has AC 10 so even if the displayed damage is before AC-reduction, it means at least 136 damage which is higher than 1.06^4*80=100

**Comment by Sandman25DCSS** [comment]
`You impale the green draconian (21)!!
There is a sudden explosion of sparks causing 9 damage!
The green draconian is lightly wounded.
You impale the green draconian (29)!!
There is a sudden explosion of sparks causing 18 damage!
The green draconian is heavily wounded.
The green draconian closely misses you. You block the green draconian's attack.
You impale the green draconian (28)!!
There is a sudden explosion of sparks causing 15 damage!
The green draconian is severely wounded.
You impale the green draconian (20)!!
There is a sudden explosion of sparks causing 8 damage!
The green draconian is almost dead.
You block the green draconian's attack.
The green draconian tail-slaps you but does no damage.
You impale the green draconian (26)!!
The green draconian is almost dead.
You impale the green draconian (24)!!
You kill the green draconian!
`

**Comment by jeremygurr** [comment]
Oh that one must be on this new branch I'm working on. Hmm... I'll apply it to the old one too.

**Comment by Sandman25DCSS** [comment]
Also vampiric weapon still sets SP to 0 so it's not deployed I guess.

**Comment by jeremygurr** [comment]
Both of those have been deployed to 1.3.3. I'm guessing you are on 1.3.2 still. I think you'll get the changes once you start a new character. But don't start a new one just yet, I'm just about to deploy 1.3.4.

**Comment by jeremygurr** [comment]
Oh no, looking at the lobby, you are actually on 1.3.1. There's quite a few changes you haven't gotten yet :)

**Comment by jeremygurr** [comment]
Well you've got a serious challenge ahead of you to beat the game. X-)

**Comment by Sandman25DCSS** [comment]
Oh, I see, players now always continue using version which they started character with, right? So I will have to kill 174% HP monsters ;)
