### ISSUE TITLE
Unresumable Save

### ISSUE THREAD

**Issue by SleepySteel** [jeremygurr/dcssca#279]
I refreshed my page on 1.3.2 in an attempt to change some of the sprites that were bugged, to the suggestion of a friend. My game instead became an unresumable bugged save that I can not delete, preventing me from playing on my account and forcing me to use an alt for the time. Is there a way I can terminate my save? It of course doesn't work if I try to enter the game and use the quit command.

**Comment by jeremygurr** [comment]
I'll delete it. Sorry saves got very broken in that version. I believe the issue is resolved though in the current.
