### ISSUE TITLE
A couple of things about corpses.

### ISSUE THREAD

**Issue by SleepySteel** [jeremygurr/dcssca#280]
1- Ghouls feel a bit weak now, and trolls feel outrageously powerful. That might not be your prime concern, but I think they could use a little something. That's just me, though.
2- I would like to see corpse sacrificing to certain gods make a reappearance.
3- I miss mutating chunks.

**Comment by jeremygurr** [comment]
Why are ghouls feeling weak? Have you played them to level 12 or so, after they've had powered by death for a few levels? They are crazy strong. Not only that but occasionally they heal from kills, having a mini makleb effect built in. 

Why are trolls feeling too powerful? Is it berserking you are specifically referring to, or some other aspect of trolls? The only major thing I changed there was giving them occasional stamina boosts on kill, which helps make up for the fact that they burn through stamina much faster than normal species do. This is more of a nerf overall compared with vanilla crawl. 

Corpse sacrifice is definitely viable here, as long as we it is done in a no-hassle way. Maybe when a player is following a god that requires sacrifice, some corpses are automatically sacrificed at death, providing the piety bonus. I guess that is no different though than just giving piety for monster death, except that you end up with less corpses. I'm not sure I'm seeing a meaningful value added for corpse sacrifice here. What are you seeing?

There is already a propsal that's not yet implemented to replace mutating chunks. There will be mini-mutation potions automatically dropped by creatures that would leave mut corpses, that would give the same effect.

**Comment by yrmvgh** [comment]
> trolls feel outrageously powerful

Do keep in mind that races aren't supposed to be balanced. They're a minor form of "difficulty level" and it's more important that they're unique than fair.

**Comment by yrmvgh** [comment]
> I guess that is no different though than just giving piety for monster death, except that you end up with less corpses. I'm not sure I'm seeing a meaningful value added for corpse sacrifice here. What are you seeing?

Perhaps there's something thematically cool about "makleb, I offer this kill to you!" that's lost in the more financial-transaction-feeling of "makleb accepts your kill, write it off your taxes".

Maybe it can be kept from being tedious by only working on named uniques that have more HD than you do. Or prayer affecting all corpses in LOS, in the other direction.

I dunno, I don't see much gameplay value in corpse sacrifice, and I wouldn't implement it in a fork I was running. But I can see how it has a different, cooler feel. THere may be a solution out there.

**Comment by SleepySteel** [comment]
I guess it's a fair proposition to say that not all races are balanced around each other- I was just a bit shocked that trolls were even more powerful given that they have stronger shaggy fur and no hunger. It felt like they were stronger WITHOUT berserk, though, is the thing- berserk wears out their baby ass stamina so quickly. Ghouls I guess didn't feel strictly weak, just stronger in different areas, and I didn't think that thing through as much. As for corpse saccing, it doesn't entirely serve much a gameplay purpose other than for flavor, but I miss walking around as an abyssal knight and tossing corpses into the pit. Also, another thought occured to me- you made Gozag only turn 50% of corpses into gold so chunk users could use him feasibly, but then made chunks go away. I suggest you let Gozag turn all corpses into gold again, unless you want necromancers of 
Gozag or something to be viable.

**Comment by yrmvgh** [comment]
Gozag 50% is still important for races that rely on enchanted Dragon Hides as their only viable armor type, imo

**Comment by jeremygurr** [comment]
Yeah I like the increased options for gozag that the 50% corpses provide. If he ends up being truly overpowered, then we will be able to tell by everyone choosing him to play, and we can adjust things. But so far that doesn't feel like the case.
