### ISSUE TITLE
Summoning

### ISSUE THREAD

**Issue by SleepySteel** [jeremygurr/dcssca#281]
I love permanent followers, but one thing: autoexploring cancels summons immediately. This makes it very annoying to keep my hoard of 20 spammals and 1 guardian golem up at all times.

**Comment by jeremygurr** [comment]
I put that in based on the previous way of summoning. I guess with the new way it makes more sense to keep them around. I'll fix that.

**Comment by jeremygurr** [comment]
fixed.
