### ISSUE TITLE
Github.io

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#287]
Is it possible for me &/or other players to put together a github.io "splash page" for visitors and new players? The readme is of an intimidating size. And black text on white background is the most awful thing in the universe.

I have decade-old HTML experience I can use to make simple table-based thing with better colors. Or we can just borrow the code from http://forays.github.io/ ... now that's a nice splash page.

**Comment by Sandman25DCSS** [comment]
+1 for improved landing page. It was great in v. 1.0 when you could see changed species (the most exciting part IMHO) instantly, now I am not even sure if guys to whom I recommend the fork even are patient to read to 1.2

**Comment by jeremygurr** [comment]
that would be awesome. I have it as one of my tasks to do, but there is so much I already am trying to keep up with, help with this would be awesome

**Comment by yrmvgh** [comment]
Where are the buttons for doing this thing. :8ball: Do I have access to the buttons?

**Comment by yrmvgh** [comment]
The species changes are very attention-grabby, yes. That and the 104 slot inventory.

**Comment by jeremygurr** [comment]
Well, the easiest way to do this is for me to throw up a wiki. Then you can set up an account and go to town making it nicer.
