### ISSUE TITLE
Qaz

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#288]
Qaz and Zin both make loud noises and improve your defenses. They both have powerful spells that hit everything in LOS. Similarities end there. Even when you only compare Recite to Disaster Area, qaz's abilities are just not as good as Zin's. Then on top of those worse abilities you generate enough noise that it pulls the whole level every time you take a stair.

It's okay for there to be good gods and bad gods, but qaz currently makes the game a lot more tiresome, and could use some love, as long as he doesn't suddenly become one of the best gods.

> As someone who is currently playing au  draconian of qazlal ... 90% of my run consists of going upstairs downtairs, the other 10% is kiting monsters to the stairs. I guess its all subjective in the end, but worshipping a god that drags me into a narrow degenerative playstyle is not fun imo.

Possibilities:
- Higher SH bonus, or Reflect intrinsic so you don't have to find an amulet
- some kind of synergy with elemental evocables like disc of storms
- some kind of synergy with elemental spell schools.
  -   maybe qaz's storm is so intense that if you cast Rmsl, it's special-cased to "stack" with the Rmsl granted by Qaz and thus upgrade into Dmsl.
- Change noise in one or more ways
  -   significantly less noise, or no noise at all, when out of combat
  -   [tension](http://crawl.chaosforge.org/Tension)-based noise
  -   noise based on how much damage you dealt this turn (whether with attacks, invo, spells)
  -   Your storm (and its noise) could be toggleable, not always-on. Either it has its own "switch on" ability, or is automatically switched on when you use one of Qaz's other abilities.
- Any reduction to noise level should also reduce the amount of clouds you generate... or should it?

> Yeah, as I was saying to dynast in gammafunk's stream, it's really okay if the game has weird niche gods. There's no expectation of balance (if there was, we would have to nerf Trog way before we thought about buffing Qaz), and there are plenty of reasons to include gods that offer narrow playstyles or challenging conducts.
> 
> The thing is that Qaz should be fun in and of itself, in the way that I think lots of players find Chei fun. Gods are a great way for the game to offer radically different incentives and challenges. Gamma pointed out (and I'm paraphrasing here) that Qaz doesn't really play to Crawl's strengths, and I think dynast hits upon that with the complaints about stairdancing. However, that just brings us to the inevitable conclusion that probably the real issue here is Crawl stairs, and that's a whole other (probably fruitless) discussion.

As much as possible, I'll try to spearhead the coding on Qaz changes - I think I'm getting the hang of this. But first let's get some opinions and thoughts!

**Comment by Sandman25DCSS** [comment]
Those quotes are from tavern which discusses vanilla crawl where stairdancing is possible. I actually won HO of Qazlal in CA fork on hard and I think it does not need changes. It's unique god with unique gameplay.
Also I liked Qazlal in vanilla crawl too (got a 15 rune win as Mf during some tournament where only one attempt was given so you can see the god is not as bad as it looks).

**Comment by yrmvgh** [comment]
Oof, rain on my parade will ya! :stuck_out_tongue: 

Okay, well if we stay away from straight power boosts, what do you think about making him more ele-evocable or ele-spell-school friendly? The thematic fit is perfect, but mechanically, the summons die to your clouds and the spells don't give you a lot of bang for your exp.

Spells are probably actually a lost cause.

**Comment by yrmvgh** [comment]
Oh, and how about noise being not **constant**. Maybe not under the player's full control with a toggle, but at least quieting down until you deal or receive damage.

**Comment by Sandman25DCSS** [comment]
Well, I would prefer "silence please" to be an activated ability, it could cost piety and maybe also remove RMsl or something to avoid making it a no brainer on new levels.
