### ISSUE TITLE
Remove stamina cost for spellcasting while in "normal" mode.

### ISSUE THREAD

**Issue by G0rg0** [jeremygurr/dcssca#292]
I propose no stamina cost on spellcasting while in normal mode, only while in power or careful modes.

Melee chars don't burn stamina while swinging weapons and even when they have no stamina, they can still fight. I think if a spellcaster has MP left, they should still be able to cast. The normal penalties that go with no stamina would still apply of course - they can't use power mode to run away etc.

**Comment by jeremygurr** [comment]
Deployed
