### ISSUE TITLE
Release summoned creature should not affect hostile summons

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#295]
I converted to random god (Ely) with summoned Imps, the imps became hostile instantly but I was still able to unsummon them.

**Comment by Sandman25DCSS** [comment]
I suspect similar issue can happen when summoning hostile demons via Summon (Greater) Demon. Hostile demons are part of vanilla crawl balance.

**Comment by jeremygurr** [comment]
Should be an easy fix. I'll just check for hostility before removing the summon. However, hostile monsters will still lock magic until they are killed :)

**Comment by Sandman25DCSS** [comment]
That's cruel :)

**Comment by jeremygurr** [comment]
fixed
