### ISSUE TITLE
Numerical piety next to the silly little asterisks

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#297]
The asterisks usefully remind us which piety threshold we're at, but they uselessly obscure the actual amount

**Comment by Sandman25DCSS** [comment]
+1
I played with piety displayed as a number in my mod, it was definitely fun. Though it's a little buff to players, knowing that you have 200 piety is useful, especially with gods who don't have piety decay.

**Comment by yrmvgh** [comment]
Would you be willing to bring that over into here with a pull request @Sandman25DCSS ?

**Comment by Sandman25DCSS** [comment]
I no longer have the source, sorry. It was several years ago.
