### ISSUE TITLE
ID mini-game

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#298]
As far as I know all species have "slow ID" mutation and I have a question. How does it work? Does it check a chance to id an item and then picks a random item from inventory? If it is the case, then player is really encouraged to drop everything on the floor and keep just 1 unknown item he is most interested in. Or are those chances independent so the more items I have in inventory, the faster I will Id them?

Also what do you think about removing ID scrolls completely? It could result in some fun situations where player would have to use fragile items,  items with *Contam, weapon with distortion, got some random mutations from quaffing a potion of mutation etc. Or is it too crazy idea? :)

**Comment by yrmvgh** [comment]
> new insight mutation that they start with which, over time, randomly identifies attributes of items in their inventory. This mutation can also randomly be gained by other species as they drink mutation potions, etc. An item with an earlier inventory letter will likely be identified before an item with a later one ('b' will be identified sooner than 'z' in most cases).

Also it is a 67% percent chance of targeting inv 2 , 33% for inv 1... Hope that covers most of it!

**Comment by jeremygurr** [comment]
It first chooses which of the two inventories to check. 1/3 chance of standard inventory, 2/3 chance of consumables. Then it start with the top item on the list (slot "a"), and randomly chooses an aspect (cursed, artifact properties, enchantment, etc) of that item. If that aspect is already identified, then it moves to the next item (slot "b"). If not, it identifies it. So it doesn't always identify the first item first, but it usually does. So assigning items you want identified sooner to an earlier letter will make a huge difference in how fast it will identify. I find most of the time I don't care, but when I get a wand, I usually want it's charge identified soon, so I will assign it to slot "d" or whatever. If there are identified items before it, they will make no difference to the process. 

That is an interesting thought to remove id scrolls entirely. I definitely want tension to be there. ID scrolls should always have some value, even late in the game. Removing the ID scrolls would make Ash and Insight mutations much more valuable. But it's a pretty big limitation. We would need some other kind of mechanism for players to use to identify things.

**Comment by jeremygurr** [comment]
The inherent insight that all species have is half as frequent as the old L1 insight that Dj had. It's fairly slow moving. The L1 insight has been made a little faster to further distinguish it. L2 is much faster, and L3 much faster than that. So the Dj keeps it's distinction.

**Comment by Sandman25DCSS** [comment]
Thank you for details!
