### ISSUE TITLE
Potion of physical mutation

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#299]
I really love mutations, but for actual game success, they're not only bad as far as risk-of-crippling-your-character, but even the "beneficial" mutations can force you to lose valuable inventory slots.

We lightly discussed this on IRC last week but I want to seriously propose splitting "potions of physical mutation" from "potions of magical mutation". The physical pot is the only one that can make you give up an equipment slot with its beneficial or negative mutations. The magicpot would have the lion's share of mutation possibilities, and would thus be somewhat more common. The physpot would primarily appeal to monstrous, odd-shaped, or slot-limited characters, and the magipot would be less unappealing for humanoids than the existing randopot.

Due to a small number of "physical"-type mutations, things which aren't clearly purely-physical or purely-magic would need to be either shunted to the physpots or duplicated and present in both.

**Comment by jeremygurr** [comment]
Ok this problem has been solved by introducing a new mutation classification: DEPENDS, as opposed to BAD or GOOD mutations. All mutations that could cause you to lose an armour slot are marked as DEPENDS, as they are sometimes good, sometimes bad. So bene mut potions will never give a DEPENDS mutation. But when removing good or bad mutations, it won't remove them either.
