### ISSUE TITLE
Crashes when trying to enter a new level

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#30]
I got crashes when trying to enter a new level twice while playing on http://crawl.homedns.org/ server

**Comment by jeremygurr** [comment]
Unfortunately my server only saves one core dump at a time, so I'll need you to hit this one again, then I can capture the core dump and figure out what's going on.

**Comment by Sandman25DCSS** [comment]
I learned a habit of saving before entering a new level and the issue stopped occurring. I will try to play as usual and see if the crash happens again.

**Comment by jeremygurr** [comment]
yeah I will be able to fix it if I can get a core dump.

**Comment by Sandman25DCSS** [comment]
I have just got the crash. Please investigate, I suspended playing to avoid overwriting the file.

**Comment by jeremygurr** [comment]
Okay, I might have fixed it. I think this bug actually comes from the mainstream crawl. I might have taken care of it though. Try and see.

**Comment by jeremygurr** [comment]
Of course for any update, you will need to save / quit the session and start again before you will be running the new code.

**Comment by Sandman25DCSS** [comment]
Ok, thank you.
