### ISSUE TITLE
Remove wizardry bonus from careful mode

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#300]
It's too easy to cast high level spells in careful mode.

**Comment by yrmvgh** [comment]
No way! Just make it smaller, and make it flat instead of a % reduction - that way it benefits the skilled more than the unskilled!

**Comment by jeremygurr** [comment]
ok changed it to a flat 20% reduction, so high level spells will still be out of reach for unskilled characters
