### ISSUE TITLE
serenity mode xp is too high

### ISSUE THREAD

**Issue by alexjurkiewicz** [jeremygurr/dcssca#301]
Sample data from a HuFi game:

```
     0 | D:1      | Reached XP level 1. HP: 23/23 MP: 6/6
    73 | D:1      | Reached XP level 2. HP: 27/29 MP: 7/7
   472 | D:1      | Reached XP level 3. HP: 23/34 MP: 8/8
  1566 | D:2      | Reached XP level 4. HP: 22/40 MP: 9/9
  2465 | D:3      | Reached XP level 5. HP: 46/46 MP: 10/10
  2466 | D:3      | Reached XP level 6. HP: 52/52 MP: 11/11
  2876 | D:4      | Reached skill level 5 in Maces & Flails
  2876 | D:4      | Reached XP level 7. HP: 57/57 MP: 12/12
  2967 | D:4      | Reached XP level 8. HP: 62/63 MP: 13/13
  3557 | D:4      | Reached XP level 9. HP: 67/68 MP: 14/14
  3810 | D:5      | Reached XP level 10. HP: 75/75 MP: 15/15
  4442 | D:5      | Reached skill level 10 in Maces & Flails
  4442 | D:5      | Reached XP level 11. HP: 80/80 MP: 16/16
  4627 | D:6      | Reached XP level 12. HP: 86/86 MP: 17/17
  5174 | D:7      | Reached XP level 13. HP: 91/91 MP: 18/18
  5241 | D:7      | Reached XP level 14. HP: 97/98 MP: 19/19
  5906 | D:8      | Reached skill level 5 in Fighting
  5906 | D:8      | Reached XP level 15. HP: 108/108 MP: 20/20
  6287 | D:8      | Reached * piety under Okawaru
  6330 | D:8      | Reached skill level 8 in Fighting
  6330 | D:8      | Reached XP level 16. HP: 120/122 MP: 21/21
  6994 | D:8      | Reached skill level 10 in Fighting
  6994 | D:8      | Reached XP level 17. HP: 134/134 MP: 22/22
  7430 | D:9      | Reached skill level 11 in Fighting
  7430 | D:9      | Reached skill level 10 in Armour
  7430 | D:9      | Reached XP level 18. HP: 144/144 MP: 23/23
  7996 | D:9      | Reached skill level 13 in Fighting
  7996 | D:9      | Reached XP level 19. HP: 156/156 MP: 24/24
  8233 | D:10     | Reached skill level 5 in Shields
  8233 | D:10     | Reached XP level 20. HP: 163/163 MP: 25/25
  8328 | D:10     | Reached XP level 21. HP: 169/169 MP: 26/26
```

The skill / level growth without using !xp drops is a little low in early game (pre-lair), but the !xp drops on each floor and each unique let you power ahead relatively quickly.

I think XL XP is too high while skill XP is a bit low. !xp potions in this mode could be about 25% of their current power, I suspect. And don't add them to uniques unless the potions are significantly nerfed.

Full log is here: http://dpaste.com/2DH506P

Note the XP/SP graph down near the bottom.

**Comment by jeremygurr** [comment]
The serenity mode is meant to be a milder form of balance, where xp is gained from many sources, but the player isn't pushed to dive as deep as possible without using many xp potions like balance is. So maybe in this case we take away potions entirely, and award xp from floor advancement and from monster kills, and the floor advancement xp is fixed, so there's no advantage is delaying as long as possible, as would be the case for destroyer mode for example.

But this also highlights the fact that potion per xp level gain is too much (probably by 4x). I'll adjust that, which will affect all modes that work this way.

**Comment by alexjurkiewicz** [comment]
Sounds good

**Comment by jeremygurr** [comment]
fixed
