### ISSUE TITLE
Fix spell failure chance

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#303]
I was surprised to see that I had 16% Haste with Str 28, Int 10, Charms 16, Spellcasting 8, Armour 22 in ring mail so I re-created the character in 0.17 local and found that I would have 4% there. Why is it quadrupled in CA fork? Even careful mode brings me to 8% which is still doubled.

**Comment by jeremygurr** [comment]
It's not. It's exactly the same failure %. It is incorrectly reported in vanilla crawl in the spell list screen. It is a bug there. We have reported it to vanilla devs.

**Comment by Sandman25DCSS** [comment]
Oh, I didn't know it. So I guess you are right and that triple miscast of 1% Necromutation didn't have 1/1,000,000 chance
