### ISSUE TITLE
Killing monsters gives no XP in classic mode

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#304]
I resumed playing my game today and despite the game says I am playing 1.3.3 in classic mode, I don't get any skill points for killing monsters.

**Comment by Sandman25DCSS** [comment]
Is it unfixable? It looks like the fork does not want me to try 15-runers, they all "die" to bugs like losing all wand zaps or being unable to learn Statue Form/Necromutation because of limited skill points :(

**Comment by jeremygurr** [comment]
I'll look into this. I'm not sure where this is coming from, but it might have to do with the level 27 cap.

**Comment by Sandman25DCSS** [comment]
I am not sure, I still kept getting skill points after reaching XL 27 the whole day, it stopped working next day only. Are you sure you haven't deployed anything?
It's easy (standard) game if it matters.
http://crawl.homedns.org/morgue/Sandman25/Sandman25.txt
61731 | Forest:5 | Reached XP level 27. HP: 402/402 MP: 55/55
 61745 | Forest:5 | Reached skill level 1 in Air Magic
63073 | Forest:4 | Reached skill level 26 in Axes

**Comment by jeremygurr** [comment]
Fixed.
