### ISSUE TITLE
Ash curses?

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#305]
I am not sure what's the bug here. I cannot find a way to remove curse as Ashenzari worshiper, README does not help either. I tried using curse ability on already cursed item but instead of removing the curse it increases curse from 100 to 200. Does it have any benefit?

**Comment by jeremygurr** [comment]
you can't just use a remove curse scroll? What are you attempting to do? The remove curse scroll should take 100 points from the curse. Oh remove curse isn't working for ash then?

**Comment by Sandman25DCSS** [comment]
Oh, I see, old way to remove curse should work indeed, I haven't tried, not sure what I was thinking :(. How about cursing already cursed item, isn't it a bug?

**Comment by jeremygurr** [comment]
Cursed items are allowed to be cursed further. I'm not sure a player would want to in this context, but we could make ash give more piety for more heavily cursed items, then it would make sense for a player to want. Maybe I'll just not allow the player to do it. Probably too confusing.
