### ISSUE TITLE
Quaffing berserk potion while tired wastes the potion

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#306]
See title, it should not be possible to quaff the potion

**Comment by jeremygurr** [comment]
oh, that is a bug I have on my list. You are supposed to be able to quaff berserk potion while tired because all potions contain their own energy and don't require the player to have SP or whatever. Scrolls or wands on the other hand may behave differently.

**Comment by jeremygurr** [comment]
fixed.
