### ISSUE TITLE
Monster in Dwarven Fortress dropped a potion of porridge

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#309]
It has been removed from vanilla crawl and has error description.

**Comment by jeremygurr** [comment]
Yeah we need to go through and remove potions of porridge (and probable a few other obsolete items). It's fairly easy to do a search for that through the dat/des/branch files if someone would like to take a stab at it so it can be fixed sooner than later.

**Comment by yrmvgh** [comment]
Partially done: porridge in the Dwarf branch has been replaced with Ambrosia. This might lure more people to come check out this mini-branch.

This makes it a nice place to go if you are playing DD and/or ^Pak, which I find pleasingly appropriate.

**Comment by yrmvgh** [comment]
As an attempt for a more universal fix going forward, I also tried making Porridge just do the same thing that ambrosia does. Not sure it'll work.

Right now: porridge throws an error
If this doesn't work: it'll throw a different error
If it works: hey, time saved for everyone!

**Comment by yrmvgh** [comment]
Touched up Forest as well. It didn't have much porridge in it to begin with.
