### ISSUE TITLE
Require multiple "spell fail" checks for a form or summon

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#311]
relative to vanilla Trmt, there's a notable lack of "your spell will fade soon" that you can use to make informed decisions - like recasting it, backing off, etc - what if instead of multiplying the chance to fail by .2, it needed to "fail" in the background 5 times.

Then it could warn you 1 or 2 fails before the final one ... "your (foo) is going to unravel soon!"

Or some combination of reducing the chance + multiple chances ... such as multiply fail chance by .4 and require 2 fails... etc

**Comment by yrmvgh** [comment]
[This](https://github.com/jeremygurr/dcssca/commit/e5602424ebfca4de1522f06f3b079b73db17333a) is causing a lot fewer "surprise untransforms", thank you!

One last beg: can you make the untransform and the final warning use an alarming color in the message log?

**Comment by Sandman25DCSS** [comment]
And now I am not sure why transmutations were changed because it is similar to vanilla crawl which cares about spell failure, spell power and makes forms expire in battle too. The only significant difference is that CA transmutations can expire after one attack unlike vanilla crawl with minimal duration for the spells. Is spamming Tm spells before every fight really worse than spamming Tm spells in fights (if unlucky)?

**Comment by Sandman25DCSS** [comment]
I guess main benefit of new Tm spells is that player does not need to cast Necromutation or whatever during autoexplore but then I am not sure it is a good idea, miscasts and MP management made the game harder (Necromutation at 2-3% could still have red miscast).

**Comment by jeremygurr** [comment]
The point is to take away battle-prep tedium as much as possible. And I think we have been successful in accomplishing that here. For transmutations a player can easily cast, they can effectively maintain them indefinitely. 

You still have a guaranteed minimum number of attacks you can do in a form (5 right now, but that can easily be changed if we feel the need). I could make that number reset if you rest if you want it to be more stable. That would be a significant buff, but probably not game breaking. 

It is true that when you have necromutation at 2% failure rate, you will rarely have to recast it, thus avoiding the miscast effects. But in return you can randomly lose that form in the middle of battle, and may face the miscast effect then, so I think the difficulty isn't that much different. Although in both cases it's a random surprise that almost always comes at a bad time and that the player can't do much to prevent, so I'm not sure it's that great of a thing anyway.

**Comment by jeremygurr** [comment]
I think we should apply this same mechanism to all self-inflicted statuses to greatly reduce tedium for spellcasters before battle. Then we wouldn't need to do things like vanilla crawl does where they remove ice shield because it's too tedious to put up before battle each time.

**Comment by Sandman25DCSS** [comment]
I like your idea of guaranteed attacks and I think it can be reset when player reaches max MP with no monsters in view. Yes, your approach is more fun for me than vanilla crawl, thank you for inventing it ;)

**Comment by yrmvgh** [comment]
Is this closeable now due to other issues on the Trmt topic, or is this useful to keep up?
