### ISSUE TITLE
Issue with accounts/passwords on http://crawl.homedns.org/

### ISSUE THREAD

**Issue by G0rg0** [jeremygurr/dcssca#32]
I have multiple accounts that appear to have issues with the password saving. Normally I would chalk it up to either forgetting or mis-typing but in this case I saved one account in Lastpass and wrote the other password down but I am still getting login failed. The email attached to both accounts is "yenddi at gmail.com" but I do not see a recovery option.

The accounts are: Gorgonzola and Gorgo - I don't know if it makes any difference, but I used empty spaces in the passwords.

**Comment by Sandman25DCSS** [comment]
I had the same issue yesterday using my single account on the server. Login failed every time I tried so I tried to register again using the same username/password/email as before and it let me in. I suspect my account had been removed, that's why I was able to register again with the same username.

**Comment by G0rg0** [comment]
Sandman - yep, it appears the account was gone as I was able to re-register with that name. I'm a bit sad at the loss of my savegame on gorgonzola though. My char was doing very well.

**Comment by Sandman25DCSS** [comment]
Hopefully Jeremy can restore the game file, I hope it was not physically removed, just moved somewhere.

**Comment by G0rg0** [comment]
Well, interesting. It let me register the account again, but the save game was still there.

**Comment by jeremygurr** [comment]
Oops. I had run a part of the python code to delete an account, but python recompiled the code with permissions that the web server couldn't use, so it made part of the login code unavailable to the webserver. It's fixed now. I don't think any save games would have been lost though.

**Comment by jeremygurr** [comment]
Sorry, the documentation for running crawl servers is almost non-existent. There are a lot of assumptions made that people new to hosting it wouldn't know about.

**Comment by G0rg0** [comment]
No apologies needed, thanks for the work you're doing.
