### ISSUE TITLE
when changing floors, summons should follow, no matter where they are in the floor

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#325]
avoiding more tedium

**Comment by Sandman25DCSS** [comment]
making Summoning OP

**Comment by SleepySteel** [comment]
I don't think it would make summoning more overpowered to spare the player a couple of turns when entering a floor- not by a margin significant enough to be the tipping point that decides if they're overpowered in the first place, at least.

**Comment by Sandman25DCSS** [comment]
I am not sure why you think it is a couple of turns only. It can be 3 hydrae and 3 shadow creature and 3 monstrous menagerie and 3 demons etc. And the most important thing is that you will be completely covered with meat shield, so far entering a floor was the most dangerous situation for any summoner, after the change it will be trivial.

**Comment by Sandman25DCSS** [comment]
It will be somewhat similar to playing with Yred or Beough except better because the summons are disposable.

**Comment by jeremygurr** [comment]
fair enough. So then if there are any monsters in LOS after descending stairs, the summons stay on the previous floor (because they are too scared ... lol). Otherwise they follow. Then much of the tediousness is still spared, but the game is not made any easier.

**Comment by Sandman25DCSS** [comment]
Well, now player has cruel choice: optimal tedious behavior with entering a floor with max MP and manually summoning OR lazy behavior where you have a chance to have all your summons expire instantly and now your MP is much less than max MP.

**Comment by jeremygurr** [comment]
When summons expire for any reason they return full MP. And summons won't expire if you enter a floor with monsters in LOS, they just stay on the previous floor. But maybe that isn't best. Maybe they _should_ expire. That actually makes more sense because in most cases I'm going down a floor and I will see a monster I can easily take out, so I'm going to want to immediately summon more, but I have to unsummon first and then summon, which is slightly annoying. Better to just make them disappear.

**Comment by Sandman25DCSS** [comment]
Oh, I missed that expired summons return MP (actual MP, not just max) back. Or do you mean it will be a new mechanic for this specific case only i.e. immediately after using stairs? I hope the latter and I like it, it solves all problems as far as I can see. You just keep using "default" summons for empty floors or have all MP to summon things based on enemies you see if the floor is not empty.

**Comment by jeremygurr** [comment]
It's already supposed to return all mp when a summon dies. Although there is a bug where it doesn't always happen correctly that I will fix soon. 

The reasoning was because in vanilla crawl you can regen mp while your summons are bashing the enemy, here you can't because your mp max is reduced by your summons. So to balance that out, you get the mp back when the summon dies. 

I'm finding summoners quite powerful at this point and it's possible that a little nerfing would be a good thing. Maybe only returning half mp on death but full mp on unsummoning would be better. But I think a few of us need to play at least into mid game with them to have a better feel for what nerfing if any is needed. After I fix a few summoning bugs of course...

**Comment by Sandman25DCSS** [comment]
Giving full MP sounds OP indeed. When I die as summoner in vanilla crawl it usually happens because I ran out of MP and all my summons died while trying to cover my retreat. So yes, giving less MP is a good idea, maybe it should never be 100% MP, 50% seems good enough. I mean if you spend all MP on 2 Ice Beasts and both died, you can summon an Ice Beast instantly and eventually you will be able to summon another (or just resummon if that Ice Beast is killed too provided it lived long enough for your natural MP regeneration to restore 50% of its cost).

**Comment by jeremygurr** [comment]
Done.
