### ISSUE TITLE
Again with the plate armor casting

### ISSUE THREAD

**Issue by SleepySteel** [jeremygurr/dcssca#327]
but this time it's summoning. I just summoned a hoard of 7 imps, put on plate armor and saw no immediate repercussions to doing so. If there are any that I'm aware of, please correct me.

**Comment by jeremygurr** [comment]
Try playing a game through lair and orc like that and you'll quickly see the problem with that strategy. Your summons will die. You won't be able to replace them without removing your armour. Is that happening in the middle of a battle? Not likely.
