### ISSUE TITLE
Ogre is way too easy for advanced players even on hard mode. 

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#33]
I like the flavor of ogre's getting upset because pain was inflicted on them, and the powered by pain mutation seems to fulfill that well. I also like the idea of ogres having a very high health pool. But as it stands, the ogre is too overpowered to fit the balance requirement for this fork. 

The balance requirement is that on hard mode, a veteran player should have a significant challenge winning, winning no more than maybe 1/2 of their attempts for the easiest of species. Also beginner players ought to be able to win on easy mode within a few months of reasonable, wiki-free practice. I want to get all of these species to get close to these requirements. I don't think all species need to have the same difficulty level, but no species should be so easy that a player can always beat the game on hard mode. Nor should any species be so difficult that a veteran player on easy mode couldn't beat the game consistently (at least 1/2 of the attempts).

So I'm trying to keep the crazy high health and powered by pain mutation of ogres, but am willing to nerf in any other area, at least that somewhat makes sense for the species flavor. Probably taking strength down a fair amount is a good start, since their strength is boosted often in battle. Maybe powered by pain itself is a little overpowered at level 1. Maybe powered by pain level 1 shouldn't kick in unless a single hit of damage is more than 10% of the max hp of the ogre (or even 15 or 20%, depending on how it plays out). I'm okay with tweaking that aspect. I really would like an ogre to feel like a tank, even without armour, at least in the early stages of the game. But they must struggle in a different way to keep the game a sufficient challenge. I already crippled their magic aptitudes, except for spellcasting. 

Here's another idea: what if ogres started with mid-game level attributes, but don't gain ANY more str, dex, int. They would start with normal ogre health/mp, and that _would_ progress with their level. So, instead of starting with 23 str, 7 int, 8 dex, they start with 28 str, 10 int, 12 dex, but it never goes higher. This naturally makes the early game easier than normal for ogres, but later game, an ogre would struggle. Maybe it would be enough of a challenge for a ogre to graduate to powered by pain 2 after level 18 or so. Thoughts?

**Comment by Sandman25DCSS** [comment]
I think 28 str is enough to win, you can equip a GDA or FDA/IDA and still have easy time.

I even remember some game where I sacrificed both Armour and Dodging as an Ogre of Ru and it was still very easy (in Hydra/Statue/Dragon form).

By the way I see a similar issue with VS, the species is balanced via low HP but the problem does not exist with +50% HP (and 21+ AC) on D1. I was able to kill 3 Orc Wizards, Orc Priest, Menkaure and a group of normal orcs non-stop on D5. 3 turns to exit Tree form is dangerous sometimes but the defenses are too good (I stayed in tree form when Eustachio noticed me on D4, for example, it could not hurt me much while I used ranged attacks). Adders and Worker Ants are plain joke no matter how early they appear.

**Comment by Sandman25DCSS** [comment]
Here is a fight with Ogre on D5, this is just broken.

The ogre barely misses you.
 You hit the ogre (5).
 The ogre is lightly wounded.
_The ogre hits you but does no damage.
 You barely miss the ogre.
_The ogre is lightly wounded.
 You hit the ogre but do no damage. The ogre is poisoned.
 The ogre is lightly wounded.
_The ogre hits you but does no damage.
 An orc comes into view.
 You completely miss the ogre.
 The ogre is moderately wounded.
_The orc hits you but does no damage.
 The orc shouts!
 You hit the ogre (5).
 The ogre is heavily wounded.
_The ogre hits you but does no damage.
 You hit the ogre but do no damage. The ogre looks even sicker.
 The ogre is heavily wounded.
_The orc barely misses you.
 You hit the ogre (2).
 The ogre is heavily wounded.
_The ogre barely misses you.
 You barely miss the ogre.
 The ogre is severely wounded.
_The orc hits you but does no damage.
 You hit the ogre (3).
 The ogre is almost dead.
_The ogre barely misses you. The orc hits you but does no damage.
 You barely miss the ogre.
 The ogre is almost dead.
 You kill the ogre!

**Comment by jeremygurr** [comment]
Excellent. This is helpful. 

What about starting Ogre 25, 10, 12? Maybe you could tell me the attributes of the ogre you won with?

Go ahead and create a new issue about vine stalkers, and we can begin bringing that into balance. When this particular issue is resolved, Ogre should be close to as difficult as normal crawl on normal difficulty mode. 

I'm okay with having a species that is overpowered for early game, but becomes a decent challenge mid game, and gets even harder after that. But i'm definitely not okay with one that is too easy throughout.

**Comment by Sandman25DCSS** [comment]
I am not sure it is possible to create problems late game via stat alone, when the species has huge HP.
Mummies don't get any bonus stats and start with pretty bad ones but still it is easy to have decent defense: AC 25/EV 22 is enough to win even when you have stats for ring mail (Str 14, Dex 19). http://crawl.berotato.org/crawl/morgue//Sandman25/morgue-Sandman25-20150317-021625.txt
Also I have offline win where Deep Elf with Str 14 was wearing +4 Shadow Dragon Armour (and everything else was normal +2 equipment without any AC from jewelry) and it allowed to have AC 39 (Armour skill 21).

**Comment by jeremygurr** [comment]
Hmm, what if Ogres never could wear more than a robe and cloak? They have awesome HP, but have a tough time dealing with damage even into the late game. In the normal game I find ogres quite a challenge until I finally get some dragon armour. Then it becomes relatively easy, even for me. 

That might be enough of a nerf to keep the late game challenging. Yeah they no longer becomes the super tank of the game, that would have to fall to another species, which is fine. I think this still preserves the distinct flavor of the ogre.

**Comment by Sandman25DCSS** [comment]
Then they will be somewhat similar to Felid who greatly benefits from transmutations.

**Comment by jeremygurr** [comment]
Ok I've got ogres having deformity level 1 and 2 over time, making it much harder for them to get high AC. May still be overpowered, but getting closer. They also don't gain stats with experience levels.

**Comment by Sandman25DCSS** [comment]
I am playing a TrFi at the moment and the hard mode is really hard.
I have 49 max HP at XL 10, my Fighting is 7.5 (I started with 39 max HP and Fighting 2.4). I basically have to berserk in most fights. So I guess I was wrong about max HP not being that important in hard mode, it depends on how much it differs from normal mode.

**Comment by jeremygurr** [comment]
In addition to the 25% less HP for hard mode, trolls also don't gain ANY HP per level, in an attempt to balance the fact that they gain many elemental resistances for free as they advance in levels. I want to strike a balance here that makes late game for a troll very difficult, but not impossible. Trolls would effectively become very easy early game, moderate mid game, difficult late. So maybe I'll boost their health a little for now. 

-- Jeremy

**Comment by Sandman25DCSS** [comment]
Yes, I realized trolls don't get any HP at XL 2, it was pleasant to save game with 58 HP and load it with 81 :)
Lair was extremely hard, not sure what I would do without gifted large rocks and berserk. Though I liked the challenge and almost want to ask to revert the change.
Those resistances are ridiculous, I am ready for the Zot: rF+++, rC+, rElec, rPois (got lucky with beneficial mutation), it was even in Lair. You basically reverted Troll, previously it was huge HP with lack of resists, now it has tiny HP with abundant resists. Don't call it a Troll after that ;)

**Comment by jeremygurr** [comment]
I pushed the resistances into higher levels. You start getting the resistances at level 10, and get a new one every couple of levels. The early game is so easy for a troll anyway it doesn't need the resists. But late game should be a substantial challenge, even with the resistances.

**Comment by Sandman25DCSS** [comment]
Yes, I like the Troll. It is really unique species, HP is similar to Felid but there are no extra lives, speed or magic aptitudes so the species uses physical attack and group-splitting tactics. Using Shadow Dragon Armour because every resistance is already covered is fun. Of course I used guardian spirit like Spriggans often do, 108 max HP and 35 max MP allow to win. Your other species are easier than standard ones, this one is an interesting exception.

**Comment by jeremygurr** [comment]
Nice! 

I'd like all the species to be a decent challenge eventually, at least on hard mode. I don't want them all to necessarily be the same difficulty, but at least none of them should be so easy that they are boring on hard mode. 

-- Jeremy

**Comment by Sandman25DCSS** [comment]
That would require some non-trivial changes IMHO. Centaur with bow/polearm can kite almost everything, no matter hard mode or not.

**Comment by Sandman25DCSS** [comment]
That would require some non-trivial changes IMHO. Centaur with bow/polearm can kite almost everything, no matter hard mode or not.

**Comment by Sandman25DCSS** [comment]
Standard crawl devs say that species is kind of difficulty level so Centaur with ranged attack is one of the easiest modes so it is probably ok if it will be easy/boring even in hard mode. The same with MiBe, DDFi etc.

**Comment by jeremygurr** [comment]
Yeah I can see that. These pose very interesting challenges. Some may not even be possible, but I'm going to get them as close as I can.

**Comment by Sandman25DCSS** [comment]
This is what I mean as Powered by Pain being too strong.

Grinder comes into view.
 Grinder shouts!
 Grinder gestures at you.
 Pain shoots through your body!
- \* \* LOW HITPOINT WARNING \* \* *
  You focus on the pain.
  _You feel very mighty all of a sudden.
  Huge Dmg: -30%(-13hp) hp: 70%(29hp)
  You turn into a venomous arachnid creature.
  Your +1 cloak melds into your body. Your +0 robe melds into your body.
- \* \* LOW MAGIC WARNING \* \* *
  Grinder gestures at you.
  _You resist with significant effort.
  _Grinder misses you.
  Found 4 gold pieces.
  You bite Grinder (11)! Grinder is poisoned.
  Grinder is moderately wounded.
  _Grinder closely misses you.
  You maul Grinder (23)!!
  Grinder is almost dead.
  You kill Grinder!

**Comment by jeremygurr** [comment]
It is understandable to me that grinder should be fairly easy for an ogre, since grinder is an early game unique, and ogres are built to be strongest early game. 

In this case, what exactly was the effect of might? Doesn't it only increase your strength? Do you remember how much? Keep in mind that without the attribute increases every few levels that DCSS has, even though the Ogre may feel a bit overpowered in the early game, it should be significantly harder later game, even with powered by pain, since you will be around 9 points lower in str than you would normally have by the time you reach level 20. And if that is still too much, we can lower starting strength a few points. I think part of the fun here is that your strength _may_ be increased, or your _agility_ might, you don't control it, and so may have to compensate for what ends up happening. We could even expand it to throw some other random boosters in there. I think it might be fun to throw in a low chance of berserk or even, more rarely, a pure haste. We can also tune it to kick in less frequently if it feels too overpowered by mid-late game. If it messes up the original idea of power-by-pain too much, it can be broken out into it's own mutation just for ogres. Another option is to make it only kick in after the ogre is below 50% health (or some other % if that makes more sense), instead of after the first hit. 

I think there are lots of ways we can tweak this to get a satisfying result. But I'd like to make sure it really needs to be tweaked first. I think if by mid game the ogre is still taking out uniques with ease because of powered-by-pain, we need to look into some nerfing for it.

**Comment by Sandman25DCSS** [comment]
Check http://crawl.chaosforge.org/Potion_of_might, Might effect is similar to +10 slaying without even taking Strength bonus into account. Probably the mutation should happen at XL 10-15 or so.
I have just entered Zot and I can no longer say that Ogre is too easy. It somewhat reminds me new Troll, while Troll can have high AC and low HP, Ogre can have low AC and huge HP, even in almost fully enchanted FDA . Though I solved the problem via Statue Form (AC 31, EV 24 with Shaolin), before that Makhleb helped with low defense problem a lot.
I am still casting level 6 spells easily (Haste, Statue Form at 3%) with Int 12-15 and 11 levels in Charms/Transmutation/Earth, 15+ Spellcasting, my EV is still very bad because of being huge and my Strength is still huge (141 damage in statue form is fun, that's without any slaying or str gear). So I don't like lack of attributes increase, it does not limit character much but makes me feel like all Ogres will be identical, I like to make decisions.

**Comment by jeremygurr** [comment]
Yeah I can make the mutation come in at level 12. I'll bring the attribute growth back. Does it make sense for the powered by pain to be less frequent? Maybe 50 chance when it would normally happen?

-- Jeremy

**Comment by Sandman25DCSS** [comment]
Yes, less frequent would be good I think, it triggered in almost every fight in Depths.

**Comment by jeremygurr** [comment]
Done.
