### ISSUE TITLE
255 MP

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#332]
I don't know when and why it happened but I have 255 max MP as XL 27 DD without +MP items in easy mode.

Health: 417/419    AC: 44    Str: 30    XL:     27
Magic:  179/255    EV: 27    Int: 11    God:    Makhleb [******]
Gold:   7371       SH:  0    Dex: 18    Spells: 12 memorised, 11 levels left

rFire  + . .      SeeInvis .    b - +6 executioner's axe of Blind Justice {drain, Str+4} (curse)
rCold  + + .      Gourm    .    k - +8 ring mail of Horyum (heavy curse)
rNeg   + + +      Faith    .    (shield currently unavailable)
rPois  âˆž          Spirit   .    x - +2 helmet of Jooskily {rPois rC+ Str+2} (curse)
rElec  +          Dismiss  .    O - +2 cloak {MR+} (curse)
rCorr  .          Reflect  .    C - +1 pair of gloves of Zin's Envy {rF+ rN+}
SustAt +          Harm     .    Y - +2 pair of boots {run}
MR     +++++                    n - macabre finger necklace {rN+} (curse)
Stlth  ++++......               R - ring of sustain attributes (curse)
                                D - +3 ring of slaying {=R}
                                E - ring "Plog" {rElec rN+ Stlth-}

**Comment by Sandman25DCSS** [comment]
It keeps growing, I have 301 max MP now.

**Comment by Sandman25DCSS** [comment]
And now 1023 MP

**Comment by jeremygurr** [comment]
wow. I'll capture your save file.

**Comment by jeremygurr** [comment]
Fixed in 1.3.3

**Comment by Sandman25DCSS** [comment]
Thank you! 
15 runes win is easy at easy, the only boss I couldn't kill was Ereshkigal, she was last and according to my calculations had 460 HP and healed for 50-230 HP too often so even +6 executioners axe couldn't kill her (I was lazy to retreat, exit Necromutation and quaff some potions so I just got the rune and teleported). 
Also I can confirm that we must not allow unlimited Necromutation as it makes extended hilariously easy, even levels with lots of silence and waves of different fiends and tormentors didn't cause any problems. 

For some reason hell effect which makes all magical effects expire does not expire Necromutation, it indicator just becomes dark green instead of light green so I guess we have a bug here.
