### ISSUE TITLE
VS is too easy

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#34]
Treeform is extremely powerful early game, +50%, AC 21, rPois and immunity to torment/draining allow to kill everything. Being unable to retreat is not a big deal because VS has anti-magic bite and can use ranged attacks easily. Later Makhleb solves "unable to retreat to heal" problem, also natural regeneration helps a lot.

**Comment by jeremygurr** [comment]
Hmm that is definitely a problem. Maybe treeform comes later in the game and we nerf some hp growth so it balances. I'll try that unless someone else has an idea.

**Comment by Sandman25DCSS** [comment]
My experience shows that tree form becomes really bad in Lair so I think the balance should be changed for early game only.

**Comment by Sandman25DCSS** [comment]
I mean I am highly unlikely to use it late (except in extended of course) so if it becomes available at like XL 10-12 it is almost useless.

**Comment by jeremygurr** [comment]
I see. So it is helpful in early game, but makes early game too easy. Doesn't really impact late game since using it is too dangerous in most circumstances or doesn't provide a strategic advantage, since late game ac is as high or higher anyway?

Are you saying that it's too dangerous to use in Lair, or that it isn't helpful enough to be worth it at that point in the game?

Hmm... maybe treeform can boost HP also, making it still useful in late game. But maybe it should stop all regeneration at the same time, to keep from being overpowered because of the VS regen. Choosing to lignify should be a carefully considered risk, like choosing to berserk. Delignifying should be costly enough to pose a serious threat if the player hasn't cleared out the danger first.

**Comment by Sandman25DCSS** [comment]
It is very helpful for rPois but Lair has some very dangerous monsters, I almost died to a single Black Mamba because I was unlucky with damage rolls and could not use scroll of blinking or teleport.
Before Lair it gives so much AC that being unable to retreat is not a big deal.
I was lucky to find a great chain mail so in Lair my AC was pretty comparable to treeform.

**Comment by jeremygurr** [comment]
Ok I revised VS a fair bit and deployed the update. AC of lignify is a little weaker at the beginning, but it gets stronger with experience, much stronger than before, so it should be a useable tool even in late game. Lignify also gives a little more health boost than before. 

However, I did nerf some things to help balance a little. There is no HP regen during tree form. VS now has deformed body mutation at the beginning, and gain deformed 2 at level 12, making body armour only give 1/3 AC of normal at that point.

**Comment by Sandman25DCSS** [comment]
Deformed body is not that important, it does not prevent any species from being able to have huge AC.
Is your intention to make VS use treeform in most fights? No tele is too dangerous, even Maxwell's patent armour is bad for most species.

**Comment by Sandman25DCSS** [comment]
I am not sure if I like it but I have just killed Khufu in treeform, AC 48 and 260 HP at XL 22 as VS. Probably it is OP a bit.

**Comment by Sandman25DCSS** [comment]
I see, you doubled HP in treeform.

**Comment by jeremygurr** [comment]
Ok I took the hp boost in treeform down a bit, still higher than original, but not quite as high. I _could_ start differentiating some of these things based on hard/easy mode. It would enrich hard mode, but also make things more difficult to learn, as there would be many different rules for hard mode, as opposed to just a few sweeping changes. Hmm... I guess it's best not to make micro distinctions.

**Comment by Sandman25DCSS** [comment]
I think VS should be unable to train Armour, similar to Draconian.

**Comment by jeremygurr** [comment]
Done.

**Comment by jeremygurr** [comment]
If this version still seems OP, I can reduce the health boost further. The main aspect of this strategy is a temporary AC boost in exchange for mobility. It should not be something used in every encounter, but should be mostly used for the harder ones. But it shouldn't be a guaranteed win either. Sometimes, lignify should be a bad or fatal decision, in the same way that berserk is sometimes great, sometimes very bad. 

Also, for some things that are OP for you, aren't even close to OP for me. But my objective with this fork is to balance the game for newbies, intermediates, and experienced players. So normal mode _should_ feel OP for you in many ways. But hard mode should still pose a challenge for you. I think I will reduce max hp for hard mode also, maybe 25% less.

**Comment by jeremygurr** [comment]
Oh the armour training won't go away until a Vs character is started, since that's when the game puts together what can be trained.

**Comment by Sandman25DCSS** [comment]
Yes, I think the balance is good now, I lost +6 chain mail with rF+++ and slaying+6 so my character went down from AC 34/EV 21 to AC 15/EV 31. Of course it made me learn Ozocubu's Armour and pick up some rF+ gear. Tree form was nice during orb run, Shadow Fiend is not dangerous when you are immune to both torment and dispel undead.

**Comment by jeremygurr** [comment]
Excellent!
