### ISSUE TITLE
Ghoul and carnivore weirdness

### ISSUE THREAD

**Issue by SleepySteel** [jeremygurr/dcssca#344]
First of all, is there any point for Carnivore to stay in the game if food isn't a major mechanic anymore? It's a purely negative trait.
Second of all, are ghouls supposed to be unable to stop rotting/restore rot by eating enemies?

**Comment by jeremygurr** [comment]
There are many mutations that are purely a negative trait. I'm not sure that's a bad thing by itself. 

Ghouls should be restoring rot as they eat enemies. Eating happens automatically when some enemies die. Do you think it's not happening?

**Comment by SleepySteel** [comment]
I'm absolutely certain that the only times my character healed from rot was when I quaffed potions of heal wounds- as a regular ghoul player I always keep an eye on rot HP.

**Comment by jeremygurr** [comment]
Fixed.
