### ISSUE TITLE
Berkerk and Trog

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#347]
I killed a monster while berserking, got a message that Trog prolonged my berserk and then next turn I am no longer berserk despite having 35/80 stamina. I don't remember having such situation in vanilla crawl so maybe something is wrong.

You reach to attack! You slice the orc warrior (24)!!
 The orc warrior is severely wounded.
_The orc warrior completely misses you.
 You reach to attack!
 You cut the orc warrior into ribbons (38)!!!
 You feel the power of Trog in you as your rage grows.
_You kill the orc warrior!
 You are no longer berserk.
 You are exhausted.
_You feel yourself slow down.

**Comment by Sandman25DCSS** [comment]
Version 1.4

**Comment by Sandman25DCSS** [comment]
I was using vampiric weapon if it matters

**Comment by jeremygurr** [comment]
vampiric does burn through stamina faster, as does berserking. However, there was a melee related stamina bug I fixed in 1.4.2, which would probably help the situation here.

**Comment by Sandman25DCSS** [comment]
Ok, thank you!
