### ISSUE TITLE
standardizing god piety gain

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#349]
I'm not sure that the flavor gained by each god having a different way to gain piety is worth the complexity cost and frequent annoyance that it causes. Case in point: with sif you gain piety while training spell skills. But it's not always the best thing to do as a spellcaster. But because that's there, you are pushed to choose a non-optimal course for no real reason other than flavor. It doesn't increase the depth or fun of the game IMO. Many of the old ways of gaining piety (sacrificing corpses, etc) have already been removed from vanilla crawl, and most gods have ended up with the same basic piety gain mechanic: kill lots of stuff and you'll gain piety. 

I think a simplification here would help things a bit. What if all gods gained piety through experience gain? Just like training skills, just like charging evocables. It creates the needed limitation so that you can't just spam abilities without limit in an easy to understand and standardized way. _Then_ you can choose how you get that experience through experience mode selection. Do you want to gain piety by killing lots of monsters? Use classic mode. Would you like to gain piety by exploring more of the dungeon? Use one of the floor based modes. Would you like it to be a combination of a few different things? Choose one of the hybrid modes. 

But what about Ash? Ash has one of the coolest and most meaningful piety gain mechanics. However, it seems to me that even if Ash followers gained piety through experience, you would still want to curse your equipment because that's how you get the cool boosts and free identification that ash provides. Effectively it wouldn't change much in how a player actually plays ash, but the piety gain mechanic itself is much simpler, and should you choose to have less items cursed, you won't have as much bonuses, but you can gain piety just as quickly as ever just by continuing to play the game. 

It would be good along with this to add a new experience gaining mode, that is based on how much of each floor you've actually seen, as opposed to just how many floors you have seen. That could be mixed in with a few of the others too.

**Comment by yrmvgh** [comment]
Like I said, Ru, Ash, and Nem have fun piety gain that encourages me to play slightly differently than I do with standard gods. I would like to keep those. Bonus: they work fine in any experience mode with or without the change.

Xom and Gozag would require a big rewrite if you change them.

I also feel that makleb's abilities all scream "chain kills!" (get more value out of your long-duration summons that way) and it would really suit him better to be the one god that stays on the Kill Count system. He's already bad for pacifists, so keeping him kill-based helps steer them toward gods that provide a better mix of combat, avoidance, and utility abilities and away from The Murder God.

**Comment by jeremygurr** [comment]
True, Ru and Nem have very specific piety gain mechanics that are important to how they work. 

But Ru doesn't really have piety. Just give you permanent abilities in exchange for sacrifices. Piety as a consumable resource doesn't exist there. 

Nem does gain piety based on drawing cards, right? Hmm... It really doesn't influence my game. Maybe I just don't know how to use it right. I just pull out cards when I need them, and get more gifts of cards than I could ever use. What impacts does Nem's piety mechanic have on your games?

I don't think Xom needs to be changed. He doesn't have any kind of consumeable piety either. And Gozag also doesn't have a separate piety resource, since he just uses gold, so no change needed there either. 

I'm not sure if this makes sense yet or not. Just toying around with the idea for now.

**Comment by yrmvgh** [comment]
In a manner of speaking, Gozag is a "kill god", so you could change him to spray coins at you or around the floor whenever you gain exp. Sounds silly, but might be a good change for pacifism (but no one plays pacifism?)

Nem is just an exploration god, like ash, and I guess Ely is too. I enjoy it as a slight change of pace, it makes me a little bit happier about Passive Mapping (because that counts as exploration), and it makes me a little bit more interested in cracking open the occasional map feature that is inaccessible to normal autoexplore. Like the lava snake vault in Lair - no loot, but a bit of exp, a bit of exploration piety, and a cool "I found a secret that i wouldn't have found if I was just mashing o and tab like an angry zombie!" feeling.

**Comment by jeremygurr** [comment]
True, gozag gains his "piety" through kills. I like the idea of finding other ways the money could appear. Maybe he just rains gold randomly when monsters are around. 

No I don't think anyone plays pacifist, at least not yet. I don't really care that much about pacifism itself, I'm more interested in just decoupling the piety gain from one specific experience model, so that we can more easily experiment with others such as pacifism, or explorer centric, or even an opposite of pacifism, where you are penalized for exploring or taking too much time between kills. Some of these modes may end up lame, and no fun. But we may also discover something very fun and unique. But we need to have things cleanly decoupled to have that option.

**Comment by yrmvgh** [comment]
Gozag should bounce coins off your head, interrupting you when you're trying to rest. That would be completely compatible with all experience modes.

**Comment by SleepySteel** [comment]
I don't think gods need to be more of the same- I think they need to be less of the same. Sif Muna's piety gain is unique and interesting, because like you said, it forces a specific path- that's what a god SHOULD do! A god should offer your rewards with costs, costs like needing to do something you otherwise wouldn't, such as not using a demon whip of pain if you're with a good god, not using a scroll of holy wrath if you're with a bad god, or not starting to train fighting yet if you're with sif muna.

**Comment by Sandman25DCSS** [comment]
Piety for exploration should stay IMHO, for example Sp of Ash can decide to ignore most monsters. As far as I remember your plan, there are no XP potions/bonuses for Abyss/Pan.

**Comment by jeremygurr** [comment]
Yeah I guess you are right. I'll drop this one.

**Comment by yrmvgh** [comment]
Most of the kill gods could still be just "exp gods". The differences between what they like you to kill are unnoticeable.
