### ISSUE TITLE
Summoner unbalanced

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#35]

**Comment by jeremygurr** [comment]
Okay I got this a lot closer to where it should be. Try out the summoner if you get a chance. It should be a much improved experience.

**Comment by Sandman25DCSS** [comment]
It looks good at XL 1. What is "Summon cost: 121   magic cost: 1"?

**Comment by Sandman25DCSS** [comment]
It's definitely still harder than standard crawl at XL 2. If I am unlucky with Imp (got one with blinking ability for example), I have to disband it, pillar-dance to restore HP/MP and try again. Not sure if it is intended. It feels like a background for masochists :)

**Comment by jeremygurr** [comment]
Okay I spent a bit more time testing it this time. Normal mode tengu summoner felt good to me for the first 10 levels or so. I was casting a couple of canines with an ice beast, and could maintain that for 10 turns or so, enough time to take out most small groups. Spell power makes a big difference though in how long they can be maintained, so I put most of my early training in summoning, and my attribute points in intelligence. 

Summoners now should be quite a bit easier, but hopefully not too easy.
