### ISSUE TITLE
Form-changing poison

### ISSUE THREAD

**Issue by SleepySteel** [jeremygurr/dcssca#355]
First and foremost, I want to thank you for giving transmutations to ghouls. Really fun change. Odd case here, though- if I cast blade hands as a ghoul I become susceptible to poison. If I am poisoned and the form ends, the poison will become grey-colored and stop ticking down. Is this supposed to happen?

**Comment by jeremygurr** [comment]
No that doesn't seem logical. I need an exception for the semi-transformed like blade and appendage.

**Comment by jeremygurr** [comment]
Fixed.
