### ISSUE TITLE
Too much fruit

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#356]
Right now there's way too much fruit in the game because many vaults create it. So I think I'll turn fruit spawning way down, and if that's not enough we'll have to remove some from vaults.

**Comment by Sandman25DCSS** [comment]
I guess it will be a serious Fedhas nerf, is it expected? As a Fedhas worshiper I never eat fruit (I haven't played Sp of Fedhas of course).

**Comment by jeremygurr** [comment]
I don't think Fedhas will have any less fruit than they normally would in vanilla crawl. The problem is that Fedhas received a ridiculous buff when we converted all food to fruit.

**Comment by Sandman25DCSS** [comment]
Oh, I missed the conversion.
