### ISSUE TITLE
branch repositioning

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#362]
In the interest of trying to flatten difficulty between branches, and improving the difficulty flow, I'm thinking of positioning the branches like so:

lair, forest, orc, depths: dungeon
dwarf, shoals, snake: lair (easy runes)
elf, spider, swamp: forest (easy runes)
slime, vaults, crypt, abyss: depths (medium runes)
tomb: crypt (hard rune)
pan, zig, hell: depths (hard runes)

The 6 "easy" rune branches in lair and forest should be roughly equivalent in difficulty (notice I removed slime).

The 3 "medium" rune branches are found in depths.

The remaining 10 hard rune branches are found in branches from depths. 

optional runeless branches: orc, zig, and all timed branches.

**Comment by yrmvgh** [comment]
I can't really disagree with any of this, and having finally explored forest it seems like a great place to find passages to other branches, thematically.

I will try to design a vault that feels like an "entrance" to the dwarven fortress and not just a damn hole in the ground.

**Comment by Sandman25DCSS** [comment]
The only issue I see is that Forest is harder than all branches it contains.

**Comment by Sandman25DCSS** [comment]
Also I hope Vaults entrance will be on Depths:1

**Comment by jeremygurr** [comment]
agreed. I'm okay with forest being a little harder in some ways than lair, but it shouldn't be dramatically harder if we are positioning it this way. 

In this case it should probably have 8 levels like lair, and maybe the monsters could be spread out a bit more to give a lair-level player a fighting chance. 

Maybe in the lower floors it could be as difficult as it is now, with the enchantress at the end, but in the upper floors it should be closer to lair difficulty.

**Comment by G0rg0** [comment]
As much of a pain in the ass as slime can be, I'd rather have it tweaked to be more fun than just nuked.

**Comment by yrmvgh** [comment]
> In this case it should probably have 8 levels like lair, and maybe the monsters could be spread out a bit more to give a lair-level player a fighting chance.

You keep talking about adding floors to things. Isn't the game long enough? We already have 3 boring orc floors (instead of just 1) before the good one. :wink:

**Comment by G0rg0** [comment]
Wasn't Orc reduced to 2 floors in vanilla?

**Comment by yrmvgh** [comment]
That's the joke! Or pun. Or maybe just passive aggressive whining. But yes, yes it was. :camel:

**Comment by yrmvgh** [comment]
> As much of a pain in the ass as slime can be, I'd rather have it tweaked to be more fun than just nuked.

Not removed-removed, just removed from lair, so that people don't blunder in as easily. if you look at the list it's been grouped with other difficultish branches.

**Comment by yrmvgh** [comment]
Admittedly the level layout of Orc is more interesting with more floors, the weird stair use and disconnected sections and all. Perhaps one of the floors can just be empty so it feels less grindy to get through it?

**Comment by jeremygurr** [comment]
Another stab at this:

lair, forest, orc, depths: dungeon
spider, swamp, shoals, snake: lair (tier 1 runes)
dwarf, elf, slime, crypt: forest (tier 2 runes)
vaults, abyss, pan, zig, hell, zot: depths (tier 3 runes)
tomb: crypt (tier 4)
- : hell (tier 4)

**Comment by jeremygurr** [comment]
It feels like tomb should be moved out of crypt. Crypt should actually have the rune (since it's at a similar difficulty level as slime, elf, and dwarf). Tomb should _not_ have a rune, but should join orc in being an optional branch with ridiculous treasure at the end if a player can survive it. Think of this in the context of the rune curses. Do you really want to try and take on tomb with 5-10 rune curses already attached to you? It's enough of a challenge even without rune curses. It also makes it possible for players attempting full rune wins to just skip tomb if their character isn't up to it. 

So then crypt would stay in forest as mentioned above, and tomb would be put in depths with the other tier 3 and 4 rune branches. Tier 3 rune branches should be found in early depths and tier 4 rune branches should be late depths. Feels like depths needs a few more levels with the 7 branches coming from it. Maybe 8-10 instead of 5. That would also make the orb ascension a little more challenging, which is something I'm wanting to do.

**Comment by Sandman25DCSS** [comment]
I think nobody will enter Tomb if it is one of the hardest places but has no rune. No loot is necessary at this point and even if player does need some loot, it is not worth the risk as you are more likely to die while going for the loot than if you play without it.

**Comment by jeremygurr** [comment]
BTW if orc is too boring, let's add a little more spice. Look over the vaults for orc and see what you can do. We don't necessarily want it more difficult, and maybe in some cases reducing monster count would be a good thing. Orc is meant to be a early game side track that is somewhat challenging but lucrative to a lair level character. I did adjust orc to appear a little earlier to encourage players to take it on sooner, thus automatically increasing the challenge level.

Maybe it would be fun to add a battle arena in the 2nd floor of orc. If you enter the arena, you fight one other orc. Orcs in the stands will cheer (or boo) you on. Fight to the death. Then the player can choose to move to the next contender. Those who have played some of the older rogue-likes will recognize this idea. But if you accept a challenger, you are forced to stay in the arena until the battle is over (no escaping, no teleporting). To be fair though, you will be told who the next contender will be. It will always be orc or ogre like, and a single monster. And you get more gold for each contender you vanquish. The first few will be trivial of course, easy money. But before long you will be facing cyclops or giants of various kinds. Players will need to know when to quit while they are ahead, or suffer the consequences.

For added flavor, orcs in the stands that were impressed by your victories will become neutral towards you when you leave the arena and they return to their normal duties of killing hapless adventurers. 

I'm sure this idea has been proposed and shot down countless times in vanilla crawl, but at the moment I don't see why not. It would definitely make orc more fun and appealing.

**Comment by jeremygurr** [comment]
If tomb is so difficult no one wants to try it, then we should tweak tomb until it is tempting for a late game player to enter it. Maybe we make escape easier somehow, so a player is at least willing to step in inside and see if they have what it takes, and if not, they have a good chance of escaping. Maybe in tomb the monsters can't interrupt stair ascension (like in the abyss). And as proposed earlier, I think there should be more than one entrance into each branch, so that if the main entrance is overcrowded, the player can still sneak in the back door and take another stab at it.

But also keep in mind that the loot in tomb will be better than it is now. In vanilla crawl, at the time you would attempt tomb, money is almost meaningless, and you have most of the weapons and armour you will be using for the rest of the game. With the new late game potions, scrolls, super-artifacts, stores with higher prices but even better goods, etc, that I am also adding, tomb will become an essential restocking place for players who wish to have any chance at a 15+ rune win.

**Comment by Sandman25DCSS** [comment]
Not sure if you read this: https://crawl.develz.org/tavern/viewtopic.php?f=8&t=18817&p=255867 It's a thread on tavern started by a dev about rune curses.

I think no loot can make Tomb a good idea unless it is much easier than other places.

Edit. I mean no matter what loot Tomb has, it is not a good idea to visit it if you can visit other areas and find some loot there. It works with other places too, for example, players visit Lair first despite Elf 3 has much better loot.

**Comment by G0rg0** [comment]
How about in addition to loot (which may not be enticing enough), there is some kind of guaranteed character enhancement at the end. A non-god affiliated altar that grants you a resistance / selectable benemut or a super acquisition or something?

**Comment by jeremygurr** [comment]
Well if tomb must have a rune, it could have the 20th one, the crowning rune that has the best rune perk, and maybe the worst rune curse. It is nice to have an even 20. 

Maybe tomb could be put on the last floor of depths then, to make it clear to the player that it's the hardest.

**Comment by jeremygurr** [comment]
The runes themselves provide the major beneficial upgrades as part of the perks they give, so it would overlap a little too much here.

**Comment by yrmvgh** [comment]
> Maybe tomb could be put on the last floor of depths then, to make it clear to the player that it's the hardest.

Tomb requires 15 other runes, and its rune perk is designed to be great even when it's the last rune you get.

**Comment by jeremygurr** [comment]
Done.
