### ISSUE TITLE
When you close a door on a dragon

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#364]
It should proooobably destroy the door

"Oh geez I'm only a dragon I don't have hands."

Could this be generalized out further though? How big, or strong, or magical should a door breaking monster be? existing [monster flags](http://crawl.chaosforge.org/Category:Monster_flag) could also have "door breaking" abilities added to or triggered by their flag. Any monster with a headbutt for instance could bash down doors. Scary yaks!

**Comment by G0rg0** [comment]
There is a dragon that can break doors - the unique Xtahua

**Comment by jeremygurr** [comment]
Seriously? That's hilarious.

**Comment by yrmvgh** [comment]
Yeah apparently the tag already exists, it just isn't used as widely as I think it shoud be.

 M_UNIQUE | M_SEE_INVIS | M_WARM_BLOOD | M_SPEAKS | M_MALE | M_CRASH_DOORS | M_FLIES,

**Comment by yrmvgh** [comment]
@Sandman25DCSS is tired of players getting buffed, I'm going to PR door-crasher on a bunch of big monsters. Elephants laugh at your puny little "door"!

**Comment by Sandman25DCSS** [comment]
I wouldn't look at what a player wants as long as most players want something else.

I guess it will require changing some vaults (also I am not sure if monsters can destroy runed doors).

**Comment by yrmvgh** [comment]
It can't destroy runed doors. If it ends up being a problem report back! Regular doors can already be smashed by a number of player and monster spells without having to use M_CRASH_DOORS, so vanilla probably already has any potential weirdness handled (or accepted as part of the game).

The flag already exists on every unique dragon, not just xtahua, so I am excited to see it on normal dragons! And elephants and death yaks. And the largest abominations and zombies. :grinning:
