### ISSUE TITLE
Unable to change autopickup for potions

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#37]
All potions are assigned to letter 'a' in autopickup screen, I am unable to change specific potions, only first 'a' potion is changed.

**Comment by jeremygurr** [comment]
Isn't the autopickup screen you are talking about the \ one? Mine seems to work like normal. I can't seem to find the symptom you are referring to.

**Comment by Sandman25DCSS** [comment]
Yes, the \ screen. It was working fine before. Now it looks like this http://tinypic.com/r/24qn1nd/9
It's my current game on your server, you can check it there.

**Comment by jeremygurr** [comment]
Ok it should be working correctly now.

**Comment by Sandman25DCSS** [comment]
Yes, it is fixed, thank you
