### ISSUE TITLE
Change Sif Muna's channeling ability to be less tedious.

### ISSUE THREAD

**Issue by G0rg0** [jeremygurr/dcssca#370]
Instead of repetitively channeling MP via the ability menu, how about an activated "mode" like power/careful that gives rapid mana regen but drains stamina? 

The overall MP gain should be effectively the same, just less tedious.

**Comment by Sandman25DCSS** [comment]
Why drain stamina?
I think it could be better to keep existing ability, just change crawl to automatically use the ability every turn while resting with 5.

**Comment by Sandman25DCSS** [comment]
I mean channeling mana in a fight is a meaningful decision which I reevaluate every turn (something can significantly change from last turn) and I suspect that stamina draining will make channeling strictly bad in most fights (it's usually better to use stamina to escape and reset the fight).

**Comment by G0rg0** [comment]
The stamina drain is simply because that's what it does now - every use costs a bit of stamina. I'd love to see that go away but figured it might be OP. 

As for auto-use on 5, what about scenarios where you are in the midst of combat and need a quick channel to cast a spell? If it still triggered a single use when you hit 5 then sure, that would work.

**Comment by yrmvgh** [comment]
I think you're supposed to channel when there's a "lull", it feels more frustrating if you wait until you're out of mana and now you're channeling with something scary in LOS.

**Comment by yrmvgh** [comment]
The ===HDAtravel macro already uses channeling when resting, or at least claims that it does.

**Comment by Sandman25DCSS** [comment]
> The stamina drain is simply because that's what it does now - every use costs a bit of stamina. I'd love to see that go away but figured it might be OP. 

Oh, I haven't used Sif Muna in CA yet. Previously I could use amulet of gourmand and spam channeling easily (100-200 hunger per invocation, engorged is 12k satiation points, starving is 1k so it is 55-110 successful invocations).

> The ===HDAtravel macro already uses channeling when resting, or at least claims that it does.

Yes, I use it. SafeChannel function rules :)

**Comment by G0rg0** [comment]
Well the ideal may be to channel when in a lull, but I find myself needing it all the time in combat. Even out of combat, it's tedious for no good reason. 

_So_ tedious in fact, that someone spent time to write the SafeChannel function. Why not just fix it's basic behavior?

**Comment by G0rg0** [comment]
Sif is supposed to be "the" choice for casters, but Vehumet's passives are way better to me. The increased range alone! Maybe something completely different is in order now that I am thinking of it.

Some ideas:

-Overall mana regen increases with piety gain. At max piety maybe not as fast as a moon troll, but _fast_.

-MP pool increases with piety gain.

-The spellcaster match to berserk: Burns some piety, but gives you an emergency MP equiv of "tireless" for a few turns then exhausts/confuses you. "Your mind becomes charged with clarity and power, spells are effortless!" (this is not the same as a potion of brilliance)

Anything that's more fun than the current drip drip drip of a bit of mana.

**Comment by Sandman25DCSS** [comment]
I think Vehumet should be better than Sif Muna for Conjuration spells, Vehumet is the god of Conjurations after all.

Sif Muna is great with summoners in vanilla crawl, today a guy sent me a link to game where he spams Dragon Call after 1 rune with 24% failure rate.

**Comment by G0rg0** [comment]
I never play summoners so there is that, but Sif should be good for all casters. Veh should be particularly good for conj, but ends up being better for almost everyone (with the exception of summoners maybe?). Almost every attack spell is partly conj, and even those that aren't benefit greatly from the extended range and mana regen.

**Comment by yrmvgh** [comment]
Maybe I'll PR some of your ideas for testing after this weekend. Testing is in some ways easier than discussing endlessly - if the code is not too complicated.

**Comment by jeremygurr** [comment]
Why would anyone channel outside of battle? Why not just rest? Does anyone have 0 magic regen? I must be missing something here.

**Comment by jeremygurr** [comment]
I agree that mana channelling shouldn't really be used continuously. I'd say just set up a single key macro, then you can save some keystrokes, and just hit it when it is worth spending a turn and some stamina for. 

Or we could make it convert stamina into mana, until you either run out of stamina, or fill up with mana. Maybe a 2:1 ratio? Or 3:1? So if you are full of sp (100), and 0/40 of mp, then you would end up with 10 sp and 40 mp. The ratio should be based on invocations I guess. 10:1 ratio at 0 inv, 2:1 at 27 inv? That would be a significant buff though since it would cost a lot less turns to do it, but it would save some tedium. But what if you didn't want to burn through all of your stamina? The first way gives more control, at the expense of more turns. 

Another option: much closer to the original, we could just try and channel 10 mp with each usage, enough to cast any spell. But the sp cost varies by inv, as above. At 0 inv, that 10 mo would cost 100 sp. If you don't have enough, you won't get the full amount of mp. 

I like the third option best so far.

**Comment by jeremygurr** [comment]
This conversation has been transferred to a more general "fix sif" issue.
