### ISSUE TITLE
Power mode is slower than normal mode

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#373]
...unless you run for at least 4 turns!

Because power mode now has that "change direction" penalty from the old anti-pillar-dancing code, beginning to run (typically in the same direction you came from, natch) counts as changing direction, so instead of losing 1.1 turns like you would in normal mode, you lose 1.5 turns.

And die. :anguished:

**Comment by jeremygurr** [comment]
Okay.... I guess I can change the penalty to 1.1 instead, so first move will be speed of normal, next will be faster.

**Comment by jeremygurr** [comment]
fixed.
