### ISSUE TITLE
message window is too small, and too many messages try and cram through

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#374]
These are two different problems but they are related. 

One is that six rows of message text is much too little to see what happens after a single turn, especially if you have many monsters on the screen or summons. I have to hit space so much to skip through "more" messages that I accidentally skip through critical things. That makes the game less fun than it should be, and terribly tedious. I actually disabled more message in my rc file previously, but that causes different problems. With a large browser window, I don't see why I shouldn't be able to configure the message window to go to 10 lines, instead of using the extra space to make the main game window huge.

The second related issue is I think the message window can be used more efficiently than it is. The first obvious thing to remove is the spell casting prompts. It's fine to see a single line in the message window saying "You cast fireball.", but the 3 lines required to ask you which spell to cast, and where to target, give no benefit whatsoever to leaving in the message window after you have cast the spell. If you look at the message log, you can see it has already been taken out. So why leave it in the message window then, and prevent me from seeing other important things going on, or force me to endlessly mash spacebar?

But there are other ways I think it could be more efficient. Maybe the left column holds details that don't force more messages, and the right column holds important summary lines, which are usually one line per turn, along the lines of "3 monsters did a total of 32 damage to you". You can still see all the details in the left column (or the message history) if you want to better understand how they did 32 damage to you, but in the 97% of the cases where you know exactly how it happened already, I think the summary will do fine.

**Comment by yrmvgh** [comment]
You wouldn't need to ask the player "which spell do you wish to cast" in the message window, if z\* or even Z\* was the default behaviour. I already use macros and/or LUA to make it so (there's an rcfile flag for a\* as the default).

Hell, prompts could appear at the very top of the game window, or the map, or in the sidebar in theory, but I'm assuming engine limitations prevent that.
