### ISSUE TITLE
Inconsistent armour egos

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#375]
Troll hide/armour and animal skins are special cased to never have armor egos, for some perfectly good reason that no one has explained to me? I can see the reason, to an extent, with the better dragon armours, but troll armour and animal skins aren't exactly game winners right now.

Also the archmagi ego only shows up on robes, but has a weird special rule that makes it spawn a lot more at lower depths (with a concordantly low enchantment bonus) and be exceedingly difficult to find the deeper you go.

I propose allowing archmagi to appear on ring mail at the very least, it's a classic "hybrid caster" armor type. Possibly we could allow it to appear on all non-plate armour.

I propose allowing troll armours and animal skins to have egos, but possibly to have their own alternate set of egos to choose from. Perhaps rF, rC, rN, rPoi, rCorr, Protection, +Str, +Dex, and +Regen. Weighted, of course, like existing egos are, so that crappier or more common egos are more likely to be chosen.

**Comment by jeremygurr** [comment]
I'd be okay with them being in the same pool as leather armours, and having the same brands as a result. I don't see any need for additional changes here at the moment though. It makes sense that arch magi would only be on robes. How many hybrid casters ever get to arch magi level?

**Comment by yrmvgh** [comment]
As far as I can tell here: https://github.com/jeremygurr/dcssca/blob/f98ccdca6350cca5b2503efb850ba63b605afc9a/crawl-ref/source/makeitem.cc#L836

leather armor is just in the "general" pool, it doesn't get anything different than chain, scale, etc. Only plate and robes are unique. Shall I put animal skins and troll flesh into the general pool? 

Game-fiction-wise, yeah how many hybrids do? In game though, it totally happens! You only need like 11 to 15 amour skill to cast quite comfortably in ringmail. :stuck_out_tongue: You can get any two skills to max (or high 20s at least) in 3 rune, if you don't have negative apts for it and you do orc / depths / elf in addition to your rune branches.

**Comment by jeremygurr** [comment]
We don't want pure casters to lose their distinction. A pure caster should play and feel significantly different than a hybrid. And the archmage brand being limited to robes is part of what creates that distinction. If anything, we need more of this distinction here, not less.

**Comment by yrmvgh** [comment]
Got it!

**Comment by yrmvgh** [comment]
Semi-relatedly, leaving an issue open for about a day after we fix something or make a change, might be good for the situations that cause sandman / gorgo to end up having questions in IRC about how power mode or berserk currently work.

Then again, people can read the titles of the [closed Pull Requests](https://github.com/jeremygurr/dcssca/pulls?q=is%3Apr+is%3Aclosed), you usually label them pretty clearly and they serve as a pretty handy "change log".

Might be easy to forget to close an issue a day later, after the coding is already complete.

**Comment by jeremygurr** [comment]
Yeah you are right. It should ideally be closed by those who created it, or at least after a few days have passed. I must resist the temptation...

**Comment by yrmvgh** [comment]
It's fun to say "done" and see the number go down.

**Comment by Sandman25DCSS** [comment]
I don't mind closing my issues, finally I learned that I can "Watch" the whole fork so I get lots of emails with all changes.

**Comment by yrmvgh** [comment]
Hopefully changing egos around doesn't cause any bugs!
