### ISSUE TITLE
Make Sif Muna fun

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#378]
I think Sif Muna should be as good of a choice as any of the others. If people are completely avoiding her because of tedium or inferiority, that's a problem. 

It sounds like the biggest issues are around her channeling ability. Also, she has no significant piety based abilities at all. So let's throw out more ideas until we find the magic combination that makes her fun, but not OP. 

Some initial thoughts:

(1) Make channeling a simple piety consuming action that fills the players magic pool. It should be expensive enough that it can't be used too often. This eliminates any tedium that channeling used to cause. The only thing I don't like about this is it feels like it steps a bit on Veh's toes, although that is no different than old channeling. But ideally the two would be a little more distinct IMO.

(2) Make channeling greatly increase mana regen temporarily, while consuming either stamina or piety.

(3) Make channeling a passive ability that reduces all spell costs by an amount related to invocations. Example spell costs for a level 9 spell:

Inv 0: 9
Inv 5: 7
Inv 10: 5.4
Inv 15: 4.2
Inv 20: 3.2
Inv 25: 2.5

Since they are fractional amounts, crawl will randomly round them, meaning that sometimes a level 1 spell will cost 0 magic to cast if the player has any invo. So heavily training invocation you can basically triple your effective magic pool for spells.

**Comment by yrmvgh** [comment]
Sorry but the title of this thread made me do this.

![Let's make Muna Sif again.](http://i.imgur.com/FDte9go.png)

**Comment by yrmvgh** [comment]
More on-topic: maybe some kind of "whenever you cast a spell, X happens". Players love procs! 
On successful spellcast: +1 (stacking) EV for 10 rounds
On successful spellcast: gain 33% discount (round down) on a spell you cast in the following turn

**Comment by Sandman25DCSS** [comment]
I think increasing MP regeneration is better than reducing spell costs because MP can be used for guardian spirit. So I like something like option 2 the most: active ability to increase MP regeneration for duration (duration depends on Invocation), it can be activated multiple times to increase MP regeneration even more (without increasing duration). It should not cost stamina/piety but when it ends a new status is displayed (not sure about the name) and player cannot activate MP regeneration unless he spends one turn to clear the status. I was trying to keep old power of Sif Muna, clearing the status is kind of eating a fruit and multiple increase of MP regeneration is for those characters who are pure summoners (fighting as FeSu on nightmare is a very bad idea) and don't have anything to do anyway. While most characters can just activate the ability once and join fighting.

**Comment by Sandman25DCSS** [comment]
Oops, my suggestion is bad, it makes optimal to retreat a bit, activate abilities and return to fight.

**Comment by Sandman25DCSS** [comment]
So now I think that third option is the best, but with more reasonable numbers, even at Invo 27 current Sif Muna cannot give more than 9 MP (d(2+[Invocations/4]) MP) and it costs 1 turn. Making level 9 spells cost 2.5 MP would allow spamming the spell indefinitely (with high max MP and as Ds with corresponding mutation you can get more than 2.5 MP per turn) and without wasting time on channeling.

**Comment by jeremygurr** [comment]
Ok I had each invo level cut spell cost by 5% before, now let's look at 3%:

Inv 0: 9
Inv 5: 7.7
Inv 10: 6.6
Inv 15: 5.7
Inv 20: 4.9
Inv 25: 4.2
Inv 27: 4.0

What I definitely want here is for inv 5 and 10 to be meaningful to a player. A player shouldn't have to have 27 inv to have a noticeable benefit. And I think what we have here _barely_ meets that, since at level 5, most of the time a level 9 spell will cost one point less, occasionally 2 points less. Almost not noticeable in practice. But then at 10 you are saving 2.4 points on average, which I think will start to make a real difference, and if you heavily focus on invocations, you can get it down to half price for all spells around level 23. 

Another example: at level 10 inv, a level 4 spell would cost 2.9, and at level 20 inv it would cost 2.2.

I still really want a piety burning ability for Sif, a powerful ability that would be expensive and rarely used, but would really help Sif to stand out, or at least stand closer to some of the others. What if the book gifts went away and instead an ability to summon a random book could be given early on (at 2\* for example). So a player could choose to conserve their piety and so gain the perks of spell cost savings and miscast protection earlier, or they could give those up in exchange for getting more books earlier, or they could balance the two. More meaningful choice. 

This new idea for channeling replacement is actually way powerful if a player is willing to pay the price for it, since it's always on, never costs anything beyond the initial investment of invocations training, doesn't take any time to use, etc. This might be enough to put Sif squarely in competition with Veh for optimal choice.

**Comment by Sandman25DCSS** [comment]
In current crawl if player has less than 10 Invo with Sif Muna while casting level 9 spells, then it is a very bad player. 
failure = 40 - piety/20 - floor(Invocations skill \* 2.0)
Even at piety 200 it means you have 30% failure at Invo 0 and 10% failure at Invo 10. I train Invo to 7+ very early (before finishing Lair).

**Comment by G0rg0** [comment]
Reduced MP cost with invo: 
I like it and it can be tweaked if it's too OP/weak. Is this also tied to piety or just straight invo?

The idea of actively burning piety for books:
Awesome! What if it also had a small chance to drop a magic related manual? Only spellcasting or one of the various other schools, never a non-magic manual. Perhaps weighted toward the schools you are training.

I also still like my idea for the anti-Trog/spellcaster berserk: 
Burn piety and for a few turns you have clarity, are able to cast with no MP cost, zero failure etc., but then suffer a significant malus. Something like confusion / increased spell failure / zero MP regen etc.

**Comment by jeremygurr** [comment]
Yeah I definitely like the idea of dropping manuals. Should only be at the highest piety levels though, and would be more likely after the player has received most of the spellbooks already.

The spellcaster berserk is definitely interesting, and we could experiment with it, it just seems likely to push Sif way over the top, to where Veh would never be chosen. 

For the new channeling, I was thinking it requires 1\* of piety to kick in (like old channeling?) but the effect is purely based on invo, for simplicity. But there are already other significant effects based on higher piety levels, so that still has significance.

**Comment by jeremygurr** [comment]
On second thought, I'm not so sure about the manual gifting thing. That could break important other aspects I'm trying to maintain.

**Comment by G0rg0** [comment]
I was thinking the manual drops would be low, like 90% chance of spellbook, but occasionally it'd gift a manual instead.

The spellcaster berserk would have to be a really serious piety hit so it's not something that would get abused but could get pulled out in a real emergency.

**Comment by jeremygurr** [comment]
The problem is that even if you get one manual, however unlikely it is, it is a game changer. I'd like to mostly provide manuals for late game super-rewards, or uber rare treasure finds (as they are now). That keeps them exciting, and doesn't wash out skill gains.

I like the idea of a high piety cost boosted mode for Sif. I think we should try it out. It might tip the scales too much away from Veh, in which case we'd need to adjust it, but it's worth experimenting with I think.

So what I'm thinking is maybe 50 piety (Which is higher than any piety cost I know of), giving maybe 20 - 40 turns or so of unbridled spellcasting fury (based on invo again?). Basically spell and stamina costs drop to 0 for the duration, but afterwards the caster is burnt out and can't cast any spell for 20 turns or so while they recover.

**Comment by yrmvgh** [comment]
Tying it to invo is definitely an important part of the package. With something like that big spell fury, I could see Sif shaping up into the "high investment high reward" caster god and Veh being the "low effort straightforward" caster god.

**Comment by jeremygurr** [comment]
Done. Open up an issue if you have anything further to discuss about this or if you've come across bugs in the implementation
