### ISSUE TITLE
Error message when entering Depths 1

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#38]
"More spells requested for fixed level (8) randart spellbook than there are valid spells.
 Discarded 0 spells due to being uncastable and 0 spells due to being disliked by No God."

**Comment by jeremygurr** [comment]
This is an issue from mainstream crawl, but just a warning that the game normally silently deals with, but since I have debugging on for this server it shows up. I'll turn off the debugging flag for the next build, then things like this won't pop up.

**Comment by Sandman25DCSS** [comment]
Ok, thank you
