### ISSUE TITLE
Your form is beginning to unravel.

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#395]
I got message "Your form is beginning to unravel."
I don't have any transmutation spells, just Delayed Fireball.

`
rFire  + + .      SeeInvis .    a - staff of fire {rF+ !a}
rCold  + . .      Gourm    .    k - +3 leather armour {MR+}
rNeg   . . .      Faith    .    (no shield)
rPois  .          Spirit   .    p - +2 hat {Int+3}
rElec  .          Dismiss  .    h - +2 cloak {MR+}
rCorr  .          Reflect  .    M - +1 pair of gloves of a volcano {Int+2 Dex+2}
SustAt .          Harm     .    x - +2 pair of boots {rF+}
MR     +++..                    J - amulet of magic regeneration
Stlth  ++........               c - ring of protection from cold {rC+, !d}
                                G - +2 ring of intelligence

@: delayed fireball, repel missiles, slow, extremely resistant to hostile
enchantments, unstealthy
A: clever 1
a: Renounce Religion, Release Delayed Fireball
}: 1/15 runes: gossamer`

**Comment by Sandman25DCSS** [comment]
Later I got `You can't maintain your form for much longer!`

**Comment by jeremygurr** [comment]
I believe I fixed this already. Maybe if you can untransform it will clear out the incorrect state.
