### ISSUE TITLE
Transformation renew too fast

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#404]
It looks like Transmutation spells are cast next turn when no hostile monsters in view. I think it should be increased to at least 2 turns, my Formicid creates a kill hole and can sustain the form almost indefinitely because it happens often that monsters don't come into view every turn even if they are adjacent to each other. I mean I have exactly one turn without monsters in view pretty often.

**Comment by jeremygurr** [comment]
It would have to be 2 turns even when transforming for the first time. Is that what you want? I can also just not allow extending it by recasting.

**Comment by Sandman25DCSS** [comment]
No, I meant it is automatically recast every turn without spending mana. Or am I wrong and mana is spent? Then it is ok.

**Comment by jeremygurr** [comment]
Oh I see what you mean. It's supposed to require 5 turns of peace before recharging the form. That would be a bug then.

**Comment by Sandman25DCSS** [comment]
Another issue is that Blade Hands sometimes expires very fast, it gives a warning `Your form is beginning to unravel` literally after 2 attacks. I have 26% failure chance for it when under the spell, this is quite respectable for Vaults 2 (Int 16, ring mail, Transmutations 18.7, Spellcasting 11.7). Can we add some minimal number of attacks depending on spell power maybe?

**Comment by Sandman25DCSS** [comment]
I can keep Dragon Form much longer (14%) which is weird provided it is much less castable than Blade Hands (3%).

**Comment by jeremygurr** [comment]
The minimum for any form or failure rate is 5 attacks. I can increase that minimum if you feel we need that. The first warning is meant to give you a feel for how fast it is decaying, so if the first warning is at 2 attacks, that tells you you probably are only going to have 5-6 attacks. 

Yeah dragon form probably doesn't hurt your failure rate as much in the form.

**Comment by jeremygurr** [comment]
I guess I can do minimum of 5 attacks + spellpower boosting it up to a minimum of 15? So spellpower could somewhat compensate for failure rate. 

When I'm struggling with blade hands I fight in careful mode, which makes it last much longer, at least until I can get that failure rate down.

**Comment by jeremygurr** [comment]
Oops, this was actually a bug. You were actually getting the results of a 50% failure rate. 25% will last much longer after I get this fix deployed. Give me 5 minutes...

**Comment by Sandman25DCSS** [comment]
Ok, great. Thank you. I almost got Transmutations higher than UC (20.0 vs 20.2) :)

**Comment by jeremygurr** [comment]
ok it's deployed.

**Comment by Sandman25DCSS** [comment]
Seems to ok fine now, thank you
