### ISSUE TITLE
Dragon Form spends stamina

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#405]
Dragon Form does not provide "Stop flying" ability and while flying wastes stamina I am always at 0-1 stamina. Is it expected?

**Comment by jeremygurr** [comment]
No forced flying situations shouldn't cost stamina. I just have to make exceptions for each form that does it, because the code isn't centralized in the place yet.

**Comment by Sandman25DCSS** [comment]
Ok, thank you.

**Comment by jeremygurr** [comment]
Fixed.
