### ISSUE TITLE
"FOO is lethally poisoned!"

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#407]
When the player is lethally poisoned, you can see it on your HP bar. Would it be possible to show that yellow segment on monster HP bars, or to get a message when you seem to have lethally poisoned a monster? (though it will be inaccureat when the monster has high regen or the like, but it'd still be better than the guess-and-pray-and-kite we have now)

**Comment by jeremygurr** [comment]
Probably, but I'm not sure how to do that. Difficulty probably exceeds the value in this case, unless someone else wants to do it or I come across an easy way.

**Comment by Sandman25DCSS** [comment]
I agree, I think it will be too hard to implement. It was (or actually is) hard for player too, there are still bugs when the prognosis is wrong.
