### ISSUE TITLE
permanent flight

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#408]
Either creatures that can turn on and off permanent flight have a reason to turn it off, or the option to turn it off is taken away. Seems like flight should give evasion and speed boost, but should cost stamina. Or else it should give neither and only give the advantage of being able to travel over any surface, but not cost any stamina and not have the option to stop flying.

**Comment by G0rg0** [comment]
I prefer the latter, but you could also give a slightly increased boost if you are hasted or swift while flying. So you'd be burning stamina in those cases, but also moving faster than if you were _just_ hasted or swift.

**Comment by Sandman25DCSS** [comment]
By the way Tengu is much harder than in vanilla crawl (cannot fly permanently from XL14, lacks both rings). I hope it is intended, not a side effect ;)

**Comment by yrmvgh** [comment]
Flight could cut your stamina regen rate, or increase your stamina costs, instead of directly burning stamina itself.

**Comment by jeremygurr** [comment]
Tengu can fly permanently. I'm playing one now that's quite powerful. They are harder in some ways, because of lack of rings, but I made up for that partially by giving them good dna and absorb enchantments. 

The good dna makes them more likely to get good mutations than bad, so taking advantage of every source of mutation gives them a fair chance at getting resistances that their rings would have otherwise provided, at the risk of picking up the occasional bad mut. 

The absorb enchantments mutation gives them a chance of an enchantment used against them failing and giving them mp instead. This somewhat compensates for lack of MR that rings would otherwise provide. 

That being said, after playing it for a while, I want a better solution for flight. Cutting regen rate or increasing costs would help, but then it becomes something else to manage after every battle. You always want to turn it on, then off, then on. I'm thinking we should just cut the buffs of flight, and leave it with the advantage of being able to move over any terrain, without any cost, and take away the option to stop it for tengu, so it's just like Dj. One less thing to manage.

**Comment by Sandman25DCSS** [comment]
Oh, I didn't play Tengu with the stamina so I assumed flight drains stamina since it can be turned off. Yes, I don't think Flight is that good except for Tengu: it is recommended to NOT be flying in Depths and onward because of Spriggan Air Mages, Titans, Blizzard Demons etc.

**Comment by yrmvgh** [comment]
Airstrike should probably deal less bonus damage to flyers, or none at all, if it's just a utility mode that doesn't get you much more than you could get with Apportation / flight pots.

**Comment by Sandman25DCSS** [comment]
I find Airstrike's extra damage interesting in water branches, it makes you choose if you want to risk getting extra damage or being slow/inaccurate in water.

**Comment by yrmvgh** [comment]
Tengu could wear rings on their legs/talons pretty easily.

![bird tags](http://i.imgur.com/5IIIUAm.jpg)

Once you bunch up your talons and push them through the ring, it'll just sit on your talons, loosely jangling around your leg like a flapper's jewelry, or these magical science tags depicted above.

**Comment by Sandman25DCSS** [comment]
Do you mean all rings on Tengu should become automatically cursed on equiping? :)

**Comment by jeremygurr** [comment]
I forgot about airstrike. This is a problem for Dj too, since they have no legs and so can't stop flying. I guess I'll leave the tengu's ability to stop flying, but remove the buffs and costs.

**Comment by Sandman25DCSS** [comment]
It will make Tengu the hardest species IMHO, not that I am complaining, just letting you know.

**Comment by jeremygurr** [comment]
I'm just going to leave Tengu flight as is for now. Maybe not ideal, but I don't have a better idea yet.
