### ISSUE TITLE
fix haste

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#411]
How should haste behave?

I think potions should be different than spells (for haste, berserk, invisibility, etc). Potions should not have any cost since they are only one time use. So a haste potion should just function for a limited time then stop like before. 

Some spells, however, should have a cost beyond just the mp cost. Haste is definitely one of them. 

Possibilities:

1) take a chunk of sp right at the beginning (maybe it costs half of your max sp), so that it can't be cast over and over, and so it has significant impact on other stamina actions. Effect stops after a certain amount of time. 

2) burn stamina over time while it is being used. Effect stops when stamina is gone, or manual stop.

3) freeze mp while it is being used. Manual stop.

4) works like transmutation, where it can stay on, but failure rate is checked on each action, so it needs to be occasionally recast. Purely based on success rate, so SE can take advantage of it. Manual stop, or fails when action happens.

I like #4 best at the moment. Realistically, is permanent haste all that different than vanilla late game haste where you can cast it whenever you want? Except it's less tedious to just have it there. Yes there is the difference of not losing that extra turn at the beginning of a battle, and that does make things slightly easier, but I think the convenience gain is worth it.

I think with #4, it should also lock up some MP. And I think transmutations should also. By itself it wouldn't have much impact. But if you have a lot of buffs on, it will greatly reduce what you can do magic-wise. So if you're transmuted, and hasted, and invisible, with ozu armour on, you shouldn't have much magic left for anything else.

**Comment by Sandman25DCSS** [comment]
5) Haste spell cannot be cast when there is any contamination. Stamina points are unchanged. Casting Haste automatically switches you to normal mode and you cannot switch to power/care/escape as long as haste is active. Now you cannot spam Haste even as Mummy or Ghoul who has lots of royal jellies or fruits

**Comment by Sandman25DCSS** [comment]
> Realistically, is permanent haste all that different than vanilla late game haste where you can cast it whenever you want

It is one of the problems in vanilla crawl, the whole extended is built around assumption that you can spam haste. Latest removal of rMut makes it even worse because you don't care about mutations anyway.

**Comment by Sandman25DCSS** [comment]
As a side effect, miscasting a spell makes you unable to cast Haste. Double fun if the miscast happened from attempt to cast Haste :) And it is good IMHO, currently there is no reason to train Charms after Haste is at 5-10%.

**Comment by jeremygurr** [comment]
It feels wrong that one spell would be required to beat extended game. I'd prefer removing haste altogether to the alternative of requiring haste to be castable to be able to beat extended. Ideally, haste would be one option, but there should be other viable options as well, equally as effective, some of which should not require any casting ability at all (trog users ought to be able to beat extended also). 

Definitely some work is required here. But it still seems best to standardize buffing spells around this model of recasting them only when they fail, and them locking up mp. If leaving haste on is too powerful, then it should have a higher cost or give a lower benefit (or both). But I think the game is better by removing things that need to be cast for every battle.

**Comment by Sandman25DCSS** [comment]
Yes, removing haste spell is fine with me.

**Comment by jeremygurr** [comment]
I think you convinced me. I will remove the haste spell. But I would like to replace it with something, since it's a major spell of the charms school. 

I want something different than what currently exists in the game. I'll create an issue.

**Comment by Sandman25DCSS** [comment]
Well, my idea was to link it to contamination so it could still be cast once in several hundreds/thousands turns. Though yes, as far as I remember I was suggesting to remove haste on crawl tavern.

If you want some new Charms spell, maybe it could decrease stamina costs for some time, then it would be useful for both escaping and fighting without being OP or spammable.

**Comment by yrmvgh** [comment]
A mutual-direction Spirit Shield type thing? Reduce stamina costs by (amount based on spellpower). While active, if you are out of stamina, stam costs are paid using half that much mp. If you're out of mana, pay mana costs using twice that much stamina. If you're out of both, maybe it even can tap into your hp.

**Comment by jeremygurr** [comment]
this is continued in two other issues now. No reason to keep this one around.
