### ISSUE TITLE
shorten pan

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#417]
What is causing pan to drag on? Does it need to be changed, or just shortened? Unfortunately I'm not very experienced with pan so I need the veterans here to chime in.

**Comment by jeremygurr** [comment]
Currently I'm thinking of a fixed 15 floors that the rune floors get randomly mixed into. Then you never have to go more than 15 floors to get all of the runes.

**Comment by Sandman25DCSS** [comment]
There is a chance to generate unique floor when entering a new pan floor so some unlucky players can get quite a lot of them before entering all 4 unique floors.
Yes, limiting total number of pan floors will fix it. Basically only N non-unique floors should be allowed, after that just unique floors are generated and exits to other pan floors on the last floor are replaced with exit to main dungeon

**Comment by jeremygurr** [comment]
Perfect. That should be simple enough. Now to find where that code is.

**Comment by jeremygurr** [comment]
Ok I didn't do exactly what I was saying, but I took an easier approach that should be pretty close. Basically, in the first 5 levels, it behaves as it did originally, having a low chance of finding rune floors. That chance increases at 10 and 15 significantly. By the time you are at 20, you will get all of the remaining rune floors without having to go further. 

I don't understand how the demonic rune works though. I'm not sure if it may force a player to go 20 more floors or not. The code isn't very clear here. If it is likely to appear in the first 20 floors, maybe we don't have to change anything else. Otherwise I need to figure out how that works.

**Comment by Sandman25DCSS** [comment]
Oops, I forgot about demonic rune. It can be generated many times, if player does not pick it up on previous floors. So I guess if player does not have demonic rune after those 20 floors + 4 unique, then there should be one of the following:
1) 20th floor must generate demonic rune and warn: "This is your last chance to pick up demonic rune"
2) After entering all 4 unique floors, there must be generated another pan floor with demonic rune and the above warning.

**Comment by jeremygurr** [comment]
It sounds like there's a pretty good chance of coming across demonic rune vaults within the first 20 floors? Much more likely than the others, or not? I can do the guarantee option but it is a lot more work, and I don't want to do it if there's an easier way to accomplish close to the same thing :)

**Comment by Sandman25DCSS** [comment]
Yes, probably we can just warn players when entering pan portal that they can get demonic rune on first 20 floors only

**Comment by jeremygurr** [comment]
I seem to be misunderstanding something here. If they didn't get it in the first 20 floors (however unlikely that may be), couldn't they just go down a few more floors until they do? I'm not actually capping pan to 20 floors, just guaranteeing the rune floors will at least happen in the first 25.

**Comment by Sandman25DCSS** [comment]
Oh, I missed it. Then yes, we don't need any warnings or other changes.

**Comment by G0rg0** [comment]
What about the special floors like holy and disco? Are those going to be guaranteed in the first 20?

**Comment by jeremygurr** [comment]
wasn't planning on it. You could always go deeper if you missed it though. They key here is for those who just want to get the runes and move on, they will no longer be required to pass through 40 floors (I know that isn't average, but it does happen, and even the average of 27 seems a bit high, especially when people are complaining about 8 levels of lair being too long).

**Comment by G0rg0** [comment]
Fair enough, it would be nice if they were guaranteed before 40-50 floors though. They are really fun! 

I guess holy isn't fun if you are an undead though.
