### ISSUE TITLE
should the healing wand delay be removed?

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#418]
Maybe this isn't needed anymore?

**Comment by yrmvgh** [comment]
Probably. That, or a warning when using it in view of monsters.

**Comment by Sandman25DCSS** [comment]
Yes, removing delay or a warning is basically required.
Does it heal the same amount as potion of heal wounds?
I like vanilla crawl healing, healing 25% HP makes nightmare too easy when you have 200+ HP in statue/dragon/tree form. Basically I don't see why Spriggan should get less HP from healing than Ogre, it's like making hard species harder and easy species easier.

**Comment by jeremygurr** [comment]
Wands heal based on evocations power. At about 50 evo, you get 100% healing. I guess I can cut that in half if you want. They heal a minimum of 20 points (like potions), so even for early game characters it is significant healing. 

Giving a fixed amount of health seems to me to strongly work against high hp characters, as opposed to it being more even. Case in point: a spriggan with 100 hp can deal with the same kind of encounter that would require an ogre at 200 hp to deal with. How do they do it? Magic protection, summoned meatshields, high evasion, whatever. But they do it. Which means they effectively take half as much damage in a given turn on average than the ogre. So giving them a fixed amount of hp for drinking a potion buys them twice as many survival turns as it does the ogre. An ogre may just buy 2 extra turns with a potion, but the spriggan would get 4 from the same potion. This makes things significantly easier for the spriggan. Now you can nerf other things about the spriggan to try and compensate for this, which is probably what vanilla crawl attempts to do, but this is impossible to perfectly balance because this gap increases as you get later in the game, since ogres hp increases at a faster rate than a spriggans, so what is an adequate nerf for beginning game becomes inadequate by late. What's worse is that spriggans tend to grow in power faster than ogres, at least during early and mid game, thus exaggerating that gap further.

On the other hand, by scaling according to their health, it is perfectly even throughout the game. The spriggan gets 3 more turns to survive after drinking the potion, as well as the ogre.

**Comment by Sandman25DCSS** [comment]
I disagree with your Sp vs Og analysis. 
In vanilla crawl Sp is easier than Og early game and deals with HP loss via escaping, late game Sp becomes much harder than Og (Og usually has much higher AC due to wearing dragon armour and huge HP due to HP bonus/penalty and HP/Fighting aptitude difference) so Sp needs every source of healing to survive unlucky rolls when EV fails.
In CA fork Sp is harder than Og basically always, at least on nightmare, because you just cannot run away from everything, eventually your stamina will be zero and you will have to fight.

HP bonus/penlaty is the most important thing in CA fork because speed becomes not that important IMHO.

**Comment by Sandman25DCSS** [comment]
Oh, I have never used wand of healing in fight so I didn't know it depends on Evo.

**Comment by jeremygurr** [comment]
It wasn't an analysis of whether Sp was easier or harder. Balancing problems between races are outside of the issue of fixed hp or scaling hp gain. 

Assuming 2 equally balanced races, one that has 1/2 of the hp of the other, both having an equally easy time of retrieving the orb with 3 runes, the one with 1/2 hp will get twice as many turns from a fixed healing potion than the other, even though in all other ways they are perfectly balanced. 

It doesn't make sense to change the entire mechanic of an item used by all species to attempt to cover up a lack of proper balancing for one. It just causes all of the others to become unbalanced. Would you say that a deep elf has a dramatically more difficult time winning a 3 rune game than an ogre? If not, then there is no need for potions to favor them. 

Now I can see how vanilla crawl has used fixed hp potions to deliberately favor weaker species as part of their balancing mechanic. But it is broken for the reasons I mentioned above, and goes against a major design goal I have of keeping items useful through end game. Maybe an expert player can squeek out a little use from them even in extended game, but that won't work here, because without level caps and with the addition of rune curses, as well as additional branches and runes to retrieve, there is much more extended game. Players will pass far beyond the point where a healing potion won't even buy them 1 extra turn for a teleport to kick in if the potions gave fixed hp. And just increasing the fixed amount makes early and mid game too easy.

**Comment by Sandman25DCSS** [comment]
I guess you missed my point. I am saying that species in CA cannot be balanced if they have different HP. Also I am saying that if species has more HP then it is more powerful than any other species which has lower HP. Basically that's the power of species:
Og/Tr > Na > Ce/DD/Mi/Ho/Dr > Hu > ... > Sp
The only exception is Fe because it has multiple lives.
That's why I think that healing percentage of HP is bad for game balance as it increases difference between species. Though probably this is what you want, I am not sure now.

**Comment by Sandman25DCSS** [comment]
Yes, Deep Elf has dramatically harder time winning than an Ogre assuming we are talking about average (all possible backgrounds instead of comparing DEFE to OgFE or DEFi to OgFi).

**Comment by Sandman25DCSS** [comment]
I think you are assuming that lower HP species have better defenses, this is not the case. Just look at FeBe (no transmutations of course so it has AC 3 , EV 40+ and -4 HP penalty) and NaFi of Chei (+2 HP bonus, naga barding, crystal plate armour, AC 70+, EV 30+, SH 20+) if you disagree

**Comment by Sandman25DCSS** [comment]
> And just increasing the fixed amount makes early and mid game too easy. 

This is what CA did IMHO. In vanilla crawl it is `9 + 3d28/3 HP (23 on average)`, so you can be unlucky and get 10 HP. Max healing is 37 if you're very lucky.
In CA it's always at least 20 HP and later you can heal 60+ HP even on nightmare.

**Comment by jeremygurr** [comment]
yes but I made early, mid, and late game easier equally :). 

I don't have a problem lowering the minimum hp given by a potion if that's what you prefer. We could even make the minimum based on difficulty. Standard could have a minimum of 20, challenge 10, nightmare 5.

**Comment by Sandman25DCSS** [comment]
I would prefer to have  `9 + 3d28/3 HP (23 on average)` on challenging and `9 + 3d28/3 HP (23 on average)` x 1.5 on standard and `9 + 3d28/3 HP (23 on average)` x 2/3 on nightmare, it would be consistent with HP increase

**Comment by Sandman25DCSS** [comment]
Currently rune curses' difficulty is determined by number of potions of heal wounds in inventory. It feels fine as long as you have one. I suspect Gozag can be one of the best gods for extended now.

**Comment by jeremygurr** [comment]
No I'm not talking about all possible backgrounds for DE, I'm talking about optimal background of DE vs optimal background of Og.

**Comment by jeremygurr** [comment]
whether rune curses were there or not, having more healing potions would have a big impact on how easy any part of the game is.

**Comment by jeremygurr** [comment]
I'm not making any assumptions about defenses, only that if character A has the same amount of difficulty winning the game as character B, and character A has half the health, then character A by definition receives half as much damage per turn on average as character B. Doesn't really matter exactly _how_ they manage to avoid half the damage.

**Comment by jeremygurr** [comment]
I guess I'm ok with making hp gain fixed for nightmare mode. 

Done. You now have vanilla wand / potion healing. I didn't make it any harder than vanilla, because I figure things probably are hard enough as is. But if you really want to make it 2/3 of the amount of vanilla, tell me and I'll change it.

**Comment by jeremygurr** [comment]
Oh and the healing wand now takes the same time all other wands do.

**Comment by Sandman25DCSS** [comment]
Optimal background for Og (Be) is much easier than any background for DE.

**Comment by Sandman25DCSS** [comment]
As you told before potions of heal wounds were too weak late game so difficulty was not determined by number of heal wounds.

**Comment by Sandman25DCSS** [comment]
> only that if character A has the same amount of difficulty winning the game as character B, and character A has half the health, then character A by definition receives half as much damage per turn on average as character B

and I am saying that such situation is impossible in CA fork. If character A has the same amount of difficulty winning the game as character B, then they have about the same HP.

**Comment by Sandman25DCSS** [comment]
Thank you for the change!
