### ISSUE TITLE
contamination

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#419]
Level 9 damage spells feel a little OP to me still. In elf I could pull out a tornado for every battle if I wanted. Which was fun to a degree, but feels like it needs a little more of a limitation. I want it to be devastatingly powerful, but I shouldn't be able to safely use it in every encounter. 

The contamination mechanic I think has some potential here. Maybe I'm just too inexperienced, but it never played a significant role for me in vanilla crawl, and it certainly isn't here. But maybe that can be changed.

I like the idea of contamination being somewhat of a long term resource / cost. I don't want it to be as long term as the food clock was, but not as short term as something that can just be recharged after every battle. And maybe a cancellation potion may be used to cancel it out in an emergency. I also like the idea of being able to push things in an emergency, pulling off another firestorm or two, even if heavily contaminated, at the risk of some ugly mutations or other miscast effects. 

So what if contamination built up based on spell power, probably like it does already. Failures of course may add 3x the contamination as casting the spell successfully, so if you are frequently attempting a 50% fail rate spell, even under Sif miscast protection, you will have consequences, and greatly limit how many of these you can pull off in a given time. Okay this probably doesn't sound any different yet. But here's the catch: contamination diminishes by experience, not by time. It should be calibrated so that contamination caused by lower level or easy to cast mid level spells would easily be wiped out through natural experience gain, so that you never enter a severely contaminated state. But even if you can cast level 9 spells well (1% failrate), there should be a little more contamination being added then is naturally removed by experience, forcing the player to once in a while choose a different tactic than just spamming a level 9.  

Getting this balanced right will be tricky. But I think it will add needed dimension here.

**Comment by jeremygurr** [comment]
As Sandman had originally suggested, if haste was linked to contamination the right way, then it would be a lot more interesting. Maybe we can bring haste back after making these changes?

**Comment by jeremygurr** [comment]
If this were implemented, we'd probably want to bring the Dj contamination bar back. Right under the mp and temperature bar, we'd have yet another bar. It does add to the clutter and makes it harder to see important things, but if we color it right maybe it will be worth the cost. Spellcasters would definitely want to keep an eye on their contamination levels.

**Comment by Sandman25DCSS** [comment]
I wouldn't like any changes to level 9 spells, it's like making melee character be unable to use triple sword after using it a couple of times. That's the main feature of level 9 spells, they are extremely expensive and are not necessary, they would become almost useless if cannot be spammed. Actually going for level 9 spells in 3 rune game is a very bad idea for most characters. I bet you were a pure caster DE/Te/HE of Vehumet or Sif Muna if you were able to cast Tornado before entering Vaults.

**Comment by jeremygurr** [comment]
Well keep in mind I'm playing standard mode (with boosted exp gain), with a tengu (+4 air), and often use careful mode to achieve 20% fail rate with Sif removing miscast effects. So definitely feeling the need for making this situation more interesting :)

Really? I thought you would like the contamination idea. The triple sword situation seems a bit different since you can't take out 10 bad guys at once, like I'm often doing with tornado. Seems like it would be more interesting to force a little more diversification here. But maybe there's another way. 

I could play on challenge mode of course, but I think that would just make this same situation happen, only later in the game. I'd still get to the point of spamming tornado everywhere, with no real cost. I have plenty of mp, and can recharge any resource I spend between battles.

**Comment by Sandman25DCSS** [comment]
Well, you played on standard and then are complaining about too easy, switching to challenging seems reasonable indeed. My DEFE of Vehumet started casting Fire Storm at XL 24, for example.
Yes, I believe care mode is OP with regards to Tornado which cannot be spammed anyway. But it is a reason to nerf care mode, not Tornado.

Axes allow to hit 6 monsters simultaneously, do you want to make them contaminate player too? ;) Honestly axes are more OP than Fire storm, I cannot imagine getting 12 runes during orb run as formicid with fire storm.

**Comment by Sandman25DCSS** [comment]
Joking about axes of course, they are fine as are.

**Comment by jeremygurr** [comment]
I see a pretty big difference there. Axes force the player to get right up against several monsters, allowing all to pound on them while they are attacking. And of course the damage is only to the 8 adjacent spaces. 

With a couple casts of tornado a player can clear all LOS (over 200 spaces being attacked if I remember right), often well outside of melee range, or maybe at most having one or two hitting them. Much lower risk, and much wider area of effect. 

I'd rather the level 9s be more powerful but cast less often to make room for other strategies and spells. Seems like the level 4-6 spells should be the spammable attack spells, and the level 8 and 9 should be emergency or super power attacks used much more rarely. Would this be that bad of a thing? 

Even berserk is limited to one use in most battles. Finesse has a high piety cost keeping players from just endlessly spamming it. Hero can be used often, but even then it's using a resource that can't be recovered with simple resting. 

Axes are definitely powerful but they put the player at greater risk than any other attack method, which I think somewhat balances it. Of course if axes _were_ the clear best choice in all cases for a melee fighter, then some adjustments would be needed. 

It might be sufficient to only add contamination on miscast (ignoring sif protection of course). So for spells that never fail, there is no long term cost at all. But it would still limit excessive use of level 9s. 

The problem can be solved in many different ways, but I want the one that makes the game most interesting and fun. In this case, I have a bunch of spells, but I'm pretty much just using tornado. That's much less interesting to me than the proposal here, which would have me using the other spells most of the time, and only occasionally throwing in a tornado, which would have devestating effect.

**Comment by Sandman25DCSS** [comment]
Axes allow you to hit all monsters every turn, usually at 0.6-0.7 turn per attack and it can be improved with haste/finesse. If the axe is something like Executioner's Axe of  Holy Weapon (the capital letters just show you how much I respect the weapon:-)) you can one-shot most monsters in extended. Compare to Tornado which cannot kill most monsters (I am speaking about adjacent ones here) even in two turns, has a cooldown, makes you flying (it is bad, remember?) and takes much time to even start damaging monsters in the outer tiles. Also Executioner's Axe is not stopped by silence, bad terrain (you know tornado barely does anything in corridors, right?) or Sap status.

There are many level 8 emergency spells (Death's Door, Borg. Revivification, Controlled Blink, Necromutation, even Discord sometimes). Do you really want all high level spells be emergency ones?

I wouldn't like if I could use Exec. Axe just every 4th attack and had to use War Axe for other 3 attacks(or even switch to Quickblade to save ability to use any axes later). Training magic schools for level 9 spells does almost nothing for level 6 spells due to spell power stepdown, 10%-15% damage increase is not important, it's like training Polearms to 20+ when you use Demon Trident and shield. Seems useful but usually you are better training something else.

Also please read https://crawl.develz.org/tavern/viewtopic.php?f=5&t=19554 :)

So I don't see any problem to solve here.
