### ISSUE TITLE
Cannot load game

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#42]
I cannot load my previous Ogre game, it says "Loading" and then goes back to lobby without printing anything.

**Comment by Sandman25DCSS** [comment]
Oh, it is not related to the old game. I tried playing with new account, got the same problem.

**Comment by Sandman25DCSS** [comment]
And I had to register as Sandman25 again, login failed otherwise.

**Comment by jeremygurr** [comment]
Should work now
