### ISSUE TITLE
MP as a spell limiter

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#421]
We've discussed this a few times. The idea of MP being the only spell limiter is appealing in many ways, but I don't think it works as it currently exists. 

I removed spell caps because I want a spell like magic missile or even ensorcelled hibernation to still be useful late game. However, even though they grow in power, the cost doesn't grow. In fact, if you factor in magic pools increasing as players gain levels, the cost really goes down. So you end up with this powerful spell that costs effectively nothing. 

Yes I know some of you will say, just put the cap back then. But that doesn't get me closer to my objective of making all items/spells/abilities useful in late game. So, no that isn't an acceptable solution unless you can find another way to keep the spell viable late game :P

No that would just cover up a deeper problem. The real problem is being stuck to having spells cost their spell level. 3 level 1 spells often is usually much better than 1 level 3, because of the cost difference. And level 9 spells don't cost anywhere near enough for late game magic pools to constrain them in a significant way. Yeah I know things are a lot more constrained in nightmare mode, but my objective is to have all 3 difficulty modes balanced and fun.

Maybe this is more of a standard mode problem, and I guess I could just fix it there, but does it really make sense for something to get significantly easier as you _increase_ the difficulty level? That would be weird at best :)

Anyway, my proposal is to fully decouple mp cost from spell level. Spell level will still restrict spell memorization, and affect failure rate. 

But the mp cost either needs to increase with power (the simpler solution), or provide a way for the player to control how much power is being provided to the spell. 
For example a late game magic missile would cost 5 mp each. A late game level 9 spell should cost maybe 30. Then mp becomes a real limiting factor.

**Comment by Sandman25DCSS** [comment]
> But that doesn't get me closer to my objective of making all items/spells/abilities useful in late game

This is wrong premise I believe. Do you want to make players use +0 mace of nothing which they started the game with when they already have +9 demon whip of electro? Why spells should be different here?

So although I found no spell cap fun, it is still broken. Magic dart should not deal 24 damage like +0 mace cannot deal 24 damage

**Comment by Sandman25DCSS** [comment]
Also yes, please start playing on challenge mode or switch to other  (more difficult) combos. For example, I am playing FoTm on challenging because I couldn't start it on nightmare, all 5 attempts died early game

**Comment by Sandman25DCSS** [comment]
I mean I didn't find MP limitless even with DE racial bonus and high spellcasting.

**Comment by jeremygurr** [comment]
It is true that with weapons, weaker ones are intended to be replaced with stronger kinds found later.

But consider this: a melee player also has potions and scrolls and wands, and even other spells that they use from time to time to enhance their battles. They don't just get one wand that's superior to all of the others and throw away the rest. Most wands have value even late into the game. 

It wouldn't make the game more fun to have a Confusion 1, Confusion 2, and Confusion 3 wand. One confusion wand is sufficient. I like carrying all of the wands I find around. There is a place for all of them in one situation or another. Should we make power caps on wands to force the player to advance to a better wand? Would that make the game more fun? I don't think so. 

The same applies to scrolls and potions. Vanilla crawl has done a great job of achieving this ideal of items that keep their value through the game for almost all of these consumable items. 

As far as weapons, it wouldn't be the worst thing in the world to follow the same pattern, and just have one kind of short sword, one kind of long sword, one kind of axe, etc, and just the basic properties vary between weapons. I don't think the extra complexity of different weapon subtypes is necessary. You do lose a little flavor, but you get simplicity in return. You can maintain just as much variety in the basic properties of the weapon as weapons do now that have multiple sub-types.

You say magic dart should not deal 24 damage, because +0 mace can't. However,
- you can enchant the mace to permanently increase damage and accuracy (can't do that to spells)
- you can brand it to permanently increase damage or speed. Also something you can't do to a spell. 
- you can continue to train your skills to boost the damage and speed.
- you can add stat points to strength to increase damage with that weapon
- you can add stat points to dex to increase accuracy with that weapon

Is there a damage cap on maces? If not, then why should there be a damage cap on spells. If it was a good thing to have a damage cap on spells, why not a good thing to have a damage cap on a weapon?

Also, even a level 1 spell costs something each time you use it, whereas using a mace costs nothing (should probably cost stamina if we wanted to make them even, which we don't necessarily want, but it's an interesting thought). 

FYI: a mace +0 against an ogre, with 40 str, 25 maces, 25 fighting, does a max of 58 damage, but typical hits are well into the 20s, from my quick testing. Not all that different than a magic missile with high conjurations, spellcasting, and int. 

As far as switching difficulty modes, _someone_ needs to test standard mode. I seem to have plenty of people who want to test challenge and nightmare modes, and give me good feedback on issues there. Besides, skill-wise I'm probably halfway between standard and challenge. My intent is to have all of the difficulty modes fun, not for everyone, but for someone. And at the moment, I think I'm the only one in this group that can even come close to acting and thinking like a beginner player, since I'm only a little past that stage myself.

**Comment by Sandman25DCSS** [comment]
> Is there a damage cap on maces?

That's because melee and spells have different formulae. For melee basic damage is extremely important, it is multiplied by fighting/weapon skill modifiers and then brand modifier is used. While for spells we have something like `1d(3+Power/5)` (magic dart) and `2d(4+Power/10)` (throw frost) as you can see we basically have power/5+N in both cases so spell power limit was very important factor (25 vs 50), otherwise we just always use magic dart since it deals the same damage for half price, requires one school only, never misses, does not care about rC+ and has large range.

> As far as switching difficulty modes, someone needs to test standard mode

I did win [DDFi of Makh](http://crawl.homedns.org/morgue/Sandman25/morgue-Sandman25-20160426-032919.txt) with 15 runes and 1.02 rune modifier, it was easy as expected, I used just 1 potion of heal wound and even that wasn't necessary.
`B - 19 potions of heal wounds {!q}`

**Comment by jeremygurr** [comment]
Done.
