### ISSUE TITLE
priorities

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#422]
Although I can't promise anything, I would like to know what everyone's "top 3-5 things they'd like to see worked on soon" are.

**Comment by Sandman25DCSS** [comment]
Well, I am fine with game as is. Rune curse would be probably the most interesting for me but it's still not completely clear what to do as I far as I know. 
I disagree with some already implemented things but I don't feel that I am missing something. But here is a list of things which would greatly reduce fun for me if implemented:
1) Changing level 9 spells to be non-spamable (contamination or always spending stamina even in normal mode)
2) Making nightmare mode easier just to make it consistent with standard mode changes (like healing % of max HP)

**Comment by jeremygurr** [comment]
Also list the top 3 things you really don't like. Not minor annoyances, but major pain points. If there's enough consensus, and it's not something I really want, then I'll remove it.

**Comment by jeremygurr** [comment]
What remains for rune curse work is to get the new branch layout in place (complete with 20 runes) (already coded, just needs to be tested and debugged), add the rune specific curses to each rune, and add the perk for each rune. I'll probably just start with the easiest 4 runes, and we can try that out. If we really like how it plays, I'll do a few more, until all 20 are complete. I plan on working on this after the wiki is fully off the ground, so I will probably have the first few runes ready in the next week or so.

**Comment by Sandman25DCSS** [comment]
Major annoyances:
1) Healing % max HP
2) Care mode boosting spell failure (Tornado, Necromutation, CBlink)
3) Power mode spending just a bit of stamina for melee (almost unlimited use of power mode for Naga and characters of Chei, compare to casters who spend much more stamina, especially with high level spells, I am not suggesting to change casters but make melee/ranged spend much more stamina instead)

**Comment by Sandman25DCSS** [comment]
I mean hitting 50 times with 33% more damage is not equivalent to running away during 50 turns or casting high level spell 5 times

**Comment by jeremygurr** [comment]
You do realize that healing is now exactly like vanilla for nightmare mode, right? Or did I not get that deployed? I think I did...

**Comment by jeremygurr** [comment]
Totally agree with point 3, hence the discussion in [issue 424](https://github.com/jeremygurr/dcssca/issues/424)

**Comment by Sandman25DCSS** [comment]
> You do realize that healing is now exactly like vanilla for nightmare mode, right? 

Apparently I don't :)

**Comment by jeremygurr** [comment]
Hehe, sorry I had explained that in another issue earlier and figured you would have read it by now, so I was surprised. Unless it didn't post correctly for some reason...

**Comment by jeremygurr** [comment]
If there is an issue on this list that you'd like to see done sooner, go ahead and add a comment so it gets bumped to the top. I'll work top to bottom.

**Comment by yrmvgh** [comment]
Even though they're kinda "background / UI" things, I think the inventory space and lack of chopping/eating provides a lot of reason for people to stick around. So in general I think anything that simplifies, streamlines, or cleans up the game is what I would consider "the priority".

**Comment by yrmvgh** [comment]
What about something like http://www.bay12forums.com/smf/eternal_voting.php ?

![](http://i.imgur.com/qYVMJpM.png)

**Comment by yrmvgh** [comment]
Re: the big keyboard layout revamp - some interesting thoughts in here, somewhat similar to Sand's point about how P is a shorter list than W+w+P. 
https://www.reddit.com/r/roguelikedev/comments/3cqsaq/faq_friday_16_ui_design/ct14vog

That said, every time I try to swap rings, I hit W first, for some reason. Yet I can usually remember to hit w for weapons. The unequip keys could certainly go, though.
