### ISSUE TITLE
class symmetry

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#424]
some of our discussions have sent my mind wandering down some interesting paths...

Don't take this too seriously, but for those who enjoy discussing all kinds of unconventional approaches, you may have fun with this. 

Current situation recap:
A melee player gets to attack as many times as they like in normal mode with no cost. In power mode, they boost their damage and burn sp. An attack has a chance to miss, based on weapon skill and dex.

A spellcaster burns through mp on every spell cast in normal mode. Then in power mode, they add sp costs to their price to boost their damage. They have additional hunger costs from the difficulty of a spell when operating in power mode, that may be reduced by increasing their int or spellcasting skills. An offense spell has a chance to fail when casting, subject to int and spell skill. After it is cast successfully, it has a chance to miss the target. So they get a double chance to miss, unlike melee players. 

This is not symmetric. It doesn't necessarily need to be, but I think it's fun to consider some symmetric alternatives.

(1) Each melee attack in normal mode costs stamina. Attacks in power mode cost 2x stamina. Higher fighting training reduces stamina cost per attack. Wielding heavier weapons increases stamina cost per swing. Being stronger decreases stamina cost per swing. When you are out of stamina, you can no longer attack until some stamina regenerates. Spellcasters would burn mp _instead_ of sp, in both normal and power modes. Of course power mode would cost 2x mp just like melee costs 2x sp for attacks in power mode. When spellcasters are out of mp, they can no longer cast spells.

(2) Melee attacks in normal mode are free. But also spells cast in normal mode are free! Melee attacks in power mode cost sp, as explained in #1, and spells cast in power mode cost mp. As above, costs for stamina are reduced by fighting skill and str, and cost for mp are reduced by training spellcasting and int.

The obvious argument against #1 is that it makes the game more complicated. If that puts the game in a worse position overall, then if we are being logically consistent, #2 would put the game in a better position overall, since it is the opposite. It applies the "good" of no cost attacks (simplicity) to the "bad" of mp based spells (complexity). 

The obvious argument against #2 is that it would seem to make magic users way overpowered, since they can cast high level spells all they want. But does it make melee players overpowered to be able to use their "high level" weapon every turn without any cost?

Both options are very unconventional for RPGs, and so probably provoke a "this is so unnatural" feeling in most readers (including me). But change is not bad in and of itself, and decisions based on "well this is just the way it's always been, and it's the way I'm used to", will not lead to the best game design, IMHO.

I'm looking for gaping holes in either of this logic... likely there are some...

**Comment by Sandman25DCSS** [comment]
I think 1st option is unplayable. Currently casters switch to melee/ranged when they are out of MP. If they can't switch because of stamina, they just retreat/teleport/pass turns. Melee characters would need to just retreat/teleport/pass turns too. 
I actually played pure caster Spriggan in vanilla crawl (no actions allowed except casting spells and moving), I wanted to kill myself during middle game, it was very annoying.

2nd option is playable, but as you told it will make casters OP. You can see it if playing Moon Troll of Chei like I did.

**Comment by Sandman25DCSS** [comment]
I would increase stamina cost for melee/ranged in power mode and would keep everything stamina-free in normal mode (spells still cost MP of course)

**Comment by jeremygurr** [comment]
Although I agree if casters were out of mp and sp they would have no fighting options, I'm not sure it would be a common problem if the whole proposal was implemented. In other words, casters _only_ use mp to fight, even in power mode. Not a drop of sp would be used. So they would have a full tank of sp if their mp ran out, unless they were trying to kite by switching in and out of escape mode, but that kind of gameplay should be punished anyway.

**Comment by jeremygurr** [comment]
Increasing stamina cost for melee in power mode is definitely a step in the right direction.

**Comment by Sandman25DCSS** [comment]
Specifically I'd like stamina points allow just a short power boost, something like 5-15 turns irrelevant of actions. It would help with quickblade vs darkmaul (or dragon form) difference, currently you can attack the same number of times with both.

**Comment by Sandman25DCSS** [comment]
> So they would have a full tank of sp if their mp ran out, unless they were trying to kite by switching in and out of escape mode, but that kind of gameplay should be punished anyway.

That would greatly encourage hybridization, probably it's ok.

**Comment by jeremygurr** [comment]
So making it based on time instead of action count, right?

**Comment by Sandman25DCSS** [comment]
Yes

**Comment by Sandman25DCSS** [comment]
Also it would be a great reason to use high level spells which should help improve situation with no spells cap.

**Comment by jeremygurr** [comment]
I have no problem with that. Only remaining issue is escape mode. Melee would be heavily penalized compared to spellcasters on trying to escape if escape required sp.

**Comment by Sandman25DCSS** [comment]
I mean casters use sp in power mode too like melee characters do. No sp costs in normal mode.

**Comment by jeremygurr** [comment]
That would be okay, but I'd still like to explore the sp only / mp only path a little further to see if it could be made viable. I think it has the potential to make life more interesting for both melee and spellcasters if done right.

**Comment by Sandman25DCSS** [comment]
Yes, we can try it and see what happens

**Comment by jeremygurr** [comment]
Concerning experiment #1 mentioned above: After thinking about it for a bit, I think I'm okay with the idea that escape mode uses stamina for each movement. So melee fighters will be using sp to fight, like spellcasters use mp to fight, so they will need to break away before they are out of sp if they want to escape safely. Spellcasters will have an easier time since they won't be using sp unless they are using a melee or ranged non-spell attack. But I think it's okay to give spellcasters a buff in this area. We are always talking about how much more difficult spellcasters are than melee fighters. Melee fighters are much more likely to not need to run away, so I think it balances out just fine. 

So to summaraize experiment #1:
normal mode:
movement is free
spellcasting costs mp
attacking costs sp

power mode:
movement is free
spellcasting costs 2x mp
attacking costs 2x sp

careful mode:
movement costs sp if there are monsters in LOS that haven't noticed you
spellcasting costs 2x mp
attacking costs 2x sp

escape mode:
movement costs sp
spellcasting costs 2x mp
attacking costs 2x sp

if you run out of sp, you can't attack any more, although you can move in modes where movement is free. If you run out of mp, you can't cast spells (obviously). Of course this favors hybrids pretty significantly, but I suppose that's better than the opposite. But I don't want to make things too hard for purists either.

**Comment by jeremygurr** [comment]
Of course if we were to implement #1 as described above, stamina pool size would be calibrated to give melee fighters plenty of stamina to fight, and have emergency sp to run, if they are fighting in normal mode. If they choose to fight in power mode, they might run low on sp, and limit their escape options. In other words, this change should not be very noticeable to a melee fighter compared to how things are now. Spellcasters, however, _would_ feel a major difference in either mode, since they won't be using stamina any more. Their mp usage will go up considerably for higher level spells, since spell hunger will now translate to greater mp usage. To make it work like stamina does, mp will be a fixed pool (doesn't increase with xl) of 100 (being higher or lower based on racial apt). So very low level spells will be able to be cast almost without limit, in the same way a fighter could attack repeatedly on normal mode with no real limit. Simple attacks / spells for both fighters and magic users may have such a low cost, that normal sp / mp regen keeps up with it, so that it effectively costs nothing.

**Comment by Sandman25DCSS** [comment]
I would prefer to calibrate stamina based on escape mode only. I mean if player has max stamina, they should be able to escape. If they decided to use care/power mode, they should no longer be able to escape as easily. This leads to many options:
1) Escape immediately
2) Try to fight in power/care mode and then either automatically switch to normal mode and continue fighting or just escape without using escape mode (teleport, blink, god abilities).
3) Try to fight in normal mode, see how it goes and then switch to option 1 or 2.

If we have melee always spend stamina and thus we increase stamina pool, then escaping immediately will be very easy, you might run through half level to stairs. And if player made a mistake and ran out of stamina completely and has no way to escape (Formicid and Vault Warden, for example, or just completely surrounded with monsters and -Tele status), then it will pass turns which is very annoying.

**Comment by G0rg0** [comment]
I think we should try it - it would certainly simplify things to and the amounts of SP/MP usage per attack and per step in escape mode could be easily tweaked to balance things. 

How about taking it further? Djinn already combined MP/HP into Essence. Why not combine SP/MP into "energy" or "vitality" or something. 

Swing a weapon? It burns energy. Cast a spell, run to escape? Same thing

**Comment by jeremygurr** [comment]
Done.
