### ISSUE TITLE
Healing potion bug

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#426]
Somehow I managed to start a game with "unknown" difficulty. This makes healing potions and cure potions heal for 0.

Maybe the game needs some default, fallback numbers for difficulty-related things. in case of bugged difficulty level. Or possibly a way for the game to detect that you're on an invalid difficulty setting, and re-ask or kick you into Challenge mode.

**Comment by jeremygurr** [comment]
fixed. Now it puts you in challenge mode if for some reason your difficulty wasn't set right. But we need to eventually track down how that happened, so if it happens again, keep your saved game and tell me the character, and I can download it and analyze.

**Comment by yrmvgh** [comment]
As best as I can recall, I was at the difficulty select screen and dealing with my cat, so most of the left side of the keyboard got pressed. I tried to replicate it again with another character, but no luck.
