### ISSUE TITLE
Display monster HP (either max or current)

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#430]
Now that we have rune curses, it is not quite obvious how much monsters differ depending on your rune count so even standard bad method  "die once to learn how tough the monster is" no longer works.
I suggest to display monster HP, either max or current. I did it in my mode and I cannot say that it was OP.

**Comment by Sandman25DCSS** [comment]
Of course if monster damage is changed by rune curses too, then we should display it too.
This one is inspired by death of my character who got 150+% of max damage from popcorn

**Comment by jeremygurr** [comment]
How would this work? Maybe:

A mummy walks into view. (32hp)
You pummel the mummy. (-20 = 12hp)
You slice the mummy. (-15 = 0hp)
The mummy dies. 
An orc comes into view. (15hp)
You slice the orc. (-5 = 10hp)
The orc drinks a potion. (+4 = 14hp)

I've really got to centralize this code. They have at least 100 places where this string is assembled... otherwise it would be a trivial change.

**Comment by Sandman25DCSS** [comment]
As far as I remember I implemented it lazy way: there is a function for monster which is called every time when monster loses HP so I changed code in just one place. It was something like this https://crawl.develz.org/tavern/viewtopic.php?f=12&t=9463&p=130330#p130330
You can ignore everything except `The dragon lost 61, current 11, max 96` there.

**Comment by Sandman25DCSS** [comment]
Also I had `An electric golem comes into view. hp 132, ac 5, ev 20, hd 15`

**Comment by jeremygurr** [comment]
It's true that I could more easily just put it on an extra line, but I'm really against more message window clutter. One of my major annoyances with the game is having to hit space for "more" 3+ times between every action in a battle. I've been working hard to reduce the noise.

**Comment by jeremygurr** [comment]
That's true, I could quickly do just that one piece for now.

**Comment by Sandman25DCSS** [comment]
I think it can be optional. I imagine many players would like to remove displaying monster HP (or even damage).

**Comment by jeremygurr** [comment]
Optional would be ideal. But it's a lot more work because I need to centralize the strings first. I'll get there though eventually.
