### ISSUE TITLE
Heal wounds (yes, again)

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#438]
50%/100% max HP healing is extremely unbalanced thing, it is more powerful that Felid's extra life or unlimited scrolls of blinking.
Players are just unkillable, they don't need any skill to survive any situation. Scroll of blinking/teleportation is much weaker, it's primary use is to buy some time so you can quaff some potions during several turns healing slowly. Previously it took player's skill to survive, good players would read teleport at relatively high HP and then quaff potions of heal wounds while waiting, bad players would just die. 
Now you don't need to blink/teleport, you just quaff potions of heal wounds and continue fighting.

I got 9 runes on challenging without using a single potion/wand of heal wounds. I have 328 HP in statue form, healing 164 HP would feel like cheating. The amount is even greater in tree form.

All those are extra lives:

```
r - 15 potions of heal wounds {!q}
 o - a wand of heal wounds (12/18) {!d}
```

http://crawl.homedns.org/morgue/SlowThinker/SlowThinker.txt

**Comment by jeremygurr** [comment]
The fundamental mechanic itself is no more broken than any other escape or buffing mechanism. Too many blink scrolls or too strong of armour or weapons would lead to the same result. The problem is how many you come across vs the difficulty of the game. I tried to fix the by reducing the frequency, but it prevents players from using healing potions to buy more teleport time when they need it. So I propose we split the potion in half.

There could be a potion that heals a flat 10/15/20 points (based on difficulty), and a potion that heals 100%. The second will be much more rare, and the first will be as common as healing potions were before. 

The second could be called "life potions", or "restoration potions"? Or "second chance" potions :)

**Comment by jeremygurr** [comment]
Is challenge mode too easy also? For 9 runes you should have had to use some healing potions. Even at your skill level that seems to easy for what I'm aiming for. 

I'm thinking of taking the rune curses to +1 hd for standard, +2 hd for challenge, and +3 hd for nightmare. 

Maybe one of the rune curses could be all healing effects are reduced by 25%.

**Comment by Sandman25DCSS** [comment]
No, blinking scroll is much worse late game, especially in Hell, Pan, Tomb or any other level where you cannot rest for too long especially since regeneration requires stamina now.
I don't see why we need to have double factors to make game easier/harder, max HP (+50%, -33%) already differentiates difficulty levels by a lot. So at least let's make challenging mode potions work like in vanilla crawl, it is too easy now. Though easy mode is close to explore mode now, healing 300+ HP as a single action is extremely OP.

**Comment by Sandman25DCSS** [comment]
100% potion stops CA being a roguelike.

**Comment by Sandman25DCSS** [comment]
Right, I haven't used any potions, Cerebov with 607 HP died without a chance, the same to Lom Lobom and all other pan lords. Finesse with UC 27 and transmutations is awesome, +8 triple crossbow of electro at min delay with Finesse is awesome too and I had Statue Form in case I needed protection from torment.

**Comment by Sandman25DCSS** [comment]
Oops, why Cerebov had 607 HP? It's supposed to have at least 650 HP according to wiki.

**Comment by Sandman25DCSS** [comment]
I am not sure increasing HD is a good idea. As far as I know it increases damage from spells and attack flavours but does not increase standard melee damage. Also increasing HD makes many tactics useless, there is no point in training stealth, dodging, throwing for needles, hexes...

**Comment by jeremygurr** [comment]
HD should increase melee weapon damage too, as well as accuracy. If it doesn't that can be fixed :)

I don't understand why increasing HD makes stealth/dodging/etc useless. Care to elaborate?

**Comment by yrmvgh** [comment]
http://crawl.chaosforge.org/Stealth#Positive_Factors_2

**Comment by yrmvgh** [comment]
http://crawl.chaosforge.org/To_hit#Monster_To_Hit_.28Melee.29

You can go D&D style, though, and try fiddling with various knobs to ensure that players and monsters "treadmill" in place relative to one another.

**Comment by Sandman25DCSS** [comment]
For needles please see https://loom.shalott.org/learndb.html#blowgun

**Comment by Sandman25DCSS** [comment]
For hexes please see https://loom.shalott.org/learndb.html#mr

**Comment by jeremygurr** [comment]
so needles have a HD cap. You know how much I dislike caps :), that is easily fixed.

I don't see a cap for monster MR though. Assuming the player doesn't have an MR cap, they should theoretically still be able to overcome it with enough focus and training.

**Comment by jeremygurr** [comment]
ok healing has been restore to standard vanilla mechanics for all difficulty levels, except that standard mode heals 10 more than vanilla, and nightmare heals 5 less per potion.

**Comment by yrmvgh** [comment]
That.... is a pretty big deal! How do we put a HUGE ANNOUNCEMENT in front of every player? Will versioning protect them or will they just boom, not heal so much?

**Comment by jeremygurr** [comment]
It will be a surprise. Versioning only works when I make a save game breaking change.
