### ISSUE TITLE
increasing HD for rune curses

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#439]
This is the place to discuss issues with using HD for rune curses. So far I know we need to remove the HD cap for poison needles, etc, so that with enough skill players can still use those on higher HD monsters.

**Comment by Sandman25DCSS** [comment]
Well, if HD increases linearly with number of runes and player's skills increase slower, then some tools will be harder to use. But now that I think about it probably it is exactly what we want, it should be harder to confuse monsters or stay unnoticed at higher number of runes even if it is the same monster type.

**Comment by Sandman25DCSS** [comment]
And for needles stabbing the chance to paralyze should go down as well, otherwise increased mosnter HP does not matter.

**Comment by jeremygurr** [comment]
Looking at the code, I don't see a real cap on poison needles against monsters. I only see a case where there is a guaranteed 2% chance of hitting if the HD is less than 15. Otherwise it just uses the normal chance calculation. And all of this is in effect in games now. NIghtmare adds 3 HD per curse. Standard 1.

**Comment by Sandman25DCSS** [comment]
I don't see monsters having increased HP. For example, `A hellion comes into view. (37hp)` after 10 runes, hellion can have 25-52 HP according to wiki.

**Comment by jeremygurr** [comment]
Done.
