### ISSUE TITLE
Mutation bug

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#440]
I got 
`118171 | Abyss:1  | Gained mutation: You cannot study or cast Transmutations magic. [a neqoxec]`

I don't think this should be in the game.

**Comment by jeremygurr** [comment]
Hmm.... that is pretty vicious. Maybe it should just be that you can't train it, but you can use the skills you already have.

**Comment by yrmvgh** [comment]
If this goes, Sac Hand should go too. Lose your shield or 2 hander, shield skill, and a ring!

**Comment by jeremygurr** [comment]
yeah, but I think crazy things like this can really add interesting challenge and dimension to the game. Just like a very lucky and beneficial mutation can happen (50% torment resistance), you also have a chance of losing your ability to train summoning skills. It's not permanent though and you can save cure mut potions for this kind of thing if it's too bad. But forcing adaptability is a vital ingredient to this game I think.

**Comment by jeremygurr** [comment]
Done.
