### ISSUE TITLE
Danger Mode Threshold

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#441]
It says that it triggers when you take 30% or more damage relative to your HP, but it checks your HP after the damage is dealt. So it's actually triggering when you take 21% or more of your HP.

For now, I think players can make it trigger "correctly" by putting this in their RC files:
danger_mode_threshold = 43

**Comment by Sandman25DCSS** [comment]
I believe it is expected to check HP after the damage is dealt.. If you set danger_mode_threshold = 100, it means you want to get a warning when you can die next turn via getting the same amount of damage.

**Comment by jeremygurr** [comment]
Yes that is true. Would it be more intuitive to be before hp loss?

**Comment by Sandman25DCSS** [comment]
For me it is better as is. Not sure if I have typical mind :)

**Comment by yrmvgh** [comment]
I find it mildly counterintuitive, but I can just set it higher so that it bugs me less. I'll leave this open in case @G0rg0 or @sleepysteel have a chime to ring in
