### ISSUE TITLE
Difficulty does not change

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#443]
I press 'n' in difficulty mode selection screen, then pick species and background from the lists and still end up playing on challenging instead of nightmare

**Comment by jeremygurr** [comment]
If you hit tab to auto-select the last monster you picked, it will also use the last difficulty mode you picked. It's a bug. You can get around it for now by manually selecting the species and job.

**Comment by Sandman25DCSS** [comment]
I know about this bug, this is why I made sure I manually select species and background, not by pressing tab.

**Comment by Sandman25DCSS** [comment]
Something is definitely wrong. I change my RC file to include difficulty=nightmare so I was not asked about difficulty, but the game still was started at challenging.

**Comment by jeremygurr** [comment]
because it pulls from your last game if you hit tab. It needs to be fixed.

**Comment by Sandman25DCSS** [comment]
I didn't hit tab, I know about the bug with tab several days already so I don't use it. Have you tried to reproduce it?

**Comment by jeremygurr** [comment]
Fixed. Now tab works properly to select previous selected mode, and what you choose overrides tab as expected.
