### ISSUE TITLE
Check out our new test website

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#445]
http://circusfork.github.io/index2.html

What else should we write on it? If you write a sentence or two that you think should be on the website, I'll put it up there! :smile: 

Check out the super subtle link to index2 hidden on [index1](http://circusfork.github.io/index.html), hehe

**Comment by alexjurkiewicz** [comment]
Nice work!

Some quick UX feedback:
- It should be clear for visitors how to play. Generally the top right of a page is used for "login" or similar buttons, so isn't where users would look for a play button. I suggest a large button in the middle of the screen like the DCSS homepage.
- "Aussie Server" link should be next to "Play DCSS-CA" and those two buttons should be renamed to something like "Play Online (AUS)" and "Play Online (USA)", respectively.
- The column width is quite narrow. It'd be good to make it slightly broader
