### ISSUE TITLE
You fail to dodge

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#447]
_(The Kobold)_ i am getting "helpless you fail to dodge" when i don't expect it
_(The Kobold)_ something change?
_(The Villain)_ me too!
_(The Villain)_ I don't know why yet

brb code diving ... almost naptime though, I promise nothing

**Comment by yrmvgh** [comment]
https://github.com/jeremygurr/dcssca/blob/9d43ecff1d46cdb119c25463c755cb32fb052da8/crawl-ref/source/beam.cc#L3434
Don't fully know what's going on here but this is probably the culprit...

**Comment by jeremygurr** [comment]
Fixed.
