### ISSUE TITLE
Heal wounds is often put by vaults

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#45]
I have just cleared Sewer and I have 8 potions of heal wounds at XL 6. Not sure if you want to fix it though, that's too much work probably.

**Comment by jeremygurr** [comment]
wow on hard mode? There's something seriously wrong there.

**Comment by Sandman25DCSS** [comment]
Yes, hard mode.

**Comment by Sandman25DCSS** [comment]
Some vaults in Sewer don't use random potions, they specifically put potions of heal wounds and curing.

**Comment by jeremygurr** [comment]
That makes sense. So then those vaults just need to cool it a bit when it comes to healing potions. Maybe some of them can be replaced with cure or resistance potions. Do you know how to edit vaults by any chance? I'm sure I could work it out easily enough, but if you already have experience with that, it would save me time that I could focus on other things. No big deal if you'd rather not.

**Comment by Sandman25DCSS** [comment]
I think it will take very little time. You can open /dat/des/portals/sewer.des and replace "potion of heal wounds" with "potion of curing".  We will spend more time if I change it and send the new file to you :)

**Comment by Sandman25DCSS** [comment]
Or I guess you can just remove it since the actual potion is usually taken from a list of potions.
So you can replace "ITEM:     potion of curing / potion of heal wounds" with "ITEM:     potion of curing"

**Comment by jeremygurr** [comment]
gotcha. I reduced all heal potions in all portals to about 30% of original.
