### ISSUE TITLE
60+ damage magic darts, 350 spell power halfling

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#452]
Just racial wild magic, robe of the archmage, less than 10 spellcasting, and less than 20 conj skill. Something geometric something maybe?

![wow](https://camo.githubusercontent.com/01154e2b1421ad51764208b03225d284806b9642/687474703a2f2f692e696d6775722e636f6d2f4e7732585036622e706e67)

**Comment by jeremygurr** [comment]
Did this character die? I need the save game to look at.

**Comment by jeremygurr** [comment]
Oh this was a major bug. Fixed now.

**Comment by yrmvgh** [comment]
Yeah, that one died, I had no will to live with that kind of cheese heh. Thank you for fixing it, I will try out an Honest halfling darter and hopefully have a lot more fun / a legit win!
