### ISSUE TITLE
Update the 'lv' field of logfile/milestone entries

### ISSUE THREAD

**Issue by alexjurkiewicz** [jeremygurr/dcssca#453]
In vanilla crawl, this field is currently `lv=0.1` (or `lv=0.1-sprint.1` for sprint). I think this would be a good field to modify to signal dcssca is a unique fork. You can see the code to specify this field in `scorefile_entry::set_base_xlog_fields` (`highscores.cc`).

A value like `dcssca-0.1` would be ideal, IMO.

**Comment by jeremygurr** [comment]
Done
