### ISSUE TITLE
Pakellas MP costs

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#458]
This god's abilities seem to be based on your current MP pool size, not your base MP pool size, so you can get a hefty discount if you make a bunch of summons.

**Comment by jeremygurr** [comment]
I didn't see any abilities that worked like that. Could you give me a specific ability that appeared to work that way? It seems like device surge takes 1 mp always, Quick charge should take 2. I don't know how supercharge works.

**Comment by yrmvgh** [comment]
![](http://i.imgur.com/BkqNZGs.png)
https://github.com/jeremygurr/dcssca/blob/dafa564f9e1be19f258edce63e7735df5d8c3725/crawl-ref/source/ability.cc#L692
![](http://i.imgur.com/CHCAfKa.png)

**Comment by jeremygurr** [comment]
Fixed.
