### ISSUE TITLE
Make morgue files reachable

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#46]
They should work correctly now

**Comment by Sandman25DCSS** [comment]
What is the path? I cannot access http://crawl.homedns.org/morgue/, http://crawl.homedns.org/morgues, http://crawl.homedns.org/crawl/morgue, http://crawl.homedns.org/crawl/morgues

**Comment by jeremygurr** [comment]
it is /morgue/{user}/{file}
it assumes you know the morgue file name. Is that not normally the case? Does the web server normally provide a list of morgue files?

-- Jeremy

**Comment by Sandman25DCSS** [comment]
Yes, all servers provide access to morgue directory of a player (http://crawl.berotato.org/crawl/morgue/Sandman25/) or even all players (http://crawl.berotato.org/crawl/morgue/). It is hard to remember filenames, I don't want to bookmark all my games in case I want to analyze them later.

**Comment by Sandman25DCSS** [comment]
Also final filename is unknown since it includes timestamp usually

**Comment by Sandman25DCSS** [comment]
By the way http://crawl.homedns.org/crawl/morgue/sandman25/sandman25.txt http://crawl.homedns.org/crawl/morgue/Sandman25/Sandman25.txt cannot be accessed either

**Comment by jeremygurr** [comment]
done

**Comment by Sandman25DCSS** [comment]
Thank you!
