### ISSUE TITLE
careful mode changes: use MP instead

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#461]
Maybe careful mode should be renamed to Focus mode, and it should burn MP instead of SP. I think that broadens options for melee characters, and more evenly balances the escape risks for a spellcaster / stabber. 

So a melee character could play in power mode, increasing damage, but burning through SP much faster than normal. Or they could take a 33% increase in chance to hit, and be able to attack for much longer in focus mode, before running out of stamina, since they are burning MP instead. The normal mode cost of 1 SP per attack is still in place, but the added action cost of focus mode will be 1 MP per attack. If they were only in power mode, it would cost 2 SP per attack, and 0 MP. 

That would make spellcasters even more likely to choose power mode, although they do it at expense of losing their ability to escape (each spell cast cost x MP, and 1 SP). If they did focus mode instead, each spell would cost x+1 MP, and 0 SP, preserving their ability to escape.

**Comment by Sandman25DCSS** [comment]
I don't think escape mode is really escape mode, it's more like "burn SP to get into corridor" or "burn SP to regenerate HP/MP" since you are still not faster than most monsters.

**Comment by jeremygurr** [comment]
Yeah escape mode is a bit weaker now. It does have the EV bonus which still  helps with escape. Do you think it should go back to 0.9, since everything else has been nerfed so much? Or something else could be done to make it a better escape mode?

**Comment by Sandman25DCSS** [comment]
No, I am fine, it should be 1.0 on nightmare indeed. On challenging/standard it could additionally automatically cast Swftness to prevent kiting while still allowing to escape if stairs are close.

**Comment by Sandman25DCSS** [comment]
Or maybe standard mode can have 0.9 and no swiftness.

**Comment by jeremygurr** [comment]
Yeah I took standard mode escape to 0.9, challenge mode to 0.95 (so sometimes they are 1.0, sometimes 0.9), and left nightmare at 1.0.

**Comment by yrmvgh** [comment]
> challenge mode to 0.95 (so sometimes they are 1.0

I like this because it'll keep energy randomizatein off our backs!

**Comment by jeremygurr** [comment]
Done.
