### ISSUE TITLE
setting all rune branches to 4 or 5 floors

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#465]
Would it be a bad thing to set all rune branches to have the same number of floors? Is there a good reason for the differences? This would make things simpler for players, who have to keep hitting ^o to figure out how many floors are in the current branch. 

D: 15
Lair, Forest: 8
Pan: 20+
Zig: 27
Everything else: 4

So this would shrink Zot, Abyss, Dis, Tar, Coc, Geh
and expand Orc, Elf, Dwarf, Crypt, Tomb

Anyone have any strong feelings about this either way? We could also do 5 for everything else instead of 4.

Ideally, I'd like to take D, Depths, Lair, and Forest to 10 each too (or 8 each). Then we would just have 2 major branch sizes, with pan and zigs being the only exceptions.

**Comment by jeremygurr** [comment]
Ok, I'm going to take another stab at this:

D: 27 floors. Orb is at the bottom. No depths or zot (although the bottom 5 floors will still behave just like zot :) )
Lair, Forest, Hells: 7
Pan: 20+
Zig: 27
Everything else: 4

I like this a lot better. Oh, when you pick up the orb, all dungeon floors above you regenerate and repopulate with monsters. Except instead of D:26 having level 26 monsters like it did before, it will have level 28 monsters. D:25 will have level 29 monsters. D:24 will have level 30 monsters. D:1 will have level 53 monsters. 

There's nothing to stop a speed runner from just going straight to D:27 and picking up the orb, except for the insane monsters that will await him on the way up...

Maybe the orb has it's own curse where it slows the player down inversely proportional to the number of runes the player is carrying. So if you try and pick up the orb with 0 runes, it can't be moved. So you must have at least 1 rune. Wow the orb is heavy. Having 1 rune, the orb changes the player's base movement speed to 200% normal (typically to 2.2 in normal mode, instead of 1.1). Having 2 runes, their speed is at 150% normal. 

0 runes = infinite weight, can't move
1 rune = 200%
2 runes = 150%
3 runes = 133%
4 runes = 125%
5 runes = 120%
...
20 runes = 105%, which would be 1.15 in normal mode, or 1.05 in escape mode nightmare difficulty.

**Comment by jeremygurr** [comment]
picking up the orb recharges all runes. And the orb has it's own charged ability: teleport immediately to D:27. It gives you one more chance if you get into too tough of a situation in the ascension. Of course you could always pick up another rune (if there are any left) on the way up and recharge the orb again.

**Comment by yrmvgh** [comment]
As you know, I still think 3 rune games take a bit too long as-is, and I periodically die in Zot from impatience and corner cutting! :grinning:

**Comment by Sandman25DCSS** [comment]
I like hell branches having 7 floors, retreating from 5-6th floor is not very pleasant but sometimes I have to do it.
I don't like idea of repopulating floors after picking up the orb. There is a significant difference between characters, some weak characters have to dive for the orb, some powerful characters just clear everything, some not so powerful characters have a choice of making orb run easier or risk dying while clearing floors. It can be easily seen in Zot 1-4 where Orb of Fire can be met and give nasty mutations. With repopulation there won't be any difference, everyone would just skip Zot 1-4.

**Comment by jeremygurr** [comment]
The point of this is twofold:

1) to prevent players from just clearing all of zot before picking up any runes or the orb, and thus skip most of the effects of the rune curses. 

2) to prevent the player from engaging in tedious behavior like digging tunnels between staircases to minimize ascension distance.

If it's too hard, we can scale back monster generation or tone down the monster difficulty. That's easy. What isn't easy is avoiding these two situations mentioned above.

**Comment by Sandman25DCSS** [comment]
I don't get why you are trying to achieve 1).
Is it ok if I clear D1-15? Is it ok if I clear Lair 1-8? Why should Zot be different? Rune curses were in effect while I was clearing Zot (here I assume your plans to prevent leaving Zot without orb are already in place).

**Comment by Sandman25DCSS** [comment]
Also I wouldn't care about digging tunnels at this point. If player wants to win that badly, he can just farm Lair 1 for XP indefinitely.

**Comment by jeremygurr** [comment]
Yes, if the player is locked in Zot, the floors don't need to be regenerated there. 

But in this issue I'm considering the idea of having Dungeon be 27 (or 25 or 20 or whatever) floors, and removing Depths and Zot entirely. The key differences are that there will be 3 stairs between all floors, instead of having a single stair bottleneck between zot and depths and dungeon, for no real reason. And it simplifies things for the player: get to the bottom of the dungeon, grab the orb, and get to the top. Extra branches along the way are optional. 

I don't like unlimited monsters, as you probably know. I will probably stop monster spawning entirely eventually. What monsters spawn when a floor is created is all that floor will have. A fixed experience pool is much easier to balance. But then they all come back on the ascension. The ascension is the real proof that the player has overcome the dungeon, and not just gotten lucky and rushed past a bunch of bad guys. And like I said, if that's too hard, it's easy to adjust the knobs for that. 

One of my key objectives here is to remove all reward for tedious behavior, so that this can be used for serious gaming like tournaments, as well as be fun for casual gamers.

**Comment by Sandman25DCSS** [comment]
I don't see ideal solution for monster generation. If it's stopped completely (like is done in vanilla after [15k turns](http://crawl.chaosforge.org/Monster_generation) ), then resting on previous level becomes absolutely safe which is also bad.
I like single entrances to Depths 1 and Zot 1, they can provide very unusual challenge and make you either change your plans or just randomly teleport on new level which is fun IMHO.

**Comment by jeremygurr** [comment]
I think there will be plenty of interest with the rune curses messing things up along the way. Some of them play with the stairs even, so it will already be quite a challenge. I don't think the additional challenge of a couple more bottlenecks is worth the complexity cost of 2 more branches that don't do anything that dungeon couldn't do. Except for Zot. The ability to lock Zot until the player escapes is valuable enough to justify the branch's existence. Maybe I'll just have D1-20, then 4 Zot floors that the player is locked in until they have the orb. No escape, no rest. But there won't be monsters immediately around the entrance either. 

They must have had a reason they created depths. I wonder what the reasoning was. What did it accomplish?

**Comment by Sandman25DCSS** [comment]
I think primary reason for Depths was to make it clear that Depths 1 is much more dangerous than D15. The difference is huge, you basically have to clear 2 Lair branches, Elf, Vaults and Crypt before entering Depths. And even then you can die to Caustic Shrike, Juggernaut, Iron Giant or Ancient Lich easily.

**Comment by jeremygurr** [comment]
Done.
