### ISSUE TITLE
if this is basically an early release, it might be good to do like vanilla does

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#475]
by listing it as unstable, experimental, or trunk
or having a link to play 1.4

**Comment by jeremygurr** [comment]
Yeah pretty much everything here is experimental :). That goes with the territory.

**Comment by jeremygurr** [comment]
Ideally we would have a stable and less stable version, but supporting multiple versions is a lot more work and we don't have the dev capacity for that yet .

**Comment by yrmvgh** [comment]
Fair enough. 1.4 was very solid I thought, rather palatable for public consumption. But no need, if it's extra work to keep it running!
