### ISSUE TITLE
Beogh gift uses wrong inventory

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#477]
I gave artefact trident to my orc follower, now I see this:
`Here: Spirok the orc knight, wielding a potion of lignification {!q} and wearing a plate armour (friendly)
`

**Comment by Sandman25DCSS** [comment]
```
Spirok hits the water moccasin (7) with a potion of lignification {!q}! 
The water moccasin dies!
```

**Comment by jeremygurr** [comment]
hahaha... that's hilarious

**Comment by Sandman25DCSS** [comment]
Fortunately Beough was smart and considered the potion inferior to trident it replaced with.
I mean it gifted trident to Spirok so I am ok now

**Comment by jeremygurr** [comment]
Fixed.
