### ISSUE TITLE
Revert "D" to drop last picked up item again

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#48]
As HardboiledGargoyle wrote in tavern (https://crawl.develz.org/tavern/viewtopic.php?f=8&t=19227&p=264150), D was very useful letter, I miss the functionality too. His another proposal can be good too though it is not that critical IMHO since player still would need to find new letter anyway.

**Comment by jeremygurr** [comment]
Done. D is back and Control-D can be used to drop consumables. 

Soon I will remove chopping from the game, so the 'c' key gets freed up. Maybe that can be used for the consumable inventory then.
