### ISSUE TITLE
I pick up bread and meat but don't actually know whether they do anything

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#481]

**Comment by jeremygurr** [comment]
All food just needs to disappear from all vaults, etc. We need to make stamina potions to replace fruit, maybe call them fruit juice or life potions and allow fedhas to use them for his abilities.

**Comment by yrmvgh** [comment]
+1000 for bringing back [fruit juice](https://nethackwiki.com/wiki/Potion_of_fruit_juice)

**Comment by jeremygurr** [comment]
fixed
