### ISSUE TITLE
stamina exhaustion (again)

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#499]
Vanilla combos are "balanced" so I believe we should not give penalty for low stamina but bonus for high stamina. Otherwise challenging mode characters are weaker than vanilla ones, they deal less damage in most cases because it takes very little time to run out of stamina no matter what character you are and what you do.

Is it a goal to have basic power of characters similar to vanilla crawl before obtaining a single rune? I hope so, it will help to attract more players with vanilla experience.

Though I suspect that no monster generation means that now optimal play consists in luring a single monster as far as possible to explored territory (80 tiles with normal speed monster I guess), killing it and then fully restoring stamina before exploring again, at least before joining a god so piety decay is not an issue yet.

**Comment by jeremygurr** [comment]
I'm not clear on what is being suggested here, or what question is being asked.

**Comment by Sandman25DCSS** [comment]
I am suggesting to remove penalty for low stamina. Players can use power/focus/quick mode with stamina, that's enough to differentiate from situation when stamina is low/zero.

**Comment by G0rg0** [comment]
I agree completely. 

It would be great if low/no stamina just kicks you out of any of the bonus power/focus/quick modes, but doesn't penalize you any further. 

That way, people can play just like vanilla, but the extra powers are there to boost you through the increased difficulty of the CA fork.

**Comment by jeremygurr** [comment]
ok, will do then. No exhaustion penalty. Deploying now.
