### ISSUE TITLE
summoner solutions

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#509]
Okay I'm thinking of putting a total cap of 4 on all player summons. They can still have beogh followers or zombie followers in addition to the 4 summons. 

The player can pick any 4 that they want. But to change them they will need to release the summons and summon again.

**Comment by Sandman25DCSS** [comment]
That's more cruel than vanilla summon caps IMHO. You really encourage to amnesia low level summons, nobody is going to use Ice Beasts when they have Hydra or Monster Menagerie. Also just 4 summons means I won't be able to use summons as meat shield or spells like Haunt.
Can you reuse vanilla summon caps?

**Comment by jeremygurr** [comment]
I think summoning is OP in vanilla too. Yes I would use ice beasts even when I have hydra online because they have different purposes, resists, etc, and they cost much less. The spell cost is a major factor in the choice of what to composed your summoned horde out of. 

Ideally all summon spells would have a place, even in late game. Maybe at high spell power, summon mammal casts several at once, increasing escape options (like summon butterfly). If ice beasts become too weak later in game, maybe their ac needs to scale a little better with spellpower.

**Comment by Sandman25DCSS** [comment]
Maybe I misunderstood your first post. Did you mean that I will be able to summon just 4 creatures overall? So if I summon 4 hydrae, I cannot summon anything else, even mammals?

**Comment by jeremygurr** [comment]
Correct. You can summon 4 hyrdas and consume your entire mana pool (if you can even get them cheap enough to pull that off), or you can combine 2 hyrdas with a couple of ice beasts for their armour, and higher per hit damage, or canines for their speed. I want all of these to be tweaked in power so that a canine is still useful even later in the game, scaling it's strong points with spell power. Canines are good for a fast speed attackers. Ice beasts can swim and have good armour, and are pretty much immune to ice attacks. Hydras have a many lower damage attacks, but would be bad against high ac enemies. Imps have many different resistances, are hard to hit, and have ranged attacks (sometimes). Mammals are easily to get to low mp costs, and if we changed them to summon more per turn, summoning 4 in a single turn can provide valueable escape enhancers, or at least a distraction to soak up a few turns from many enemies. 

As far as haunt, I don't think it needs to follow the same constraints as other summons, since it works a bit differently. Sticks to snakes, for example, can be used as many times as you have sticks, and doesn't affect the summoning limit at all. So you can haunt as many monsters as you like, with the normal magic cost and expiration times. Only your static summons stick around indefinitely and reduce max mp.

**Comment by Sandman25DCSS** [comment]
I remember you removed per-spell-caps from summoning spells because those were limiting player choice and now you introduce a more severe total-cap and are trying to make mammals similar in power to hydra or dragoncall to provide options. I don't know what to say here, I think I will continue to ignore summoning spells, sorry.

**Comment by jeremygurr** [comment]
players have more choice than before because they can have 4 canines, whereas they could only have 1 canine and 3 imps before. Now you can choose whatever combo you want. 

Hydra and dragoncall will always do more damage than their cheaper counterparts, but damage done isn't the only factor to be considered. Sometimes you need a monster that can take more damage, for example, and I think something should do a better job of that than hydra (maybe guardian golem and ice beasts?) And sometimes you need something that can do more damage against a heavily armoured opponent, and so maybe ice beast would be better than hydra. Or maybe you need something that can keep up with a fast moving monster, so imps or canines would be better.

**Comment by Sandman25DCSS** [comment]
I don't see more choice here. My vanilla summoners could have lightning spire, guardian golem, 3 ice beasts, 2-3 mana vipers and monster menagerie _at the same time_.

**Comment by Sandman25DCSS** [comment]
Now I will have 3 monster menagerie all the time.

**Comment by jeremygurr** [comment]
No because there will be enough distinction between each summon eventually to not make that a no-brainer. If it is, then I'm not done yet :)  The cap could easily be 5 or 6 if that makes most sense. I am actually trying to nerf all summoners in general at the same time, because from my experience with them in vanilla and in ca, they feel quite OP to me.

**Comment by Sandman25DCSS** [comment]
I don't see how 5-6 hydrae or monster menagerie can be a nerf.
I suspect you will come to per-spell-cap soon to make every summoning spell more distinct ;)

Yes, Summoning is OP in vanilla (Dragon call with Sif Muna is typical example) but there are other ways to nerf it like increase level, decrease cap, decrease duration, add another magic school...

**Comment by SleepySteel** [comment]
I say have a hypothetical "100%" summoning capacity, and have different summons take up a different amount. Nowhere near thought through, but for example- 16 spammals might take up as much as 1 dragon, or 2 hydras. If nothing else, things like spammals and butterflies should be a special case, possibly along with lightning towers and guardian golems.

**Comment by jeremygurr** [comment]
done
