### ISSUE TITLE
Poison prevents using stairs

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#51]
I am not sure if it is intended, I couldn't use stairs with no monsters in view due to being poisoned.

**Comment by jeremygurr** [comment]
It's somewhat intended. I had considered that case and figured it was okay to wait until the poison was gone first. But now that I think of it, if you are trying to escape monsters it's not very fair to be stopped by poison. I guess I should make that distinction then.

**Comment by jeremygurr** [comment]
Fixed.
