### ISSUE TITLE
minimum spell cost

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#510]
I'm thinking of setting a minimum spell cost of 5 for all spells. Currently there is a different minimum for each spell level. I will change it to have a minimum of 5 for all spells. It will be very easy to get a level 1 spell down to 5, and very difficult to get high level spells down that low. 

This should temper a number of extreme situations.

**Comment by Sandman25DCSS** [comment]
You can just divide MP by 5 IMHO. It should not require math skills to calculate how many times I will be able to cast 27 MP spell with 134 max MP.

**Comment by jeremygurr** [comment]
Dividing the mana pool by 5 affects other aspects of the game such as focus mode cost. The pool needs to be the size it is to allow for smaller (<5) changes. Also, cutting it by 5 doesn't avoid much more math, since most spells will cost more than 1 point for most of the game.

**Comment by G0rg0** [comment]
I'll be honest, I really don't like variable spell costs at all (with the notable exception of the Sif invo interaction). I'd much rather have fixed costs and make adjustments elsewhere if balance is needed.

**Comment by Sandman25DCSS** [comment]
Yeah, especially since you don't know when you get costs decreased. It's similar to AC gain when training Armour, unspoiled player has no idea when next AC point will be obtained.

**Comment by Sandman25DCSS** [comment]
I have just realized that decreasing spell costs can be replaced with increasing MP pool. And then we won't need to think hard how to fix guardian spirit, channeling etc. Maybe we even will get back to vanilla MP this way :)

**Comment by jeremygurr** [comment]
done
