### ISSUE TITLE
Orc sometimes requires you to go down to Orc:5-8 to finish exploring Orc:1-4

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#516]
because of the way Orc is generated, it is extremely unlikely, but theoretically possible, that you'd be forced to go all the way down to O:8 in order to find the ending vault of O:4.
or even just to get access to most of O:2
the simple solution is digging wands, but that's potentially undesirable

How about I add a 1 tile minivault to Orc 1 with a guaranteed digging wand?

**Comment by jeremygurr** [comment]
I think it's kind of interesting for the rare chance of being an extra challenge. Orc is a purely optional branch anyway.

**Comment by yrmvgh** [comment]
It has 4 shops in it... that is not optional imo. :stuck_out_tongue_closed_eyes:

**Comment by yrmvgh** [comment]
As branches get expanded with bonus floors, (which I just realized, is pretty spoilery... gonna take peeps some time to realize orc 5 isn't giving exp), might want to read this great summary of (some) of the level gen stuff!

https://www.reddit.com/r/roguelikedev/comments/3n63hw/faq_friday_22_map_generation/cvlmeys

**Comment by Sandman25DCSS** [comment]
Yes, probably there should be an explicit warning about no xp thing when going to orc 5 for the first time in every game.

**Comment by jeremygurr** [comment]
definitely. I plan on having a warning message, but just haven't gotten to it yet.

**Comment by jeremygurr** [comment]
Everyone agrees that we shouldn't give experience for deep branches right? Meaning bottom half of doubled branches?

I can fairly easily deepen as many branches as we need. Maybe orc is enough, but it's easy to extend others.

**Comment by yrmvgh** [comment]
Good stories are succinct stories, and I don't see a lot of value in junky floors full of junk with little or no loot and no exp. We have to ensure that portals and end vaults don't spawn on those floors, make sure the junk floors don't randomly steal all the unique-tagged vaults and unique/named enemies.

**Comment by yrmvgh** [comment]
In other words less is more! You've done a _wonderful_ job cutting many junky, mostly-pointless, or tedious things out of the crawl source, why dilute that by finding ways to introduce new mostly-pointless stuff? :laughing: 

I do see the Beogh reason to extend Orc, however...

**Comment by jeremygurr** [comment]
yes the extended orc won't take any uniques or branches or anything like it, unless you actually enter the floors.
