### ISSUE TITLE
Fragile items in shops

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#518]
This is a pretty rare problem, but it has happened to me once. Would it be possible to have Fragile visible even on unid'd randarts - at least in shops, but maybe everywhere?

Can waste a lot of money that way, and flavor wise, maybe the justification can be "you clearly see that whatever its other properties are, it is made of fog / dreams / ectoplasm and likely to fade away when ignored."

**Comment by Sandman25DCSS** [comment]
I wouldn't like this change, fragile is not the worst possible property and we don't have *Contam or *Confuse visible in shop either.
