### ISSUE TITLE
Trove does not accept scrolls

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#521]
> There is a portal to a secret trove of treasure here.
> This trove needs 5 scrolls of identify to function. Give it the items? 
> You must unequip the items first!

**Comment by Sandman25DCSS** [comment]
Also probably trove should never require id scrolls in CA

**Comment by jeremygurr** [comment]
well I already reduced the count requirement. 5 id scrolls should be fairly easy to obtain. But this bug should be easy to fix. I'll have time to work on it tonight.

**Comment by yrmvgh** [comment]
How about troves that require id scrolls being _temporarily_ disabled? Scroll drop rates have changed frequently, and when we're not tweaking that, we're tweaking insight rate, or changing the way insight is triggered, all of which directly influences the value of id scrolls. You can log out for a night having used your scrolls correctly up to that point, and log back in the next day, filled with regret.

Now, I don't mind that kind of constant change, but it has been far less of a thing with other consumables, which have fairly steady drop rates, usage, and value. I **do** disagree with "never require id scrolls ever again", but I think it'd be a good idea until our id system is stable.

**Comment by Sandman25DCSS** [comment]
ID scrolls are not a big deal because of insight mutation, they are too cheap for trove and should be removed from there  IMHO

**Comment by jeremygurr** [comment]
I see. Okay they are gone.
