### ISSUE TITLE
stamina cost is too low

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#525]
I cast Bolt of Fire as DE with Int 50 and Spellcasting 16.4, it costs 0-1 stamina so I can stay in power mode indefinitely (my max SP is 120) with amulet of SP regeneration

**Comment by jeremygurr** [comment]
Yeah that isn't right. Power mode is supposed to cost 3 sp every turn no matter what else is going on. Stam regen amulet should help, but maybe it is too strong now, or maybe it shouldn't even exist. 

Maybe all stamina regen shouldn't be happening while power mode is being used. Once you get away from monsters for a few turns (5 I think), stamina regen resumes.

Likewise, mp regen wouldn't happen while focus mode is on. 

So you can still extend your stamina in normal or focus mode with an amulet, but not if you are in power mode.

**Comment by yrmvgh** [comment]
The amulet slot is very valuable. Is infinite power mode better than Regen, Faith, Dismissal, and Rage? On many characters, Faith and Rage will do more for you than endless Power mode - and even when you compare SPregen to the weaker amulets, note that SPregen isn't actually benefiting you at all until you cross the point where your  SP would normally have run out. It's a dead slot until then, and could have been filled with something that helps you with those first few turns wherein all your enemies are alive.

**Comment by Sandman25DCSS** [comment]
that would make all regen items useless IMHO

**Comment by Sandman25DCSS** [comment]
I was replying to Jeremy

**Comment by jeremygurr** [comment]
fixed
