### ISSUE TITLE
Hill Orc is very limited in options

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#53]
Subdued magic 3  makes most spells almost useless, for example, conjuration spells deal too little damage, regeneration lasts only about 5 turns, summons expire very fast etc. Only Haste, Song of Slaying and Blink/CBlink seem to be good.

**Comment by jeremygurr** [comment]
so it cripples their spellcasting, but is that really a bad thing? It creates a unique play style. Does it make the game too difficult, or does it only limit play styles? Does the species need a buff to compensate?

**Comment by jeremygurr** [comment]
Hmm, getting haste and controlled blink much earlier than normal may be a sufficient compensation for lack of power in other spells.

**Comment by Sandman25DCSS** [comment]
Well, it is unique playstyle when comparing to other species but it will be the same playstyle every time you play Hill Orc. It has good aptitudes for Fire magic, Hill Orc with Fire Storm was fun. Another way to provide easy Haste and CBlink is via aptitudes like Spriggans do, for example.

**Comment by jeremygurr** [comment]
I don't want to lose that unique style of species that the wild magic might provide, if it indeed provides a valuable and unique gameplay. But it sounds like you are saying that we are losing something unique by losing the old hill orc species, right? If so, and if you don't think there's a way to achieve that either with other species or by adjust the hill orc, then maybe we should split it into a different species. What if we either move the wild magic to the lava orc, which is already broken anyway, and restore the hill orc to the way it was. Then we could work more on making the lava orc interesting and balanced. Do you know what the core issues were that cause the lava orc to be scrapped? I'm not sure it can be saved, but I think it's worth a try.

**Comment by Sandman25DCSS** [comment]
IMHO subdued magic is the best for species who has problems casting high level spells and cannot have high spell power anyway. Troll has been already changed quite a lot, how about Minotaur?

**Comment by Sandman25DCSS** [comment]
No, I don't know why Lava Orc was removed, probably it was considered too similar to Hill Orc.

**Comment by Sandman25DCSS** [comment]
I found this https://crawl.develz.org/tavern/viewtopic.php?f=8&t=12301

**Comment by jeremygurr** [comment]
I like the idea of moving it to minotaur. We'll try that.

**Comment by jeremygurr** [comment]
There was some people that really liked lava orc, and lots of proposals of how to fix them, so there must have been something interesting there. Sounds like one big issue is the developer that made them abandoned support, and no one else wanted to mess with it. It may yet be fixable. It sounds like the heat forms need to be controlled by something different though, possibly direct player choice through transformation abilities. It would be nice to find a couple of people who really liked them and get them to come and help us test and refine them. 

-- Jeremy

**Comment by Sandman25DCSS** [comment]
Well, I played the old Lava Orcs and liked them. Recently I won Lava Orc in your mode and liked them again ;) 
The only thing that may seem broken is that it is optimal to kite dangerous monsters to get high temperature. But then it makes you unable to read scrolls so it can result in a death. I suggest to make Lava Orc unable to evoke items when in high temperature so it will never be able to teleport away from danger.
