### ISSUE TITLE
Staff of energy is OP

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#531]
Staff of energy decreases Fire Storm cost from 13 MP to 7 MP, that's too much IMHO

**Comment by jeremygurr** [comment]
ok I cut the effect of staff on energy in half

**Comment by Sandman25DCSS** [comment]
Probably this effect should be removed completely. Staff of energy does not increase number of casts in fights in vanilla, it just saves some food. CA does not have food so we can use staff of energy just for channeling.

**Comment by jeremygurr** [comment]
ok effect gone.
