### ISSUE TITLE
Weird curse

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#532]
I got some heavy curses, cured them with scroll of remove curse but I still didn't get all properties back.

> rFire  + + +      SeeInvis .    a - staff of fire {rF+ !a}
> rCold  . . .      Gourm    .    d - +8 ice dragon armour of Obravargh {rPois rF- rC++ Slay+2, rC++, rF-}
> rNeg   + + +      Faith    .    U - +1 buckler {AC+3}
> rPois  âˆž          Spirit   .    Q - -2 hat of the Alchemist {rElec rPois rF+ rC+ rN+ MR+ rMut rCorr}
> rElec  +          Dismiss  .    q - +2 cloak {MR+}
> rCorr  +          Reflect  .    Y - +2 pair of gloves {Str+3}
> rMut   +          Harm     .    C - +1 pair of boots of Qazlal's Fury {rCorr MP+20}
> SustAt .                        O - amulet "Jetull" {RegenSP rF+ Dex+2}
> MR     +++++                    l - ring of fire {rF+, rC-}
> Stlth  +.........               s - ring of fire {rF+, rC-}
> 
> @: immune to fire clouds, lich-form, power, delayed fireball, studying 2 skills,
> repel missiles, very slow, almost entirely resistant to hostile enchantments,
> very unstealthy
> A: clever 1

As you can see I have rC++ from IDA, rC+ from hat, rC+ from lichform, rC-- from two rings of fire. Previously it resulted in rC++ but now it's gone.
And I cannot use scrolls of remove curse, it tells me 

> Really read w - 13 scrolls of remove curse {!r}? 
> None of your equipped items are cursed.

**Comment by Sandman25DCSS** [comment]
I tried removing all items which affect rC and now I have this:

> rFire  + + +      SeeInvis .    g - +0 blowgun
> rCold  x x .      Gourm    .    (no armour)
> rNeg   . . .      Faith    .    U - +1 buckler {AC+3}
> rPois  .          Spirit   .    (no helmet)
> rElec  .          Dismiss  .    q - +2 cloak {MR+}
> rCorr  +          Reflect  .    Y - +2 pair of gloves {Str+3}
> SustAt .          Harm     .    C - +1 pair of boots of Qazlal's Fury {rCorr MP+20}
> MR     +++..                    O - amulet "Jetull" {RegenSP rF+ Dex+2}
> Stlth  +++.......               G - ring of Shaolin {EV+8}
>                                 (no ring)
> 
> @: immune to fire clouds, power, delayed fireball, studying 2 skills, repel
> missiles, very slow, extremely resistant to hostile enchantments, fairly
> stealthy
> A: clever 1

So I have rC-- for no reason

**Comment by jeremygurr** [comment]
fixed
