### ISSUE TITLE
Weird mana cost

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#536]
I have 7 skill levels in Conjuration and 0 in Hexes yet pure Conjurations level 4 spell costs 12 MP but Conjurations/Hexes level 4 spell costs 11 MP.

**Comment by jeremygurr** [comment]
I need to download your character to look at it, but can't find your save right now, so you are either using a different account or have already terminated that character. 

The cost should be based purely on intelligence and spellcasting, and be exactly the same for all level 4 spells, so this could be some kind of randomized rounding. I'd have to look to be sure.

**Comment by Sandman25DCSS** [comment]
Yes, the character is terminated indeed

**Comment by jeremygurr** [comment]
This is something I fixed. They actually had the same cost (as all level 4 spells will), but because of randomization, it varied a little. I took away the needless randomization here, and the resulting confusion.
