### ISSUE TITLE
Remove piety decay

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#539]
Is there a reason for piety decay to still exist? From what I hear, it's mostly to discourage extreme cases of luring. But I believe those extreme cases have already been removed by stair dance, pillar dance, and extended kiting removal. So this just leave the negatives of piety gain (forcing the playing to not rest between battles), without the positives.

**Comment by G0rg0** [comment]
I say remove it, we can always add it back in if it seems necessary but I really don't think it is.

**Comment by jeremygurr** [comment]
done
