### ISSUE TITLE
should abyss have a particular threat band, like a branch? or an infinite threat range, such that it's always "the bad place"?

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#543]
should abyss should have a range of difficulty that places it in a particular threat band, like other branches? or should it have an infinite range of threats so that a lategame banish is never a free pass to heal up?

**Comment by yrmvgh** [comment]
If abyss gets a bigger high end that scales with the level of threats you're facing, perhaps the low end can also be expanded so that early banishes aren't so randomly lethal

**Comment by Sandman25DCSS** [comment]
I haven't been in Abyss since it was changed to have just 4 floors in CA but Abyss 5 is extremely dangerous in vanilla, sometimes it is a free pass to heal up and sometimes it is a free pass to die... Which is intended I believe.
