### ISSUE TITLE
Wand of heal wounds takes 10 turns with Evocations 16

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#55]
See title, is it expected to be like that? I assumed it was a linear dependency: 10 turns at Evocations 0 and 2 turns at Evocations 27.

**Comment by jeremygurr** [comment]
Hmm seems wrong, I'll check it out.

**Comment by jeremygurr** [comment]
Ok I adjusted it. It's actually an exponential scale:

evo 5 = 20 turns
evo 10 = 10 turns
evo 15 = 5 turns
evo 20 = 2 turns
