### ISSUE TITLE
XP potion gives double skill points

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#558]
I quaffed the potion, got some skills increased:

> Really quaff p - a potion of experience {!q}? 
> You feel more experienced! (2198)
> Your Fighting skill increases to level 3!
> Your Armour skill increases to level 2!
> Your Dodging skill increases to level 3!
> You have reached level 10!
> You gain insight: a scroll labeled GOPLEPH NU ZISS {!r} -> a scroll of enchant weapon {!r}

Then I selected which skills to train and got some skill points again

> Your Fighting skill increases to level 4!
> Your Crossbows skill increases to level 10!
> Your Armour skill gained 2 levels and is now at level 4!
> Your Dodging skill increases to level 4!
> Crossbows reached 10.

**Comment by jeremygurr** [comment]
fixed. It will go out with next deployment
