### ISSUE TITLE
Unable to enter Crypt 3

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#565]
Crypt 1 and Crypt 2 layouts are still swapped and I get consistent crash when trying to enter Crypt 3.

http://crawl.homedns.org/morgue/Sandman25/crash-Sandman25-20160517-115204.txt
http://crawl.homedns.org/morgue/Sandman25/crash-Sandman25-20160517-115108.txt

**Comment by jeremygurr** [comment]
Unfortunately they don't have the vault information in the crash dump. I need to have your save file to be able to track down the issue. In this case, since you have started a new game, I don't have enough information.

**Comment by Sandman25DCSS** [comment]
Ok, thank you.
