### ISSUE TITLE
Change rest_wait_both to respect stamina

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#566]
It would be very nice if rest_wait_both controlled whether player wants to restore stamina before exploring. Currently I still have to manually rest when my HP/MP are at 100% but stamina is not.

**Comment by jeremygurr** [comment]
Really? My stamina always charges up before exploring, because of rest_wait_both=true.

Oh I see the problem. You have a custom auto-explore lua function in your rc file. You need to change that to check sp also.

**Comment by Sandman25DCSS** [comment]
Oh, thank you, I missed it.
