### ISSUE TITLE
Tengu is extremely hard

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#57]
Tengu cannot wear any rings and thus is extremely hard. I am XL 18 Tengu with body armour of MR+ and cloak of rPois. I lack MR+++ (only MR++) and I have no rF+, rC+, rN+, rCorr. I can get a rF+ OR rC+ but it would make me at MR+ which is extremely bad (Snake with MR++ was not easy either, I almost got teleported in Snakes 4).

I suggest to move/copy intrinsic mutations from Troll to Tengu. At least Troll can get required resistances on rings and swap them as necessary. With current design I am really encouraged to use Tengu with some longbow and kite all monsters due to 0.5 turn per move and lack of resists.

**Comment by jeremygurr** [comment]
I kind of like the idea of a species that has a hard time getting decent resistances. I don't want it to be impossible or to force a very narrow gameplay style though. 

Although moving the intrinsic resistances across to tengu would solve this immediately problem, I think would come at the expense of species distinction. I like that a troll has an unusually easy time getting great resistances, and that the tengu has an unusually difficulty time. 

As far as the kiting issue, any significant challenge to the tengu will also strongly encourage kiting, so if kiting really is a serious problem, it is much broader than this specfic issue, and won't be solved by making it easier to get elemental resistances. 

Hmm.... tricky, I'll have to think about this one. Maybe some kind of ability that would give them an edge somehow.

**Comment by Sandman25DCSS** [comment]
My point is that cloak can have +Inv, MR+ or rPois, gloves can have +3 Str or +3 Dex, hat can have sInv or +3 Int. So Tengu basically requires luck with randarts to be playable unless it is lucky to find a robe with rF+ and rC+. Fire Dragon Armour is not an option, for example, because there is no way to fix the rC- without lucky mutation or randart.

**Comment by Sandman25DCSS** [comment]
I have just spent acquirement on armour, really unusual. Got lucky, gloves have rC+and MR+ so it becomes playable in my game.

**Comment by jeremygurr** [comment]
What if the tengu has unusually high magic resistance? It would still be quite difficult, but playable maybe? Or even magic immunity, to make them further distinct from any other species?

**Comment by Sandman25DCSS** [comment]
Yes, it could work. Player might choose armour to get rF or rC.

**Comment by jeremygurr** [comment]
Ok I added a mutation to tengu that should help the situation. It won't help your current character, since these mutations are only given as you advance to specific levels, but will help all future tengus. Check out the commit or readme for details.

**Comment by Sandman25DCSS** [comment]
Thank you. Also I suggest to nerf bonus for flying, +20 EV (from 27 to 47) and double speed movement (from 1.0 to 0.5) seem too much.

**Comment by Sandman25DCSS** [comment]
It takes 0.3 turn to fly a tile at XL 26, this is OP.

**Comment by jeremygurr** [comment]
I will reduce the evasion and reduce the speed advantage a bit. I can understand the evasion part, but what real impact on gameplay does a speed of 0.3 do vs a speed of 0.7 make? You can kite pretty well either way. The only significant different I can grasp at this time is that the 0.3 makes it easier to escape tough situations, which I don't think is a bad thing, especially for a species that is so squishy.

**Comment by Sandman25DCSS** [comment]
For example, 0.3 turn means that I can move and shoot an arrow every turn. Even juggernauts are a joke when you spend 0.2 turn to move (Haste does stack). One of the reasons why I don't play Spriggan or Centaur is exactly this, move advantage encourages time-consuming tactics.

**Comment by jeremygurr** [comment]
I adjusted the speed but this smells like a deeper issue, maybe at some point I can dig a little deeper. Hmm... a thought: what if when running away from a monster (or maybe just during an encounter). the monster randomly shouts out to other monsters, and occasionally new monsters spawn just outside of los, but ahead of the player, if an encounter has gone on too long. Kiting would be fine for quick encounters, but extended kiting would be impractical in most situations.

**Comment by Sandman25DCSS** [comment]
That would be spoilery. How about intrinsic ability to evoke Swiftness? That would still allow to escape from danger but would make kiting impractical.
Even after nerfing the speed boost is OP, during orb run I ran away from Executioner (0.4 turn per move when hasted and flying). When a fiend blocked my path, I just retreated from view, casted haste and run to another stairs (the other stairs were close, otherwise I would just run in circle and would outrun the fiend).

**Comment by jeremygurr** [comment]
That's a fair point. Maybe I'll push for getting the stamina system implemented sooner than later. I think that would take care of the kiting issues on a deeper level. That will have the same effect as making the speed of the tengu work like swiftness does.
