### ISSUE TITLE
another ranged nerf: remove launcher brands

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#571]
I think it's cool and valuable to have a stack of fire arrows in my inventory, until I come across a fire branded bow. Then they are pointless. Also makes ammo gifts significantly less valuable. I say no more branded launchers (except maybe some uniques).

**Comment by Sandman25DCSS** [comment]
Well, I have mixed feelings. I stopped using branded ammo after getting a flaming/freezing launcher but later I resumed using branded ammo after getting speed/velocity launcher. So maybe allow velocity/speed launchers? Though that might make scroll of brand weapon OP.

**Comment by jeremygurr** [comment]
hmm... good point. How about speed ammo instead?

**Comment by Sandman25DCSS** [comment]
Interesting idea.

**Comment by Sandman25DCSS** [comment]
I suppose you keep steel/silver/penetrating bolts, arrows of dispersal in game, they are fun IMHO.

**Comment by jeremygurr** [comment]
Yeah I don't want to remove any ammo brands. Just the launcher brands. I'll add velocity and piercing arrows. And maybe velocity bolts too. Bolts already have penetration, so I don't know if they need the piercing ones (that do more damage).

**Comment by jeremygurr** [comment]
Although steel doesn't have any point now, right?

**Comment by Sandman25DCSS** [comment]
Steel bolts stack with velocity/speed launcher too like flaming/freezing bolts do but I guess removing the stacking is part of the nerf

**Comment by jeremygurr** [comment]
isn't steel only to make it mulch less?

**Comment by Sandman25DCSS** [comment]
What is piercing here? Vanilla does not have it as far as I know

**Comment by Sandman25DCSS** [comment]
No, steel deals 20% more damage

**Comment by jeremygurr** [comment]
Piercing is the replacement for vorpal launchers. I'm open to better names.

**Comment by jeremygurr** [comment]
Oh, then steel is all we need.

**Comment by Sandman25DCSS** [comment]
Even 30% more. http://crawl.chaosforge.org/Steel

**Comment by jeremygurr** [comment]
Ok, I had a better idea. Maybe we keep non-elemental brands on launchers (velocity, evasion, etc), and not on ammo. Then you could use a bow of velocity with flaming arrows or poison arrows. Gives more choices, although definitely less of a nerf than before.

**Comment by Sandman25DCSS** [comment]
This is what I wrote in my first message ITT :)

> So maybe allow velocity/speed launchers? Though that might make scroll of brand weapon OP.

**Comment by jeremygurr** [comment]
haha, I guess it takes a while for me to catch up sometimes....

**Comment by Sandman25DCSS** [comment]
Speed is available on artefacts only by the way

**Comment by jeremygurr** [comment]
Done
