### ISSUE TITLE
Nerf hydra to 8 heads max

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#575]
I've just met a 9-headed hydra on nightmare. I think 8 heads should be max as in vanilla provided it is much harder to escape from it.

**Comment by jeremygurr** [comment]
But don't you have 9 headed hydras in your nightmares? All serious crawl players do :)

Maybe I can make it's head count based on depth instead of difficulty. Eventually a 9 headed hydra will be nothing for your character.

**Comment by Sandman25DCSS** [comment]
Unless it is Felid...

**Comment by Sandman25DCSS** [comment]
12-headed hydra on Swamp 2... I think I will suspend playing until it's fixed...

**Comment by Sandman25DCSS** [comment]
But yeah, I had hydrae nightmares in vanilla. When Felid petrified a hydra, tried to kill it and then found it had 17 heads when the petrification was over...

**Comment by Sandman25DCSS** [comment]
Swamp 4 would be deadly for melee character.

> The 12-headed hydra simulacrum vapourises!

**Comment by jeremygurr** [comment]
Done.

**Comment by alexjurkiewicz** [comment]
Should be 9 heads, surely, since that's a multiple of 27...
