### ISSUE TITLE
Return menu for experience potion

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#578]
It's hard to choose what to train when quaffing potion of experience because you basically don't want to train weapon skill or invocation higher than needed

**Comment by jeremygurr** [comment]
fixed in v1.5.2

**Comment by Sandman25DCSS** [comment]
Thank you

**Comment by Sandman25DCSS** [comment]
Reopening. I quaffed the potion and got my skills trained instantly:

> You feel more experienced! (262796)
> Your Fighting skill gained 4 levels and is now at level 27!
> Your Armour skill gained 2 levels and is now at level 20!

then menu opened and no experience was added to selected skills.
