### ISSUE TITLE
Crash caused by signal #11: Segmentation fault

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#58]
http://crawl.homedns.org/morgue/Sandman25/crash--20160327-165508.txt

I cannot load the game.

**Comment by Sandman25DCSS** [comment]
Oh, it loaded from 4th attempt.

**Comment by jeremygurr** [comment]
Yeah I reverted my change. For some reason the webtiles version is crashing now, even though the desktop works fine. I'll sort it out.
