### ISSUE TITLE
summoning nerfs

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#586]
Wow summoning with a bow is way fun. But I've been steadily nerfing things for them to get that delicate balance I'm looking for that still keeps things interesting. In particular I've made summoning spells cost 4x as much, although they can still be trained down to the minimum of 5 MP with enough spellcasting and intelligence. And I made power mode cost double MP, instead of just adding an SP cost. 

But there's one more thing I'm considering, that I think will make the challenge level for summoners just right. I want each time a summoned creature gets damaged, for the spell failure chance to be checked, and if the spell fails, the summon "escapes" (disappears). This forces summoners to have better fail rates than before if they want to maintain their summons for any length of time. So if a player tries to summon a bunch of creatures and then put heavy armour on, that won't work. Or if they just barely can squeak out the summons after failing a few times (with focus mode on), they still won't last long. Players can keep focus mode on to double how long they can maintain the summon of course, if they are having trouble.

**Comment by Sandman25DCSS** [comment]
I have a somewhat unrelated story. Yesterday I spectated one of the top players playing VpCK of Xom and he greatly used Lignting Spire in Lair/Orc/Lair branches. He didn't use other summoning spells before Lair 8 and a single Lightning Spire cleared Lair for him with careful play. Of course he was a hybrid and meleed things too: good EV in troll leather armour, always at alive state for increased regen and scimitar of electro at min delay but his summoning skill was about as high as Long Blades and yet it was not close to 1%. Do we want to make this playstyle impossible via extra fail checks? Do we want to allow having 4 Lighting Spires?

**Comment by jeremygurr** [comment]
I've been using lighting spires a fair bit too in Lair as a ranged attacker. I just took on a pack of death yaks with them. It's easy mode, so of course it is easy. But still, it took a death yak maybe 2-3 hits to destroy a lightning spire. If I had it down to 20% fail rate, that would still give them 5 hits on average before they would disappear. So maybe instead of 2-3 hits, it just averages out to about 2 hits for a lightning spire to disappear. I still give half of the mp back, and can often pull out another pretty quickly. So I'm not sure that the failure rate would eliminate that particular playstyle. What it does do is make it harder for a summoner to just keep a perpetual meat shield in front of the them, never facing any risk of getting hit. We'll have to play it of course to find out for sure. But in short, no, I don't want to get rid of that playstyle.

**Comment by Sandman25DCSS** [comment]
I am not sure friendly fire can be fixed. Animate dead + ranged combat is OP combo at the moment.

**Comment by jeremygurr** [comment]
I haven't worked on balancing necromancy at all yet. I think summoning is getting close to having a reasonable balance between fun yet challenging. I suspect I'll be able to do something similar with necromancy. Maybe I should just use the same mechanic for all spell based followers.

**Comment by Sandman25DCSS** [comment]
Is Summoning balanced assuming every summoner uses a longbow? Or is ranged attack balanced assuming the character has Animate Dead? I find it's weird, maybe every tool should be balanced no matter what other tools are used.

**Comment by jeremygurr** [comment]
I had an idea. I will make the fail check happen only when a player's arrow passes through a summoned creature. That way the penalty only affects ranged summoners. It will still be no big deal when a player is strong enough to have very low fail rates, but earlier on it will be harder to just throw up a meat shield and have perfect protection.

Another thing I could do, that will be even bigger for balancing out friendly fire, is to allow enemies to fire through player summons also, but not through monsters. So a centaur could still hit the player from a distance, even if there were several summons in between. So the meat shield still protects the ranged summoner from melee fighters, but does nothing to protect them from ranged, so they still have a weakness. Now often ranged attackers will target summons anyway, but not always. This doesn't make sense thematically, but maybe gameplay is improved enough to justify it.

**Comment by Sandman25DCSS** [comment]
Do you mean Felid Summoner will be unpalayble because it will die to first Centaur it meets? I wouldn't like the change.
Also what about undead, can I shoot through my allied zombies?

**Comment by jeremygurr** [comment]
Yeah the intention would be to do the same for necromancy, assuming this works. 

I don't see how a felid summoner that faced a centaur would be any more difficult than a felid monk that faced a centaur. Either way the centaur can hit the felid. Besides, if it was a felid summoner in vanilla, they couldn't have a summoned army ready when they faced a centaur anyway, They would have to take several turns summoning before they would even have a meat shield that would be effective.

**Comment by Sandman25DCSS** [comment]
> I don't see how a felid summoner that faced a centaur would be any more difficult than a felid monk that faced a centaur

The most reliable way to avoid being hit by Cenatur is to put Lightning Spire in the way. Or any other summon with low EV but Lightning Spire is the best since you choose its position.
In vanilla Centaur is much more dangerous for Mo than for Su because it takes some luck for him to shoot at you through 1-3 summons between you and him.

**Comment by Sandman25DCSS** [comment]
Or maybe I missed your point and you are saying that it is ok to nerf all Felids with ranged attack and encourage them to go Trog more often.

**Comment by Sandman25DCSS** [comment]
Though FeMo has higher Dodging/Fighting than Summoner so yes, Su will be harder :)

**Comment by Sandman25DCSS** [comment]
I've tried DgSu and it's the most OP character I ever played. Completely surrounded with small mammals on D1, then you can get Canine Familiar instantly after reaching XL 2 (using power mode for spell power boost) and later 8 Imps or Canine Familiar and 4 Imps can kill everything.

>  4470 | D:4      | Noticed Grinder
>   4514 | D:4      | Killed Grinder
>   4704 | D:4      | Found a shadowy altar of Dithmenos.
>   4731 | D:4      | Noticed Blork the orc
>   4740 | D:4      | Killed Blork the orc
>   5012 | D:4      | Noticed a phantom
>   5050 | D:4      | Killed a phantom

**Comment by Sandman25DCSS** [comment]
http://postimg.org/image/60f1tt9mp

**Comment by jeremygurr** [comment]
I know, I have not implemented most of what I'm suggesting here yet. I haven't had time. Once it's implemented, summoners will still be easier than most combos, but I think still somewhat of a challenge.

**Comment by jeremygurr** [comment]
Ok I've got an interesting solution in place now. Only summons may be shot through (not raised dead or simulacrum, god gifts, etc). When summons are shot through, the current spell failure is checked. If the spell fails, the summon vaporizes.
