### ISSUE TITLE
Monsters have tiny HP 

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#588]
> A deep dwarf berserker comes into view. (hp=9, hd=12) It is wielding an
>  enchanted mace.
> _You shoot an arrow. The arrow barely misses the deep dwarf berserker.
>  You shoot an arrow. The arrow hits the deep dwarf berserker (27)!!
>  There is a sudden explosion of sparks causing 10 damage!
> _You kill the deep dwarf berserker!
> _No target in view!
>  A deep dwarf berserker comes into view. (hp=7, hd=12) It is wielding an
>  enchanted war axe.
>  You shoot an arrow.
>  The deep dwarf berserker shouts!
>  The arrow hits the deep dwarf berserker (5).
>  There is a sudden explosion of sparks causing 20 damage!
>  You kill the deep dwarf berserker!

4 runes, nightmare

**Comment by jeremygurr** [comment]
I thought I already replied to this, but I don't see it so I'll repeat. 

I had put in all the wiki numbers, but apparently they are scaled smaller later. Should be an easy fix when I get some time.

**Comment by Sandman25DCSS** [comment]
I am not sure what you mean. [Wiki](http://crawl.chaosforge.org/Deep_dwarf_berserker) has 49-87  HP for DD berserker, not 7

**Comment by Sandman25DCSS** [comment]
Oh, I see, you put 49-87 but it was reduced to 7. Wow, that's weird.

**Comment by jeremygurr** [comment]
Funny. That field I changes was supposed to have 10x average hp. No wonder it was so far off. Fixed.

**Comment by Sandman25DCSS** [comment]
Confirmed. Thank you

**Comment by Sandman25DCSS** [comment]
Oops. Some monsters still have tiny HP.

> A deep dwarf scion comes into view. (hp=4, hd=11) It is wielding an enchanted great mace

**Comment by Sandman25DCSS** [comment]
I guess it wasn't deployed yet. Just standard DD have normal HP.

**Comment by jeremygurr** [comment]
it won't change monsters that are already spawned. But it should be fully deployed and I'm sure scions were one of them I updated. Did you go to a new floor and see the same problem?

**Comment by Sandman25DCSS** [comment]
Yes, I entered a new floor after reading your previous message where it was fixed.

**Comment by Sandman25DCSS** [comment]
Someone else will test it I guess, I cleared all fortress.

**Comment by jeremygurr** [comment]
hmm... it must still have a problem then. I'll sort it out.

**Comment by jeremygurr** [comment]
As far as I can tell, they seem to have the right hp when I went to fortress.
