### ISSUE TITLE
Damage from torment should not be increased

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#591]
Torment damage should not be increased, it should stay 50% no matter how many rune I get or what difficulty I play.
Otherwise it is not fun.

>  You begin teleporting projectiles to their destination.
>  The curse skull calls on the powers of darkness!
>  Your body is wracked with pain!
> _\* \* \* LOW HITPOINT WARNING \* \* *
>  Huge Dmg: -62%(-139hp) hp: 38%(83hp)

**Comment by jeremygurr** [comment]
Agreed. Done.
