### ISSUE TITLE
remove dragon armour from ogres and trolls

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#594]
I'm sure this will be quite unpopular, but consider my reason:

Ogres and Trolls have the early game challenge of not being able to wear normal armour, to make up for the fact that they have large hp pools and high strength. However, by late game, they get the dragon armours, which are just as good as anything that normal armour wearers get. So their major limitation completely goes away by late game, yet their big advantage, their hp, continues to grow at a rate faster than any other species, creating this situation where ogres are quite difficult before they get dragon armour, and quite easy after. I don't know if that's ideal. This would be the same as allowing mummies to suddenly drink potions halfway through the game, for no reason at all. Or Spriggans suddenly gaining a bunch of hp midgame. Thematically it makes sense that dragon armour is big, but then why couldn't you make large plate armour just as easily as making large dragon armour? It renders the body armour limitation on large species nearly meaningless. 

I propose taking away the dragon armour from ogres and trolls. Maybe they can have a little more hp to compensate, or some other kind of balancing factor, if they even need it (which I'm not 100% sure that they do). Actually, better than increasing hp would probably be to boost their strength a little more, so that they large size really is noticable. Right now a starting ogre has the same strength as a formicid, yet a formicid can wear full body armour.

This increases the difference between large species and the others, whereas now, the only big difference between late game species is that large ones have a lot more hp. It also makes a really powerful late game species a little less OP. Especially under the context of not having a level 27 cap, where an ogre can continue to gain ridiculous amounts of hp as they pass level 35 in extended game.

**Comment by Sandman25DCSS** [comment]
I am not sure I understand. Do you want to make them always wear robes and troll leather armour? That would make every Tr/Og go for statue form.
Even in dragon armour they have much worse AC than normal species because they lack boots, gloves, helmets and have awful aptitudes in Armour.

**Comment by Sandman25DCSS** [comment]
Large size gives a very significant penalty to EV, also they have very low stealth factor

**Comment by jeremygurr** [comment]
That is true, they lack all of the other ac enhancers that other species have. Maybe it's not that big of a deal then, since there is still a strong difference. 

The statue form thing brings up an interesting point. How often is it optimal for a ogre NOT to go for statue form? From what I've seen, statue form may be a bit OP. I don't think we should nerf the AC of it, but maybe we could make it slow down attack speed a little, to make it a toss up whether to go statue form or to go with dragon armour. Or maybe it is already that way?

**Comment by Sandman25DCSS** [comment]
Yes, statue form already has intrinsic slow, all actions take 50% more time.

**Comment by Sandman25DCSS** [comment]
It is optimal for Ogre not to go for statue form when it uses dragon armour ;) and it's not in extended.

**Comment by jeremygurr** [comment]
Ok I'm good with that then.
