### ISSUE TITLE
allowing casters to cast without mp, just like fighters

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#597]
More craziness to consider:

This would change the game significantly for spellcasters. I'm not sure it would be better at this point, but I'm very curious to see. So unless someone can point out a fatal flaw in this idea, I think I will try it out for a while, and we can see how it plays.

The idea would be spellcasters can continue to cast any spell, even when mp is gone, but of course they can't be in power or focus mode, and there will be a new penalty added (which will also be added to fighters). 

When a fighter _or_ spellcaster continues to fight/cast spells when out of resources, their max sp/mp will be reduced _temporarily_. Like a form of rot, that only goes away as experience is gained. Permanent spells, like summoning or trasmutations, will _not_ be available when there isn't sufficient mp. 

I would still rather just have an "exhausted mode", instead of the mp rot, but that seems to be quite an unpopular idea :)  Basically getting rid of exhausted mode just makes players always exhausted, unless they are in a power mode. I'd rather have exhausted, normal, and enhanced modes. But whatever.

It's a pretty huge buff for most spellcasters. Whether it is a good thing or not has yet to be seen.

**Comment by Sandman25DCSS** [comment]
I believe it will make game unplayable late game (it's impossible to avoid fighting at 0 stamina) and unpleasant early game (retreating as fighter after killing a couple of goblins)..

**Comment by Sandman25DCSS** [comment]
Do you remember that melee/ranged has a very serious penalty for damage/speed (not sure about accuracy) in normal mode compared to power one?

**Comment by Sandman25DCSS** [comment]
We already can tab with melee and ranged. Why should casters be alike too?

**Comment by Sandman25DCSS** [comment]
Currently I don't bother to retreat as ranger, I just press o and it restores stamina before autoexploring. If a monster comes into view, I press tab several times and then o again. With provided change I will need to retreat deep into explored territory.

**Comment by jeremygurr** [comment]
I'm not understanding these responses. What would make the game unplayable? You are talking about exhausted mode? It wouldn't be any more unplayable than playing in normal mode now, since that's basically what I'm talking about for exhausted mode, with the new normal mode being better than the current. 

Or maybe you are talking about sp rot for fighters? There would be a maximum amount of rot allowed (maybe sp max can't go below 20 for example). And it would recover fairly quickly after killing a few more bad guys. But it would strongly encourage players to stay within their limits. But maybe you are right, maybe it would just encourage players to break away after every kill to keep from having to rot their sp. 

melee / ranged have a penalty for damage and speed if they aren't in power mode (accuracy if not in focus mode). Likewise spellcasters have a penalty from damage (because of spellpower), or success chance (for focus). Are you trying to say that the melee penalty for not being in power mode is much higher than the penalty for spellcasters for not being in power mode?

People _do_ tab with conjurers with auto-magic on. It's really not that different than ranged attackers, except that ranged attackers have unlimited ammo, and conjurers don't. 

I assume the last comment was about the mp rot. Retreating doesn't work for rot. It doesn't go away with time, only as the player gains experience. So it is no different. You still just hit o after an encounter. 

But saying this, I'm more convinced now that the exhaustion strategy is better than the rotting one. Or maybe a mild hybrid of both (tiny bit of rot + tiny penalties).

**Comment by Sandman25DCSS** [comment]
Sorry about unclear responses. Yes, I was talking about stamina rot. Late areas are full of monsters so you cannot avoid fighting at 0 stamina, even casters have to switch to weapon or they will die.
Early game I would have to retreat after killing even easy monsters because getting to 0 stamina has a strategic penalty so I am greatly encouraged to start every fight at full stamina.
I know about auto-magic, it still does not work with current MP 0 so casters are unique in this regard, they must play carefully unless they are hybrids and can switch to weapon later.

**Comment by jeremygurr** [comment]
Ok let's play with this and see what works and what doesn't. Deployed now. Most parameters are easily tweaked as we find it is too much or too little.
