### ISSUE TITLE
Increase piety cost for most gods

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#599]
Most gods had relatively fast piety decay, now I can use Heroism/Finesse non-stop in Vaults 4 and still get 3 gifts without moving. I think piety cost can be increased depending on piety decay of corresponding god.

**Comment by jeremygurr** [comment]
Give some suggested increases, because I'm not familiar which which gods had fast piety decay. Should we double piety cost for Oka and Trog? For everyone?

**Comment by Sandman25DCSS** [comment]
Piety decay is described in wiki for every god, for example 

> You'll lose on average one Piety point every 320 turns, so kill often! 

http://crawl.chaosforge.org/Okawaru

I hope it is kept in one file for all gods in source code.

**Comment by jeremygurr** [comment]
it's pretty easy to change, but hard to guess what the right numbers will be. I think I'll just start with doubling piety costs for high decay gods. People can create issues for more specific problems.

**Comment by Sandman25DCSS** [comment]
Yeah, doubling can be good.

**Comment by jeremygurr** [comment]
done.
