### ISSUE TITLE
Too high damage from rune curses

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#601]
It looks like rune curse doubled damage for 9 runes on nightmare, is it expected?
1.04^9=1.42
1.06^9=1.68

> The bolt of dispelling energy hits you! (24)
> You see here an Akashic Record.
> Huge Dmg: -20%(-48hp) hp: 80%(189hp)

http://crawl.homedns.org/morgue/Sandman25/Sandman25.txt

**Comment by Sandman25DCSS** [comment]
Also

> The purple draconian zealot invokes the aid of its god against you.
> _Something smites you! (12)
>  Damage: -10%(-23hp)   hp: 79%(179hp)

and

> The purple draconian zealot invokes the aid of its god against you.
>  The damnation unfurls!
>  The damnation engulfs you! (17)
> LOW HITPOINT WARNING>  The damnation engulfs the purple draconian. (34)
>  The damnation engulfs the orange demon. (25)
>  The damnation engulfs the yellow draconian. (20)
>  The damnation engulfs the soul eater. (24)
>  The damnation engulfs the purple draconian zealot. (12)
>  The yellow draconian hits you but does no damage.
> _You hear a roar! x2
>  Huge Dmg: -15%(-35hp) hp: 59%(133hp)

**Comment by Sandman25DCSS** [comment]
Is it possible that the 1.42 modifier is applied twice? Once as boost for monster damage and another time when applying to player? 1.04^18=2.02

**Comment by jeremygurr** [comment]
No it's because hd is increased and damage is increased. For damage to be about double after 9 runes on nightmare doesn't seem too far off to me. Nightmare should be extremely difficult by the time you get to 5 runes, much more so at 9. Really challenge mode should be where nightmare is now, by the time I've got everything balanced right. And nightmare should be far beyond that. The hard part is making it still fun and winnable. But since I'm still missing many of the tools to help players make it winnable, I guess it's okay as it is for now.

**Comment by Sandman25DCSS** [comment]
Then maybe readme files should be changed, they mention 1.04 damage per rune currently

**Comment by Sandman25DCSS** [comment]
Oh, I think rune curses make 20 rune wins plain impossible. This is what happens with 9 runes and AC 70:

> The yellow draconian knight points at you and mumbles some strange words.
> The shard of ice hits you! (88)
> You partially resist.
> Huge Dmg: -60%(-141hp) hp: 36%(85hp)

**Comment by Sandman25DCSS** [comment]
According to wiki they can deal just Throw Icicle (3d25). 

> Because it deals 40% cold damage and 60% physical

http://crawl.chaosforge.org/Throw_Icicle

I had rC+ so it should have been 60% + 40%/2=80% i.e. 3d20=max 60
I got 141 instead, 235% damage assuming my AC did nothing.

**Comment by Sandman25DCSS** [comment]
Also speaking about too weak dragons:

> The fire dragon breathes flames at you.
> The blast of flame hits you! (87)
> You resist.
> Damage (61) was greater than 30% of your hp (150)!!!
> Huge Dmg: -36%(-87hp) hp: 64%(150hp)

**Comment by Sandman25DCSS** [comment]
Also I think rune curses should be disabled during orb run. Panlord with glaciate/shatter will kill everyone in 1 turn (in 2 with protection from instadeath).

**Comment by jeremygurr** [comment]
Rune curses are meant to stop the player from winning. A player must determine how many runes they think they can complete an orb run with, and shoot for that. Most advanced players should be doing very well to manage a 3 rune nightmare win. It's too easy for that at this time, but I'm working on it...

**Comment by Sandman25DCSS** [comment]
Panlords can one-shot most characters on nightmare with shatter/glaciate. It is not fun to require luck to win. Of course I haven't entered Pan/Hell/Abyss for the same reason.

**Comment by jeremygurr** [comment]
Consequently, nightmare mode has further to go than other difficulty levels to get the right balance. I have many more things to add which will empower a player to deal with such threats. But for now, nightmare players need to aim for less runes.

**Comment by jeremygurr** [comment]
I'll also reduce the rune curse damage a bit for now, which won't eliminate the problem that's bothering you, but it will allow you to get a few more runes before it's as bad.

**Comment by Sandman25DCSS** [comment]
Thank you
