### ISSUE TITLE
Shooting no arrows causes poison

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#602]
I found a shortbow without ego and poison arrows.When I shoot without arrows, it uses random brand every time.

> You shoot a poisoned arrow. The poisoned arrow hits the iguana (1).
> The iguana is poisoned.
> The iguana hisses angrily.
> You shoot an arrow of frost. The arrow of frost hits the iguana (1).
> The arrow of frost freezes the iguana. (1)
> You shoot an arrow of frost.
> The arrow of frost hits the iguana but does no damage.
> The iguana seems to slow down.
> The arrow of frost freezes the iguana. (1)
> The iguana bites your crimson imp (7)!
> Your crimson imp barely misses the iguana.
> You shoot an arrow of flame. The arrow of flame hits the iguana (1).
> The arrow of flame burns the iguana. (1)
> The iguana is no longer moving slowly.
> You shoot an arrow of frost.

**Comment by jeremygurr** [comment]
So you shot with the poison arrows, then switched to nothing and it fired random ones?

**Comment by Sandman25DCSS** [comment]
No, I have never shot with poison arrows. I just picked them up along with shortbow if that matters

**Comment by Sandman25DCSS** [comment]
I mean I never quivered any arrows

**Comment by jeremygurr** [comment]
fixed, will be deployed in 10 mins
