### ISSUE TITLE
Remove Deformed Body 2 from Ogre

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#610]
It is not fun to enchant IDA and then find that it barely gives any AC after getting to XL 15. What am I supposed to do as OgBe with 80 stamina in Exh mode? Have 5 AC/5 EV and 90% damage?

**Comment by Sandman25DCSS** [comment]
I have AC 13/EV 7 with Exh status while wearing +8 IDA and +2 cloak with Armour 4.4/Dodging 7 and Str 30/Dex 13. This is extremely unfun.

**Comment by Sandman25DCSS** [comment]
This is with 115 HP at XL 16 (Fighting 15.6), cleared D, L, O and Spiders.

**Comment by Sandman25DCSS** [comment]
I was confused many times in a row and had to quaff curing because large size means my EV is very bad and low AC means I cannot allow spiders attack me, even with rPois.

**Comment by jeremygurr** [comment]
I took it down to deformed body 1 instead. Doesn't effect current games though since mutations are given when a player reaches a certain level. The ogre has a +5 hp apt, so it needs something to keep it from being ridiculously OP. That's what the deformed body was intended to do.

**Comment by yrmvgh** [comment]
Ogres **do** have Tough Skin ... are you sure the centaur advice for Deformed here doesn't apply? http://crawl.chaosforge.org/Centaur#Difficulty_of_Play

**Comment by yrmvgh** [comment]
I guess ogres not getting gloves and boots makes it a bit different...

**Comment by Sandman25DCSS** [comment]
Thank you. Probably Ogre should not have that much HP then.

**Comment by Sandman25DCSS** [comment]
Oh, can I remove Deformed Body 2 mutation with potion of cure mutation?

**Comment by yrmvgh** [comment]
If it's changed to white text, cure mut will work, but it probably came in as a racial and will stay that way. In wiz mode (I know :cry: ) you could possibly level down and then level back up to clear it.

**Comment by yrmvgh** [comment]
Or if it's that other kind of teal color that signifies a boosted racial trait

**Comment by Sandman25DCSS** [comment]
Thank you.I will keep playing then.

**Comment by jeremygurr** [comment]
Unfortunately intrinsic mutations can't be removed with cure mut potions. It would be nice if intrinsic mutations wouldn't be saved at all, but would just be implied when you are a certain species. Then we could change them on the back end and it would immediately take effect with an update.

**Comment by jeremygurr** [comment]
Levelling down wouldn't work since it's no longer part of that species parameters.
