### ISSUE TITLE
Discussion about Lair branches

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#617]
I find it boring that I always do Spider as first branch with all my characters. How about making some Lair branches rune-locked? For example, "To enter this branch you need to have barnacled rune". Or "To enter this branch you need to have 3 runes".

**Comment by jeremygurr** [comment]
Interesting. Could definitely change some things up. Choice will be a lot more interesting as I get specific curses implemented, then you'll have to decide which curses / perks you want to go for first given a specific character. Rune locking the branches takes away some choice. Although an occasional random rune lock would make things more interesting than it hurts I think, if it's somewhat uncommon. Maybe 1/3 of branches requires 1 rune, and 1/3 of those require 2.
