### ISSUE TITLE
Early game is too easy

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#618]
> Vanquished Creatures
>   A dart slug (D:1)
>   A hobgoblin (D:1)
>   A kobold (D:1)
>   A goblin (D:1)
>   A bat (D:1)
>   A rat (D:1)
> 6 creatures vanquished.
> 
> ```
>  0 | D:1      | SlowThinker the Formicid Fighter began the quest for the Orb.
>  0 | D:1      | Reached XP level 1. HP: 10/10 MP: 80/80
> 72 | D:1      | Reached XP level 2. HP: 15/15 MP: 80/80
> ```
> 
>    222 | D:1      | Reached XP level 3. HP: 19/19 MP: 58/80
>    266 | D:1      | Reached XP level 4. HP: 24/24 MP: 68/80

**Comment by jeremygurr** [comment]
fixed
