### ISSUE TITLE
Focus/power modes seem to keep timing out

### ISSUE THREAD

**Issue by eliotn** [jeremygurr/dcssca#621]
I usually want one of these modes to be on.  Is there any way to prevent the from constantly timing out and not auto resuming when out of combat, maybe auto resume unless the player consistently cancels.

Also, I can't figure out how to do the auto resume.

Additionally, the game could use internal documentation altered to conform the new features within the game.  It seems to be sorely lacking.

**Comment by eliotn** [comment]
wait it might already do autofocus, guess I accidentally 'c' corpses

**Comment by eliotn** [comment]
Also I drank a potion of cancellation with statue form with no enemies around and it didn't cancel the form.  Is this intended?

**Comment by Sandman25DCSS** [comment]
You can cancel form via abilities menu (press a and then check menu).

**Comment by yrmvgh** [comment]
Ah yes, I used to still have "c" in a lot of my macros out of habit. That will mess you up! You no longer need to chop, btw, corpses will automatically convert into hides and weak-mut-potions at a rate similar to vanilla chopping.

**Comment by jeremygurr** [comment]
Totally agree we need more in game documentation. This is early stage development and we can use all the help we can get. The intention is to eventually have the game clear enough and in game docs good enough that a wiki will never be needed. It's a lofty goal and make take us some time to get there, but we'll get there eventually. As a small example, notice when you look at a weapon description in your inventory, that it tells you your current SP cost and the current attack speed, in addition to what it had before. Not to mention how it tells you your % chance of hitting based on your last hit on the right side of the screen. Little by little it'll improve.

**Comment by jeremygurr** [comment]
Quick mode, focus and power modes all turn themselves back on as soon as you have 50% of the needed resources, as long as you don't manually cancel them. In case you didn't already know.

**Comment by eliotn** [comment]
Also I noticed another thing, I found a ring that had the description that it increased Stamina by +1 but it actually gave much more.

**Comment by jeremygurr** [comment]
Yeah it should say +20. That's a description bug.
