### ISSUE TITLE
CA fork philosophy

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#623]
I see that there are many things that work like this:
worse than vanilla in normal mode, much worse than vanilla in exhausted mode, slightly better than vanilla in power mode OR focus mode.
AC, EV, fail rate, spell power, attack speed, melee damage, movement, basically everything I can think of.
This discourages improving characters. I mean what's the point in training Armour, Dodging or magic schools if you are still much weaker than vanilla in normal and especially exhausted mode. Better just retreat after every fight no matter how small it was and restore stamina/MP completely to be able to use focus/power mode again. If you are patient enough, you will be more powerful at XL 1 in power mode than at XL 5 in exhausted mode. Player skill does not determine much because training or even weapon choices are not as important as player's desire to spend much real time on retreating and resting.

**Comment by jeremygurr** [comment]
A valid problem. I just haven't gotten around to implementing the solution yet. 

Ok just did it. Now it is meaningless to spend much time retreating.

**Comment by G0rg0** [comment]
What is the fix exactly?

**Comment by Sandman25DCSS** [comment]
From latest changes doc:

•Retreat simplification (instant rest)
◦Instead of making it optimal for a player to retreat and recharge after every monster killed, the player is instantly fully recharged as soon as they have killed all nearby monsters. 
◦If the player kills the last known monster, and there is another just beyond the edge of LOS, it is brought to edge of LOS instead of player instant-resting.
◦If instarest doesn't happen, that means there is an invisible monster nearby or you have seen a monster, but haven't actually killed it, and it has moved out of LOS. In this case you'll have to rest the old-fashioned way.
