### ISSUE TITLE
Make sidebar Hit Chance work a bit more like To Hit?

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#641]
Right now Hit Chance shows what your hit chance was against the most recent enemy you attacked. To Hit updates with your gear and effort mode selections.

Could Hit Chance take that info from "To Hit" and use it to show what your hit chance against that same enemy would be, updated for any accuracy changes you've made?

**Comment by jeremygurr** [comment]
Unfortunately hit chance is based on many separately randomized factors. The logic is quite complex and there is no simple solution to determine what the chance percentage is for a given monster. Maybe I'll simplify the calculations at some point and that would make the chance much easier to calculate. 

I have thought it might be more useful to display averages instead based on past history. Like average damage over the past 1, 5, and 25 hits. And average chance to hit based on actual numbers. It would be a little complex for the casual gamer, but they can ignore it safely. It would be similar to how the unix uptime command worked, and would look like this: 

Damage per turn: 10.0, 7.45, 7.40
To Hit %: 80, 72, 70

then you change things and attack a couple of times, and see
Damage per turn: 12.8, 8.5, 7.62
To Hit %: 71, 72, 70

Now maybe your damage just spiked for that one hit, but your average doesn't really change much. Or maybe overall your damage is higher. 

Maybe we can insert a "predicted" value up front:
Damage per turn: (12.0) 10.0, 7.45, 7.40

of course we would have to abbreviate to have enough room:

DPT: (12.0) 10.0, 7.45, 7.40
Hit%: (75) 71, 72, 70
