### ISSUE TITLE
Gozag worshipper leaving corpses instead of gold.

### ISSUE THREAD

**Issue by G0rg0** [jeremygurr/dcssca#65]
I can't quite seem to nail down what combo of spells/actions is causing this, but it's a relatively new behavior in this game 

I thought it was related to using a battlesphere but I'm seeing it even when I don't have one summoned. Most kills are still leaving gold but I'm getting a number with corpses or no corpse _and_ no gold.

**Comment by jeremygurr** [comment]
Yes Gozag has a 50% chance of leaving the corpse or goldifying it. This is mentioned in the readme. It's long huh? 

I did this because I want to be able to use Gozag with species that would otherwise starve, or even with necromancers. If that seems too easy we can tweak the ratio a bit.

**Comment by G0rg0** [comment]
Doh, should have RTFM! That always gets me in trouble.
