### ISSUE TITLE
No monsters met during orb run

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#652]
Is it expected that I met no monsters during orb run?

**Comment by jeremygurr** [comment]
no

**Comment by jeremygurr** [comment]
I have no idea where this is coming from. When I get a chance, I'll do an orb run and then I'll be able to find out. In the meantime, if someone gets to it first and sees this problem, tell me before going much further so I can copy the save and analyze the problem.

**Comment by Sandman25DCSS** [comment]
Theoretically it is possible that I was just very lucky. Extraordinary lucky provided it was a Naga of Chei who spent 2.6 turns per move and I didn't try to optimize orb run, I just Ctrl+g to D1 and then found myself on D1. The only monster was a cursed skull on Z4 and I believe it is possible that it was a normal monster, not orb spawn.

**Comment by yrmvgh** [comment]
We have some sort of "autosave" system in the event characters need rollbacks, right? Can it be triggered to autosave a copy, say, every time a rune/orb is picked up in the event something needs to be looked at in that character/god/area? Then the player doesn't have to put the game on hold and no one has to make a new character just to test the issue found by that character.

**Comment by jeremygurr** [comment]
That is a valuable clue. No monsters spawn normally except for abyss and orb run, so I'm guessing that if you just walked normally you would have seen the spawns, but maybe auto travel doesn't generate any spawns, and so they were skipped. Maybe I can disable auto movement in orb run, or find some way to spawn monsters while auto travel is happening.

**Comment by Sandman25DCSS** [comment]
Disabling auto movement would be bad from convenience perspective. Personally I would not mind removing orb run, I suspect it is not fun to get a panlord with 118% glaciate when you have 60% HP of vanilla spriggan who cannot even run at vanilla spriggan's speed for long. And you can't even escape via stairs because it is a ranged attack which ignores EV and does not care much about AC/rC+

**Comment by jeremygurr** [comment]
So the game just ends when you pick up the orb? That's a pretty dramatic change, but with the rune curses, the player has already had to fight through so much to get to the orb, there's already been plenty of game. Removing the orb run is the easiest solution, and maybe what we should do for now. But ideally we should probably make the orb run more interesting and fun. Even in vanilla, by the time I was strong enough to complete an orb run, I usually could manage it without much trouble, just quickly dodging anything that came along.

**Comment by Sandman25DCSS** [comment]
> Even in vanilla, by the time I was strong enough to complete an orb run, I usually could manage it without much trouble, just quickly dodging anything that came along. 

I am not sure why you use `even` here :)
In vanilla orb run is infinitely easier because you can always be in hasted mode when it matters (mutations from contamination don't matter at this point), you can run away from most monsters even without haste, you can ignore most monsters and escape via stairs. Typical orb run looks like this:

> 96449 | Zot:5    | Got the Orb of Zot
>  96535 | Zot:3    | Noticed Pnuock the pandemonium lord
>  96569 | Zot:1    | Noticed Guifuiss the pandemonium lord
>  96944 | D:9      | Noticed Kobro the pandemonium lord
>  97194 | D:1      | Noticed Baik the pandemonium lord
>  97234 | D:$      | Escaped with the Orb!

or like this:

>  83295 | Zot:5    | Got the Orb of Zot
>  83346 | Zot:5    | Noticed an ancient lich
>  83358 | Zot:5    | Killed an ancient lich
>  83358 | Zot:5    | Reached skill level 22 in Fighting
>  83580 | Depths:1 | Noticed Zeolyrghu the pandemonium lord
>  83878 | D:7      | Gained mutation: You tend to lose your temper in combat. [mutagenic glow]
>  83976 | D:2      | Gained mutation: You occasionally shout uncontrollably at your foes. [mutagenic glow]
>  84036 | D:$      | Escaped with the Orb!

**Comment by yrmvgh** [comment]
Yeah, orb runs are mostly a formality - though because this is a topic we've discussed before, I visited ##crawl-dev to find out why orb runs exist. Mostly it's tradition, but 

> @amalloy  the thing is, if you remove the orb run, you are making zot:5 tele strats even stronger, to the point where it is insane not to do it

So how about this:

> |amethyst you could propose the compromise of ending the game when you take the Zot:5 stairs with the orb

**Comment by amalloy** [comment]
I don't appreciate having a single comment of mine in ##crawl-dev taken out of context here as if it were my only objection. I said a lot of things in this conversation, and so did a number of other people.

Obviously you guys are welcome to remove the orb run for dcss-ca, and it doesn't matter at all what my opinion on it is, but if you're going to use my opinion please don't take one thing I said as if it were the only thing.

**Comment by yrmvgh** [comment]
I'm just summarizing man - figured it's better to credit you than just act as if I came up with your (good!) point about tele-ninjas on my own. Next time I guess I'll make sure not to mention you, or just copy-paste the entire hugelong convo, knowing that no one will read the wall of text. :wink:

**Comment by Sandman25DCSS** [comment]
If it wasn't obvious, I suggested to end game when taking upstairs on Z$, not when picking up the orb.

**Comment by jeremygurr** [comment]
Fixed.
