### ISSUE TITLE
Should we keep a long "bikeshedding" thread to contain various minor quibbles?

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#657]
For things like little apt tweaks, questions of flavor, etc.

For instance, I've been long thinking that HO Summoning should be +2 so that it's not squeezing into the "awesome space" of a hill orc's other signature +3 apts. But that's not really worth devoting an issue to, and I can make the change myself if Gurr says "ok", but who knows, someone who's not on IRC might have an opinion about it.

And various feelings about small stones that Gorgo experiences could go here too. :smile: 

Or is it better for organization if we open individual issues for each little thing? On one hand it keeps things from getting "buried" in a thread, then again much larger issues can get "buried" on issues-pages 2 & 3 by a hill of more minor issues.

**Comment by jeremygurr** [comment]
I'd rather just have an issues for each. Then when it's resolved the issue goes away, instead of always having to read a long issue to make sure all of the items have been resolved before closing it.

**Comment by jeremygurr** [comment]
As far as the HO summoner, I just want to have at least 2 strong species in any given area. Outside of HO, we have a +2 summoner, and a +1 summoner, and all others are 0 or negative. So if a player wants to pick a strong summoner specialist, they don't have many good options. At the moment, HO is the _only_ +3 summoner. But I'm not against making a different species a strong summoner and returning HO back to normal.

**Comment by yrmvgh** [comment]
I guess my first thought would be to swap HO with Te or DE's apt. Te are already high in it. With DE it might be interesting to provide an alternative to the classic DE blaster - though maybe it risks becoming the dominant playstyle. FeSu is super fun and could maybe get the apt to encourage more people to try it out - but it's already pretty good.

**Comment by jeremygurr** [comment]
Yeah I don't want to change species that are already strong with summoning. I want to take one that is mediocre or even bad at it and change it.

**Comment by yrmvgh** [comment]
Aight

**Comment by Sandman25DCSS** [comment]
I tried FeSu but didn't like that it starts with 9 lives so I quit after one death. When you get extra life every 3 levels, you have nothing to be sorry about when you die early. When you have 9 lives total, dying even once makes me feel bad because my character becomes weaker in the long run.
