### ISSUE TITLE
Ru's -potion status is not removed when autoresting

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#659]
I killed a monster while having -potion status and all my HP/MP/SP got to 100% but -Potion status stayed.

**Comment by Sandman25DCSS** [comment]
The same happens with Invisible status

**Comment by yrmvgh** [comment]
32 5/24<> "instant" rest could burn 20 to 35 auts, just to nudge timers along, but then you might get stumbled upon (though pretty unlikely with the way rest checks for nearbys?)

**Comment by jeremygurr** [comment]
this should be good now.
