### ISSUE TITLE
Ru's abilities can be spammed

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#664]
See title. I invoked Apocalypse twice in a row

**Comment by jeremygurr** [comment]
Yeah we have a plan for that. Once I split out exhaustion from the stamina, it should work like before. It's just a bit tricky and hasn't been done yet.

**Comment by Sandman25DCSS** [comment]
Yes, I understand, I just created the issue to be sure it is not lost in IRC.

**Comment by yrmvgh** [comment]
Semi related note, if that "low stamina" threshold continues to block certain actions, it could use an indicator light both as a reminder and so that players who don't know what the SP threshold is, can learn it
