### ISSUE TITLE
Weapon description is wrong

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#665]
> A glowing executioner's axe.
> Attack delay:  Base: 2.0   Current: 1.0   Min: 1.0

As you can see it is at min delay despite I have 0 skills in Axes and 2.9 in Fighting

Demon whip is a much faster weapon and still I have 

> Attack delay:  Base: 1.1   Current: 0.9   Min: 0.5

**Comment by jeremygurr** [comment]
is the executioner's axe speed branded? Which character so I can see it?

**Comment by Sandman25DCSS** [comment]
http://crawl.homedns.org/morgue/Sandman25/Sandman25.txt

**Comment by jeremygurr** [comment]
I see two executioner's axes in that game and they are both at 1.5 delay. What am I missing?

**Comment by jeremygurr** [comment]
Maybe your character hasn't saved since you found it?

**Comment by Sandman25DCSS** [comment]
I don't have them in inventory, I used Ctrl+f to find them and then checked their description. Their brand is unknown

**Comment by jeremygurr** [comment]
I used ctrl+f to find the two I saw, but both were at 1.5 delay

**Comment by jeremygurr** [comment]
they were both in orc:1

**Comment by Sandman25DCSS** [comment]
that's because I am in statue form

**Comment by Sandman25DCSS** [comment]
without statue form they are at 1.0, I have just checked

**Comment by jeremygurr** [comment]
ah that was it

**Comment by jeremygurr** [comment]
That was a bug, but even without the bug the delay is 1.1 because of the 35 dex. Yeah I'm not sure how I feel about that. I guess the nice simple solution creates too big of a flavor problem. I'll work on it.

**Comment by Sandman25DCSS** [comment]
And that's I am without Chei :)
Currently spellcasting is the best magic skill for transmuter, it improves all Tm spells no matter how many schools they have.

**Comment by Sandman25DCSS** [comment]
I got eudemon blade from Mennas and it is at min delay with just 12.3 fighting and 2.4 long blades.

**Comment by Sandman25DCSS** [comment]
Yes, I believe current formula for success rate is really weird and Dex is too powerful for both melee and spells. I have Freezing Cloud (level 6!) at 17% (grey) with 0 Air, 0.6 Conj, 3 Ice, spellcasting 9.4 and Int 10. That would be 100% fail in vanilla but in crawl I have Dex 35...

**Comment by jeremygurr** [comment]
fixed
