### ISSUE TITLE
No Forest

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#666]
Ctrl-o screen says 

> Forest: D:11-13

but there is no Forest on those floors and I can see all 3 downstairs and all 3 upstairs on every level.
http://crawl.homedns.org/morgue/Sandman25/Sandman25.txt

**Comment by jeremygurr** [comment]
That may be a one time bug because I changed the dungeon floor count after you had begun that game (most likely). I hope.

**Comment by Sandman25DCSS** [comment]
ok. thank you
