### ISSUE TITLE
Dwarven Fortress has rune on first floor

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#669]
See title.

**Comment by yrmvgh** [comment]
Both of the Dwarf vaults that have a "rune of zot" in them already are using
`PLACE:   Dwarf:$`, so in a normal branch that would make them only show up on the bottom floor. But Dwarf used to be 1 floor, so it's probably just generating 4 floors that all use the same rules, thus each floor thinks it's the end floor?

**Comment by jeremygurr** [comment]
No the floors will still be numbered. Something is definitely fishy...

**Comment by Sandman25DCSS** [comment]
In my current game there is no rune in Dwarven Fortress.

> _Done exploring

I see all 3 upstairs.

**Comment by jeremygurr** [comment]
fixed
