### ISSUE TITLE
Sometimes monsters just stand around despite being awake, in LOS

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#672]
Noticed by lordfrikk, who may have more info

My hypothesis has something to do with the new instarest feature that zeroes monster energy

**Comment by jeremygurr** [comment]
yes it zeroes the monster energy because otherwise the monster gets a free movement immediately after being moved. Maybe I'll just cut it in half instead, so it's closer to what it would be like if you stumbled upon the monster.

**Comment by Sandman25DCSS** [comment]
I think giving monster a free movement is good, this is what normally happens in vanilla when player enters monster's view. Similarly when a monster walks in player view it is player who acts first.

**Comment by jeremygurr** [comment]
In the case of auto rest pulling a monster in, that monster may have caught up with the player anyway (without instarest), or it may not have, and the player would have stumbled on it later. Maybe then I will randomize it. Half of the time will be like the player stumbled across the monster (and it's asleep or whatever), the other half as it the monster approached the player, and it gets the first move.

**Comment by Sandman25DCSS** [comment]
As far as I know monsters cannot wake up without a reason so making 50% monsters approach the player would be a significant nerf of stealth

**Comment by jeremygurr** [comment]
Ok then I'll not wake them, just randomize the energy then.

**Comment by yrmvgh** [comment]
Nothing too strange appears to be happening with monster energy (tm)!
