### ISSUE TITLE
Speed brand does not decrease attack time

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#675]
r - the +7 war axe of Capital Punishment {speed, rElec rN+++ MP-20 Dex+4}.
Attack delay:  Base: 1.5   Current: 0.7   Min: 0.7

war axe without ego:
Attack delay:  Base: 1.5   Current: 0.7   Min: 0.7

I tried attacking with the former without statue form, it takes 0.7 indeed

**Comment by jeremygurr** [comment]
This _should_ be fixed now (hopefully). In the latest version. Possibly also in the earlier one, I can't remember.
