### ISSUE TITLE
Significant improvements to fighting and spellcasting

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#678]
I have taken the things we've learned from the last round of changes and reworked a lot of things from the ground up. Yes I know this is a pain for those who are used to things working a certain way, and instability is no fun either way. But this is a necessary part of getting this fork to where I want it to be. Overall, this should provide a significant improvement from where things were. 

Please read the cheatsheet sections about "Fighting" and "Spellcasting" for details. But basically it boils down to every aspect being governed by 2 major factors, and all factors have equal effect on the aspect they govern, and no 2 aspects are governed by the same 2 factors, greatly increasing strategic depth in these areas. Also all min-delays are reached at the same level of contributing factors. I will soon add much better in-game documentation, so people will be able to always know what to focus on to improve any given parameter. But for now, keep the cheatsheet close by.

These changes are put into a new version, so that you may finish your existing games without all the rules being changed on you mid game. However, if you'd like to transition a character straight into the new version, tell me and I can make that happen easily. 

Of course there will be new balance problems created, but for the most part they should be easy to correct. So reply to this issue if you come across a serious balance issue. To be clear, a balance issue is defined as something that significantly reduces choice / strategic options in the game. Feeling like something behaves very differently than what you are used to is _not_ necessarily a balance issue. If you don't know, feel free to ask. For example, if you start up a character and you can't even cast your level 1 spells, that's a critical balancing issue. You can also notice that with all the changes, a certain combo/part of the game is much more difficult than it really should be. 

Overall the code for these aspects is much cleaner and simpler than before, making it much easier to make adjustments to get things nicely balanced. But it is unlikely that I got all of those knobs turned to the right place on the first try, so please be patient with the numerous balancing issues which may well exist in the new version. 

If you are very frustrated with the changes and don't want to bother, you can come back in a few weeks when I have gotten things mostly balanced out myself. I will test many different combos as quickly as I can to root out balance issues and get them playable and fun. Or if you are patient, you can help me with this process by testing out things too and telling me what you find.

**Comment by jeremygurr** [comment]
I have carefully considered the input that many of you have given, and much has influenced this change. But I'm sure there are still some pain points for some of you. Just give it a try, and you may be surprised by how it plays. 

For example, you can get all weapons to min delay by only training fighting and getting some dex. That may seem OP on the surface, but you have to look at the whole picture to really understand. For starters, it takes 50 points of fighting + dex to achieve min delay. So if you start with 15 dex, and do nothing to increase it, reaching min delay will be quite difficult since you will need to train fighting to level 35. Next, the main weapon skills now have a much bigger impact on weapon damage than before, so you won't want to neglect training them, unless you don't need weapon damage, and rely purely on weapon brands to do the work. But even if you are depending on a quickblade of electrocution, maybe you don't care that much about damage, but you do need accuracy, which plays a bigger role now than before, and can only be increased by training weapon skills or adding dex. 

So there are trade offs at every turn. There's almost always an alternative way to do something, and there should almost never be a no-brainier, always the same strategy for allocation of stat points.

**Comment by MattConrad** [comment]
> For example, if you start up a character and you can't even cast your level 1 spells, that's a critical balancing issue. 

Pretty much the case with my DsIE:

> Welcome, mattchew the Demonspawn Ice Elementalist.
>  You are playing the Challenge difficulty mode, Classic experience mode 
>  The bosom of this dungeon contains the fabled artefact, the Orb of Zot.
>  Press ? for a list of commands and other information. Found 7 gold pieces.
>  Found a staircase leading out of the dungeon.
> _A goblin comes into view. (hp=4, hd=1)
>  You miscast Freeze. You are very lightly contaminated with residual magic.
> _A chill runs through your body.
> _You miscast Freeze. Nothing appears to happen.
> _You miscast Freeze. Wisps of condensation drift from your hands.
> _You miscast Freeze. You feel uncomfortably cold.
> _You miscast Freeze. You feel a strange surge of energy!
> _You miscast Freeze. A chill runs through your body.
> _You miscast Freeze. Your hands feel numb with cold.
> _You freeze the goblin (1).
> _You miscast Freeze. You shiver with cold. The goblin hits you (3).
>  You kill the goblin!
>  You freeze the goblin (7).
> _A bat comes into view. (hp=3, hd=1)
> _You miscast Freeze. Your hands feel numb with cold. The bat barely misses you.
>  You kill the bat!
>  You freeze the bat (3).
>  A hobgoblin comes into view. (hp=5, hd=1) It is wielding a club.
> _The hobgoblin shouts!
>  You miscast Freeze. You are contaminated with residual magic.
> _You feel uncomfortably cold.
> _You miscast Freeze. You feel uncomfortably cold.
>  You miscast Freeze. Frost covers your body.
>  The hobgoblin hits you (6) with a club.
> _You were prevented from receiving too much damage! (6 -> 5)
> _You miscast Freeze. You feel uncomfortably cold.
> _You miscast Freeze. Frost covers your body.
>  Clearing travel trail.
> _You miscast Freeze. Frost spreads across the the floor.
>  You miscast Freeze. You feel uncomfortably cold.
>  Your body shudders with the violent release of wild energies!
> _You feel stupid.
>  You miscast Freeze.
> _You hear a crackling sound.
>  You miscast Freeze.
>  You hear a crackling sound.

This continued on in the same pattern with a cockroach, that I somewhat miraculously managed to kill, but I'm at red contam now.

According to the spellcasting screen, my spell failure rate is only 52%, but I am pretty darn sure that isn't correct. Can't really play a DsIE like this.

**Comment by jeremygurr** [comment]
Ok DsIE should be playable now. Keep in mind that it is expected for early spellcasters to be playing in "focus" mode (see changelog-ca.md and cheatsheet.md) to reduce spell failure, until they gain enough skills to not need it.

**Comment by MattConrad** [comment]
Ah, I didn't realize that. At some point I started ignoring modes, but I've taken note of this.

**Comment by yrmvgh** [comment]
What's the scoop on Str/Int races, like Fo and LO? From a quick skim, it seems like Dex now plays a crucial role in every type of offensive attack/spell, in addition to already being the only stat that directly contributes to defense (ev).

That bit aside, the rules are MUCH more comprehensible and I will be rolling some kind of Dex-friendly race to try it out. :) I do love felids quite a bit aside from the fact that I suck at them...

**Comment by Sandman25DCSS** [comment]
Not sure if I should report it here or create a new issue but new system broke weapon balance.
Here is what I have:

> a - a +0 dire flail (weapon).
> Base accuracy: -3   Base damage: 15   Current SP cost: 2
> Attack delay:  Base: 1.3   Current: 0.7   Min: 0.6
> 
> J - a morningstar of freezing.
> Base accuracy: -2   Base damage: 14   Current SP cost: 2
> Attack delay:  Base: 1.5   Current: 0.9   Min: 0.7

So it is a 2h weapon with higher damage AND speed than 1h weapon. 

> I - a great mace.
> Base accuracy: -4   Base damage: 19   Current SP cost: 2
> Attack delay:  Base: 1.7   Current: 1.0   Min: 0.8

And that's a useless weapon. Even at min delay it is worse than Dire Flail

> b - a +4 battleaxe of flaming.
> Base accuracy: -4   Base damage: 15   Current SP cost: 2
> Attack delay:  Base: 1.7   Current: 1.0   Min: 0.8

Great, now all characters should have an axe in inventory.

> j - a +1 trident of freezing.
> Base accuracy: +1   Base damage: 9   Current SP cost: 2
> Attack delay:  Base: 1.3   Current: 0.7   Min: 0.6

And a polearm for reaching too. Almost at min delay despite I have 0 in polearms.
Speaking about weapon skill, I trained Axes only but yet I use +0 dire flail instead of +1 war axe of venom or even +4 battleaxe of flaming because base damage is much higher and though I don't know damage bonus for weapon skill, it does not matter because Axes crosstrain with M&F.

**Comment by yrmvgh** [comment]
Hm. Chei might just be too much for our fork - because stats matter more here, and losing move speed doesn't mean as much as it used to. Certainly a good candidate for temporary disabling, imo.

**Comment by Sandman25DCSS** [comment]
Also damage is probably too high.

> You cut the orc into ribbons (133)!!!!

That's for +4 battleaxe with Axes 7.8 and Fighting 11.1. Str 37.

> You chop the orc warlord into pieces (139)!!!!
>  You burn the orc warlord!!! (36)
>  You kill the orc warlord!

**Comment by Sandman25DCSS** [comment]
> Certainly a good candidate for temporary disabling, imo.

It won't help. It's possible to get a bunch of +Dex items. Stats should not replace training.

> Health: 189/189    AC: 40    Str: 20    XL:     25   Next: 56%
> Magic:  96/96      EV: 32    Int: 14    God:    Ru [******]
> Gold:   10160      SH: 12    Dex: 30    Spells: 12 memorised, 5 levels left
> 
> rFire  + . .      SeeInvis +    a - +9 eudemon blade (holy)
> rCold  + + +      Gourm    .    W - +3 warlock's mirror {reflect}
> rNeg   + + +      Faith    .    (helmet restricted)
> rPois  âˆž          Spirit   +    E - +2 cloak {rPois} (curse)
> rElec  +          Dismiss  .    I - amulet "Quicef" {Spirit +Fly rPois Int+3} (curse)
> rCorr  .          Reflect  +    M - ring "Pugum" {Wiz rC+ Str+5, =R}
> SustAt +          Harm     .    V - ring "Geggog" {rF+ rC+ Int-3 Dex+5, =R}
> MR     +....                    L - ring "Pomy" {Ice +Fly rN++ Slay+3}
> Stlth  ++++++++++               j - ring of Robustness {AC+8, =R}
>                                 i - ring of sustain attributes (curse)
>                                 m - ring of protection from magic {MR+, !d =R}
>                                 u - ring of Shadows {Umbra +Inv rN+ SInv, =R}
>                                 K - ring of Lyuciesok {Fragile rF+ MP+20 Dex+5, =R}

**Comment by Sandman25DCSS** [comment]
Oh, and all characters should have a launcher also.

> An uncursed longbow of flaming.
> Base accuracy: +0   Base damage: 15   Current SP cost: 2
> Attack delay:  Base: 1.7   Current: 1.0   Min: 0.8

**Comment by jeremygurr** [comment]
Yes damage was too high. That was a bug that has been fixed. 

And stat boosting items have been cut in half. We can easily adjust more if necessary. And chei is no problem either. All of these are minor highly tweakable items. We just need to identify the amounts and we'll be fine. 

This is good data though. It helps me to tweak things faster. 

Dex is no more important than any other stat. Each plays a vital role and careful consideration of which to invest in is more crucial here than in vanilla.

**Comment by Sandman25DCSS** [comment]
What about weapons variety? Now every character will use everything: ranged launchers, stabbing with dagger, cleaving, reaching etc.

**Comment by jeremygurr** [comment]
there is plenty of weapons variety since the most important factors are controlled by weapons skill: damage and accuracy. If they are not important enough, then we'll tweak them until they are.

**Comment by Sandman25DCSS** [comment]
Either all monsters need to be changed or the expected damage per turn should be close to vanilla. Even Iceform with Heroism in Lair deals too little damage because of 1.3 turn per attack. Normally an attack would take 0.8 turn so the fight lasted 150+% more time. Also most monsters attack once per turn so having player attack take more than 1 turn is bad because:
1)  You can no longer retreat after unlucky attack, you die to double attack instead
2) Some monsters are unkillable because of that. For example Ogre can deal 80+ damage when you attack it just once.

> _You gain the combat prowess of a mighty hero.
>  You hit the spiny frog (6). The spiny frog seems to slow down.
>  You freeze the spiny frog. (3)
>  The spiny frog stings you (22)!!
>  Damage (22) was greater than 30% of your hp (38)!!!
> _\* \* \* LOW HITPOINT WARNING \* \* *
>  Huge Dmg: -36%(-22hp) hp: 64%(38hp)
> _You hit the spiny frog but do no damage. The spiny frog misses you.
>  You hit the spiny frog (6). The spiny frog seems to slow down.
>  You freeze the spiny frog. (2)
> _The spiny frog misses you.
>  You pummel the spiny frog (18)!! The spiny frog seems to slow down.
>  You freeze the spiny frog! (8)

Both Fighting and UC were 10.4

**Comment by Sandman25DCSS** [comment]
Yes, it's currently unplayable, players should not die when they have Fighting/UC 14+ in Lair and put all bonus points into Dex for attack speed. 1.2 turn per attack is too much.

**Comment by jeremygurr** [comment]
There was a bug there. 1.5 was being used instead of 1.0 base delay for UC. That is fixed now.
