### ISSUE TITLE
Remove rPois- from Formicid

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#683]
It is not fun, seems just like a check for potions of curing. Have a potion? You live. No potion? You die. Many monsters with poisonous attack are faster than PC even in quick mode and formicids cannot blink/tele/haste.

> You are lethally poisoned!
>  Damage: -3%(-3hp)   hp: 69%(66hp)

No, I didn't die :)

**Comment by jeremygurr** [comment]
Done.

**Comment by Sandman25DCSS** [comment]
Again :(

> Damage: -12%(-12hp)   hp: 82%(78hp)
>  You feel extremely sick.
>  Nessos shoots a poisoned arrow. The poisoned arrow hits you but does no damage.
>  You are lethally poisoned!
