### ISSUE TITLE
Extreme anti-stair-dance idea

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#686]
- All normal (non-branch, non-portal) stairs are changed into escape hatches
- When all the Escape Hatches and Cursed Runes of Zot on a floor are gone, spawn a new hatch going down and a new hatch goind up (if there's another floor in that direction).

Harder to cheese with high-EV characters, pushes you to move on and not repeatedly re-use a certain spot / stair. Also makes it more clear to DCSS tourists what's going on - being surprised by the existing anti-stairdance code is a negative experience for all the newcomers I've observed (even though vets seem to mostly like it).

**Comment by Sandman25DCSS** [comment]
I think the idea has more disadvantages than advantages.
1) I entered Snakes Pit 2 as XL 18 Felid in vanilla and found that all 3 stairs are adjacent to each other and there are more than 10 monsters in view including 2 shock serpents and an anaconda. Without stairs I would die. Actually I almost died even after getting rElec and XL 23.
2) Autotravel will be broken.
3) Too similar to Ziggurats which are not even crawl.
4) New players will die when entering a branch for the first time. I think it's better to get "You stop ascending" message, it is less surprise than getting a couple of uniques on last floor as Formicid without stairs in view.
5) Less skill, more luck. Currently player needs to make decisions and has several ways to escape (agility, fear, fog, fan, invisibility, haste), with unknown location of stairs there would be too much gambling.
