### ISSUE TITLE
Monster accuracy?

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#688]
I wonder how hard it would be to display monster accuracy. I got 

> The Executioner completely misses you. x2; The Executioner misses you. x2
> The Executioner completely misses you. The Executioner hits you!
> There is a staircase leading out of the dungeon, spattered with blood here.
> Damage: -5%(-8hp)   hp: 95%(130hp)
> Unknown command.
> The Executioner completely misses you. x2; The Executioner barely misses you.
> The Executioner completely misses you. The Executioner hits you!
> The Executioner completely misses you.
> Damage: -8%(-10hp)   hp: 87%(120hp)
> Unknown command.
> The Executioner completely misses you. x3; The Executioner barely misses you. x3

vs EV 42 and I am curious how lucky or unlucky the executioner was. I think it might be useful when choosing EV or AC rings. Of course it should be an option disabled by default, otherwise too much spam.

**Comment by jeremygurr** [comment]
Done. See the right side stat bar, with the "To Hit Chance" and "Be Hit Chance" numbers.

**Comment by Sandman25DCSS** [comment]
Thank you!
