### ISSUE TITLE
Tiles are wonky.

### ISSUE THREAD

**Issue by G0rg0** [jeremygurr/dcssca#69]
Just loaded up my save (in lair) and mushrooms look like various elves, plants look like things from Snake Pit. My mummy looks like a draconian or something.

I've attached a screenshot:
![wonkytiles](https://cloud.githubusercontent.com/assets/17931524/14131025/5941ba4a-f5ec-11e5-97e0-0c887f206205.png)

**Comment by G0rg0** [comment]
Actually, everything looks wrong. Demonic crawlers look like green rats, my battlesphere looks like a spatial maelstrom etc.

**Comment by jeremygurr** [comment]
Yeah that happens when the tile order gets off. Give me 20 minutes...

**Comment by jeremygurr** [comment]
Ok try it now.

**Comment by G0rg0** [comment]
Yep, looks good. 

I see the new version is up but there is no link to edit your .rc file, is it sharing the one I've already set up for the older version?

**Comment by jeremygurr** [comment]
yeah it shares the rc file but I don't have it working to where we can play a game in each version at the same time yet. It forces us to only do one at a time. Oh well maybe that's okay.

**Comment by G0rg0** [comment]
I'll move over after I get this guy killed, thanks.
