### ISSUE TITLE
4 acquirements in a vault

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#694]
I guess something is wrong with the vault. I have never seen 4 scrolls of acquirement in view before.
![something is wrong](https://cloud.githubusercontent.com/assets/12790660/15656356/3b6c2f10-2674-11e6-949e-65c02a363a88.png)

**Comment by Sandman25DCSS** [comment]
And 3 more on another floor. Forest again.
![one_more](https://cloud.githubusercontent.com/assets/12790660/15656594/20e543b8-2677-11e6-8087-a4a65ae76d76.png)

**Comment by Sandman25DCSS** [comment]
I was wrong, not 3, but 6.

**Comment by MattConrad** [comment]
I've noticed a lot more ?acq in this most recent game. Around 10 total. OK by me! But if the adjustment wasn't on purpose, I suppose you ought to be aware of it . . .

**Comment by jeremygurr** [comment]
No it isn't on purpose. I'll lower the chances. Probably got thrown off by other scroll reductions and food reductions we have done.
