### ISSUE TITLE
Remove friendly fire protection

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#695]
It is ridiculous, I can target fireball through my zombies, I can hit them with fireball, I can hit them with fire storm and they stay healthy and friendly.

**Comment by yrmvgh** [comment]
Friendly fire could be a lot less annoying if projectiles and beams "warp" around allies like they currently do around walls, so that any clear path to the target is valid, instead of only the most direct path - (which your allies tend to travel on.

**Comment by jeremygurr** [comment]
That is a bug. Fireball should be hitting friendlies.

**Comment by jeremygurr** [comment]
Fixed.
