### ISSUE TITLE
Hell effects are too powerful vs Dex

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#697]
Now that Dex is equivalent of average skill level for the purpose of spell failure hell effects with their stat draining are extremely unpleasant. I lost 9 Dex, now even level 8 spells are uncastable while before I had level 9 spells at grey.

**Comment by Sandman25DCSS** [comment]
Do we really want to encourage scamming Abyss for XP?

**Comment by jeremygurr** [comment]
Abyss scumming should not be possible. Probably should just eliminate all xp in abyss. 

Problem #2: I'll cut stat drain in half for hell effects. 

Done.

**Comment by Sandman25DCSS** [comment]
> Abyss scumming should not be possible. Probably should just eliminate all xp in abyss. 

Not sure about it. It is useful to kill something to get some stairs generated. Otherwise we will get back to 3 hours for getting the rune.
