### ISSUE TITLE
Orc Mines 5 gives experience

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#698]
See title.

> You kill the orc warlord!
>  Your Shields skill increases to level 17!

**Comment by jeremygurr** [comment]
It does train skills, but doesn't advance your experience level. We could remove skill training too if you think we should.

**Comment by Sandman25DCSS** [comment]
Skills are much more important than XL, so it makes clearing all those levels very useful. It had lots of warlords so not easy XP but still there is too much XP already with all those extra branches.

**Comment by jeremygurr** [comment]
fixed.
