### ISSUE TITLE
!r annotation does not prompt confirmation

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#700]
See title.
I have !r inscription on all my scrolls and now it does not prompt me to confirm reading.

**Comment by jeremygurr** [comment]
that slipped in with the vanilla code merge. They significantly changed the code that handles all item usage. I'm guessing they missed this. It will probably be fixed upstream soon.

**Comment by jeremygurr** [comment]
I _could_ reverse what they did in this particular instance, but that could have long term impacts elsewhere.

**Comment by Sandman25DCSS** [comment]
No, it's ok. The "nightmare" game was too easy, I had 200+ spell power with Int 33, magic schools slightly above 20 and just one enhancer, casting fire storms every 0.7 turn. In vanilla that would be about 100 spell power and 1 turn. So I suspend playing until the fork is harder for casters and easier for melee, sorry.
