### ISSUE TITLE
HD is not increased with runes

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#701]
I have 17 runes so } screen lists "Rune curse effects:  hd: +17   hp: 140%   damage: 140%" but still I got 

> A Hell Sentinel comes into view. (hp=158, hd=19)

**Comment by Sandman25DCSS** [comment]
Also for some reason Hell Sentinel is vulnerable to fire???

**Comment by jeremygurr** [comment]
hell sentinel bug fixed. 

I tested the hd thing a bunch and it seems to be working properly for what I've tried anyway. All monsters are created when you first enter the floor. If you had come to this floor when you had less runes, and then came back, the monsters would still be at the lower hd. There's no chance that this happened? No it's extremely unlikely. Hmm... that must mean there is an alternate way that monsters are being created that I'm unaware of.

**Comment by Sandman25DCSS** [comment]
It was last level of some hell branch and the hell sentinel had normal HD 19. I am pretty sure I haven't entered the floor with 0 runes :)

**Comment by Sandman25DCSS** [comment]
Maybe it was created by hell effect, not sure if it uses the same code.

**Comment by jeremygurr** [comment]
I think this is fixed now.
