### ISSUE TITLE
Crashes during orb run

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#702]
There were several crashes during orb run on Zot  6 and Zot 5. Unfortunately it looks like chash files have not generated.

By the way, I really like new orb run, though probably it should disable scrolls of magic mapping also.

**Comment by jeremygurr** [comment]
Cool I'm glad you like it. Now we just got to get those crashes worked out. What was happening just before the crash? Any idea what could have triggered it? Oh it was when you were trying to cast tornado? Well someone was crashing it with tornado. Hmm... I might have an idea.

Ok I fixed the tornado bug. If that was your issue then it should be good now. I think you already finished that game though, huh?

**Comment by Sandman25DCSS** [comment]
The new orb run was really scary: where to go, where are all the stairs? :)
Yes, the game is finished. Once it crashed when I tried to enter a new floor, once when I was just moving manually.

**Comment by jeremygurr** [comment]
Well I cleared the previous core dump, so hopefully if it happens again I can catch it.
