### ISSUE TITLE
Berserk Potion did not take effect

### ISSUE THREAD

**Issue by yrmvgh** [jeremygurr/dcssca#706]
possibly due to 0 sp

_The killer bee poisons you! The killer bee stings you but does no damage.
 It was a potion of berserk rage. The killer bee stings you (5).
- \* \* LOW HITPOINT WARNING \* \* *
  _The killer bee completely misses you.
  You puncture the killer bee (7)! You feel sick.
  The killer bee stings you but does no damage. The killer bee stings you (5).
- \* \* LOW HITPOINT WARNING \* \* *

**Comment by jeremygurr** [comment]
should work now. Potions should always work independently of resources.
