### ISSUE TITLE
Casting Beastly appendage while already having it wastes a turn

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#709]
> Your form becomes more stable.
>  You are already in that form, and it's as stable as it can get.
> _The hobgoblin completely misses you.

**Comment by jeremygurr** [comment]
That's odd. I can't seem to reproduce this one. Each time I try it, no time advances and no monsters can move.

**Comment by Sandman25DCSS** [comment]
Oh, I cannot reproduce it either, maybe I missed something first time. Thank you for taking a look into it.
