### ISSUE TITLE
Yred is nerfed

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#711]
Yred's Animate Dead created zombies which expire in 27 turns, that's too little time.

**Comment by Sandman25DCSS** [comment]
Not sure if gifts were changed. I got bone dragons much earlier than in vanilla

**Comment by jeremygurr** [comment]
fixed. Not sure what's going on with the gifts since those haven't changed.

**Comment by jeremygurr** [comment]
It appears like yred's animate dead is meant to last indefinitely. Maybe we want this, or maybe we don't, we'll have to see how it plays out.

**Comment by Sandman25DCSS** [comment]
Yes, that's the power of Yred, it is god of undead army.
