### ISSUE TITLE
No way to leave zombies on previous floor

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#714]
I tried to enter a new floor without zombies and Yred's allies but I can't, I told them to wait, told them to retreat, nothing helps.

**Comment by jeremygurr** [comment]
There isn't currently any simple way to do this. Probably would be valuable, but it would take some significant effort, or someone that really knows what they are doing with the code.

**Comment by Sandman25DCSS** [comment]
I see, Yred/Beogh is unplayable then

**Comment by Sandman25DCSS** [comment]
In case it isn't clear, those 2 ways work in vanilla.

**Comment by jeremygurr** [comment]
I just figured out an easy way to do it. See the changelog for details.
