### ISSUE TITLE
Melee balance

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#715]
Melee balance is very bad early game, I am XL 7 HO (+2 Fighting aptitude, +3 Axes aptitude) and it still takes 1.5 turn per attack despite I trained Fighting (7.1) and Axes (6.0) only, also put all bonus points into Dex for attack speed. 

Vs Ogre.
In vanilla with Figthing 2.4 (starting value)

```
Attack: Hill Orc Gladiator vs. ogre (4000 rounds) (2016/06/05/13:26:10)
Hill Orc Gladiator: XL 1   Str 17   Int 8   Dex 11
Wielding: +0 war axe, Skill: Axes
ogre: HD 5   AC 1   EV 6

      Axes | AvHitDam | MaxDam | Accuracy | AvDam | AvTime | AvSpeed | AvEffDam
         0 |      5.5 |     14 |      70% |   3.8 |   150  |  0.67 |      2.6
         1 |      5.6 |     14 |      70% |   3.9 |   145  |  0.69 |      2.7
         2 |      5.5 |     14 |      70% |   3.9 |   140  |  0.71 |      2.8
         3 |      5.7 |     15 |      71% |   4.1 |   135  |  0.74 |      3.0
         4 |      5.7 |     15 |      73% |   4.2 |   130  |  0.77 |      3.2
         5 |      5.6 |     16 |      74% |   4.2 |   125  |  0.80 |      3.4
         6 |      5.9 |     17 |      74% |   4.3 |   120  |  0.83 |      3.6
         7 |      6.0 |     17 |      74% |   4.5 |   115  |  0.87 |      3.9
         8 |      6.2 |     18 |      74% |   4.6 |   110  |  0.91 |      4.2
         9 |      6.2 |     18 |      74% |   4.6 |   105  |  0.95 |      4.4
        10 |      6.3 |     18 |      74% |   4.7 |   100  |  1.00 |      4.7
        11 |      6.6 |     19 |      75% |   5.0 |    95  |  1.05 |      5.2
        12 |      6.6 |     20 |      76% |   5.0 |    90  |  1.11 |      5.6
        13 |      6.7 |     19 |      75% |   5.1 |    85  |  1.18 |      6.0
        14 |      6.7 |     21 |      76% |   5.1 |    80  |  1.25 |      6.4
        15 |      7.1 |     21 |      78% |   5.5 |    75  |  1.33 |      7.4
        16 |      7.0 |     22 |      78% |   5.5 |    70  |  1.43 |      7.8
        17 |      7.3 |     22 |      76% |   5.6 |    70  |  1.43 |      8.0
        18 |      7.5 |     21 |      78% |   5.9 |    70  |  1.43 |      8.4
        19 |      7.4 |     22 |      78% |   5.9 |    70  |  1.43 |      8.4
        20 |      7.6 |     24 |      78% |   6.0 |    70  |  1.43 |      8.5
        21 |      7.6 |     24 |      79% |   6.0 |    70  |  1.43 |      8.6
        22 |      7.9 |     25 |      78% |   6.2 |    70  |  1.43 |      8.9
        23 |      7.9 |     25 |      80% |   6.4 |    70  |  1.43 |      9.1
        24 |      8.1 |     25 |      79% |   6.4 |    70  |  1.43 |      9.2
        25 |      8.2 |     25 |      79% |   6.5 |    70  |  1.43 |      9.3
        26 |      8.5 |     27 |      79% |   6.8 |    70  |  1.43 |      9.7
        27 |      8.4 |     27 |      81% |   6.8 |    70  |  1.43 |      9.8
```

In CA with Fighting (7.1) and Axes (6.0), Str 17, Dex 13:

```
           AvHitDam | MaxDam | Accuracy | AvDam | AvTime | AvSpeed | AvEffDam
 Attacking:      5.0 |     12 |      80% |   4.0 |   150  |  0.67 |      2.7

This is worse than XL 1 vanilla.
```

**Comment by Sandman25DCSS** [comment]
I realize you are not going to have the same balance as vanilla but it is hard to be on D6 with corresponding monsters when your power is like on D1 in vanilla

**Comment by Sandman25DCSS** [comment]
Something is very wrong, I set my Fighting to 15 and Axes to 15 and still got:

```

            AvHitDam | MaxDam | Accuracy | AvDam | AvTime | AvSpeed | AvEffDam
Attacking:      5.9 |     14 |      89% |   5.3 |   130  |  0.77 |      4.1
```

**Comment by Sandman25DCSS** [comment]
This is ridiculous, Fighting 25 and Axes 25.

```
            AvHitDam | MaxDam | Accuracy | AvDam | AvTime | AvSpeed | AvEffDam
Attacking:      7.1 |     16 |      93% |   6.7 |   120  |  0.83 |      5.5
```

**Comment by Sandman25DCSS** [comment]
> a - a +0 war axe (weapon).
> 
> A military axe with a long haft and a single-bladed head. 
> 
> Base accuracy: +0   Base damage: 11   Current SP cost: 2
> Attack delay:  Base: 1.6   Current: 1.2   Min: 0.8

**Comment by Sandman25DCSS** [comment]
Max damage 16, really???
XL 1 vanilla HOGl has max damage 15 :)
With Fighting 25 and Axes 25 max damage would be 44.

**Comment by Sandman25DCSS** [comment]
```
           AvHitDam | MaxDam | Accuracy | AvDam | AvTime | AvSpeed | AvEffDam
Attacking:     11.0 |     44 |      83% |   9.2 |    70  |  1.43 |     13.1
```

**Comment by jeremygurr** [comment]
Okay I buffed it a bit. The intention is that standard mode shouldn't be too far off from vanilla damage wise. Nightmare of course is intended to be quite a bit harder. 

I'm not sure that your fsim numbers are accurate though, since it quickly exhausts the player and then all following numbers are based on exhausted status, which naturally should be much lower than damage done if you are not exhausted. I'll see if I can't get fsim to work in a bit more reasonable way here.

**Comment by jeremygurr** [comment]
Ok so a HOFi in _standard_ difficulty with str 17, dex 13, fighting 7.1, axes 10, you get avg dam 4.9. Taking axes to 20, you get avg dam 6.2. Taking fighting to 20, you get avg dam 7.2. Taking difficulty up to nightmare changes that to 4.6. Yes, that makes things quite a bit harder than standard mode, and that is intended.

**Comment by Sandman25DCSS** [comment]
It means players must avoid training Fighting/Axes, the increase from 4.9 to 7.2 is almost nothing, for nightmare even worse. In vanilla damage would be 11.6 with Axes/Fighting 20.
Does magic suffer from similar problems? If it does, then training magic to high levels does not make much sense either. It looks like everyone should be a hybrid since there is nothing to train and we have MP and stamina pools.

**Comment by Sandman25DCSS** [comment]
Oh, fsim with 0 stamina is fine, I have just checked and found that I can attack only 10 times before my stamina runs out on D6. It encourages stupid tactics like luring several monsters in the open to attack them simultaneously, corridors are bad ;)

**Comment by MattConrad** [comment]
I find the new system weird. It is strange to have Fighting at 16 and still have a broad axe at > 1 turn delay.

I don't think I could have gotten my recent MiBe very far if it weren't for an extremely lucky early acquirement. It's hard to get melee off the ground, and even now using axes is dicey. I am playing on Challenge, maybe this is above my pay grade.

It's funny that Sandman hybrids are good, I like hybrids, but to me they are not workable because you have to invest so deeply in Fighting to get your attack speed remotely tolerable. That's something that might be :( about CA.

I don't have a strong opinion about what changes are needed (maybe a bigger spread in base weapon delays?), and I'm fine with seeing how things evolve, but it does feel "weird" right now. Maybe that's something to get used to, dunno.

**Comment by Sandman25DCSS** [comment]
No, I didn't mean that my hybrids are good. I meant that it does not make much sense to invest much into skills because high level skills are very expensive but are not that helpful. So it is better to have 5-10 in all skills instead.

**Comment by jeremygurr** [comment]
It's easy enough to increase damage scaling with skill levels. I'll try cranking that up a bit and we can see how that goes. Spellcasting was apparently too powerful that way, so I have scaled that down a little. 

I'll have this change in place late tonight.

**Comment by jeremygurr** [comment]
Ok it's increased now. Basically every 10 points of weapon skill adds 50% base damage. However, since your accuracy also goes up with weapon skill, the effective damage is more than that, especially for hard to hit monsters.
