### ISSUE TITLE
Sometimes HP stays elevated after berserk wears off:

### ISSUE THREAD

**Issue by MattConrad** [jeremygurr/dcssca#716]
Right now my MiBe should have 132 HP, but has 198:

Health: 198/198    AC: 33    Str: 31    XL:     18   Next: 25%

I've noticed this several times while playing this char. Earlier it wore off very quickly. Now it seems to be sticking around longer. Maybe it wears off when I take damage, my AC is a lot higher than it was.

**Comment by jeremygurr** [comment]
fixed

**Comment by MattConrad** [comment]
Can't check this right now but I'll reopen later if I see it again.
