### ISSUE TITLE
 DCSS:CA v1.1 supposed to be running yet?

### ISSUE THREAD

**Issue by G0rg0** [jeremygurr/dcssca#72]
I can click the link and get the loading screen but then it just drops me back to the lobby.

**Comment by jeremygurr** [comment]
It only lets you run one version at a time. Are you sure the v1.0 character is ended?

**Comment by G0rg0** [comment]
It is, got confused by some trantellas and was tired of the mana-grind at that point. 

It _will_ let me start a v1.0 game.

**Comment by G0rg0** [comment]
Just made a test account and had the same issue, so it's not related to my account.

**Comment by jeremygurr** [comment]
Ok I fixed it.

**Comment by jeremygurr** [comment]
Oops, broke it again...

**Comment by jeremygurr** [comment]
Ok I finally fixed the issues.
