### ISSUE TITLE
Killing a skeleton causes a mummy death curse.

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#73]
You destroy the hill giant skeleton!
 The curse on the +2 cloak of Starlight {rElec rC+ EV+4 Stlth--} has been
_lifted!

Isn't the curse expected to happen only when killing some kind of mummy?

**Comment by jeremygurr** [comment]
hehe no, curses go away automatically based on experience gain. The curse being lifted is a _good_ thing. It means it's no longer cursed. So when killing something that gives you a lot of experience, the same way that draining diminishes with experience, it is more likely to show that the curse has been lifted.

**Comment by Sandman25DCSS** [comment]
Oh, nice. Thank you for the explanation.
