### ISSUE TITLE
Too high rune requirements

### ISSUE THREAD

**Issue by Vollch** [jeremygurr/dcssca#733]
I'm stuck in my current [game](http://crawl.homedns.org/morgue/Vollch/Vollch.txt). Shoals asks for 7 runes, Swamp asks for 10 runes, Orcish mines asks for 3 runes, while i've been able to get only one rune from snakes(this one had free entrance). So, only branch i can go next it's Abyss - with distort weapon. But even with that second rune it still won't be enough to open orcish mine.

**Comment by jeremygurr** [comment]
Oops, orcish mines should never have a requirement. Good catch.

**Comment by jeremygurr** [comment]
Ok it's fixed now, your game should work, at least allowing you past orc.

**Comment by Vollch** [comment]
Yeah, thanks.
