### ISSUE TITLE
Rune curses disappears after save & load

### ISSUE THREAD

**Issue by Vollch** [jeremygurr/dcssca#734]
Subj. Descended on cursed ladder, got curse, " confirms. Save, load. Nothing in ", and that ladder(after ascending back) warns about curse again.

**Comment by jeremygurr** [comment]
I need to know which branch it was.

**Comment by Vollch** [comment]
Well, i didn't actually checked every branches whether it asks about again, but it defenetly happened in vault and fortress.

I think it's all of them. I've got 8 runes, and now(after break, i.e. save and load) game shows me: "you are not affected by any rune curse".

**Comment by jeremygurr** [comment]
Fixed.
