### ISSUE TITLE
Mummies immunity to curses prevents Ash worship.

### ISSUE THREAD

**Issue by G0rg0** [jeremygurr/dcssca#74]
I'd rather be able to worship Ash than have the curse immunity. Scrolls of remove curse are common enough that it's not a big deal to wear ID things.

Among the other benefits (Ash is one of the best Gods imho), it is one of the best (only?) ways to deal with confusion. The removal of the clarity amulet is really rough on undead due to no potions.

**Comment by jeremygurr** [comment]
I suppose it wouldn't hurt to just cancel the immunity when they worship Ash. It was just a flavor thing, but flavor isn't more important than gameplay.

**Comment by G0rg0** [comment]
Yeah that would work, just remove the immunity when worshipping ash. I do like the flavor - immunity to curses makes sense for a mummy.

**Comment by jeremygurr** [comment]
done
