### ISSUE TITLE
halfling is a little too hard

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#77]
move wild magic to level 4 to give them a fighting chance at the beginning. Increase conjuration apt since they are so naturally good at elemental magics, and very few species have decent conj apt.

**Comment by jeremygurr** [comment]
Okay I now have wild magic at 6, 12, and 18. This makes it much easier, even though it's still a challenge.

**Comment by Sandman25DCSS** [comment]
I am not sure about the challenge, with right combo (caster of Vehumet) it makes them extremely powerful.
