### ISSUE TITLE
Troll's hunger is really unpleasant

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#78]
New Troll has very few HP so unlike standard crawl it is a very bad idea to explore when wounded during middle and late game . Also it has quite good magic aptitudes so Troll caster is very nice and as you know MP regeneration is very food-consuming. Unfortunately increased hunger does not work well with all that, even for TrEE of Vehumet with most XP in Spellcasting.

So I suggest to remove or decrease Troll's hunger, it is no longer a fighter with huge HP.

**Comment by jeremygurr** [comment]
I agree. The hunger issue will be addressed more completely in upcoming changes. For now I'll set the troll hunger to the same as if they had a regen amulet on. 

Done. Since it's a mutation change it won't apply until you start a new troll character unfortunately.

**Comment by Sandman25DCSS** [comment]
Do you plan to add similar mutation to Vine Stalker? Troll actually has less HP than VS, less Regen (2 vs 3) and no anti-magic bite to restore MP.

**Comment by jeremygurr** [comment]
Wasn't planning on it. I like the VS as it is right now. 

Do you think we need to buff Troll a bit? Troll has unparalleled innate resistances that should help a lot, but should I boost the health 25% higher?

**Comment by Sandman25DCSS** [comment]
No, I wouldn't like to buff Troll's HP, it is the hardest species by far and this is good.
I would like Troll with normal hunger OR VS with hunger penalty too.

**Comment by jeremygurr** [comment]
Yeah I like troll being a late game challenge species. 

I changed troll to have standard regen hunger. Do you think it should be less, to be normal non-regen hunger, or is it okay like it is?

**Comment by Sandman25DCSS** [comment]
Troll is challenging during middle game also, at XL 16 (cleared D, L, O and Snake 3) it has rC++ (standard crawl has rC+) and that's it.
Normal non-regen hunger would be better IMHO. Troll can no longer kill everything non-stop to get corpses, especially as caster at full HP and almost zero MP.

**Comment by jeremygurr** [comment]
Okay I'll give them free regen then and start their resistances a little earlier. That should help.

**Comment by Sandman25DCSS** [comment]
Is it possible to give resistances based on difficulty and don't change them for hard? I think Tr is winnable as is, it's just unpleasant to deal with hunger issue.

**Comment by jeremygurr** [comment]
Not with the current way it is implemented. I can keep them the same for now if you prefer that.

**Comment by Sandman25DCSS** [comment]
Yes, please keep them the same then. Thank you for your patience ;)

**Comment by jeremygurr** [comment]
Ok changes deployed.
