### ISSUE TITLE
lightning and shock spells need to be more different

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#79]
Lightning and shock behave exactly the same as far as I can tell. Since I've removed the spell caps, there is no difference. We need something that sets lightning apart from shock. Maybe shock does significantly more damage than lightning (at the same power level), but only works close range (1 space away), where lightning gives you the awesome blast through multiple enemies / bounce off walls effect. Shock should not have the bouncing property to keep lightning distinct. Like all spells, I want shock to retain it's usefulness throughout the game if possible, so lightning shouldn't just be a direct replacement for shock. Both should ignore dodging, but not armour.

**Comment by Sandman25DCSS** [comment]
I used both spells all the way into Zot, I believe current balance is fine. If I wanted to kill something fast, I used Lighting Bolt since it deals more damage. If I had time to save MP, I used Shock, even 3 casts save you 40% MP comparing to Lightning Bolt.
Both spells ignore 50% AC and don't ignore Dodging.

**Comment by Sandman25DCSS** [comment]
Also Shock is a much better spell in dangerous terrain since it is almost silent, unlike extremely loud Lightning Bolt.

**Comment by Sandman25DCSS** [comment]
http://crawl.homedns.org/morgue/Sandman25/morgue-Sandman25-20160328-001424.txt

**Comment by Sandman25DCSS** [comment]
Shock             |       |       |    63 |   597 |   882 |   349 |   358 |   280 |    64 ||  2593
       Lightning Bolt    |       |       |     2 |    25 |    28 |     7 |    18 |       |    34 ||   114

**Comment by jeremygurr** [comment]
Maybe I'll leave it for now then until I later do a more comprehesive element change.
