### ISSUE TITLE
Crash on game start

### ISSUE THREAD

**Issue by alexjurkiewicz** [jeremygurr/dcssca#8]
```
dcss-dcssa/bin/../dat/des/branches/abyss.des:1506: Map 'grunt_abyss_rune_wretched_hive' is too big for the Abyss: 28x17 - max 27x22
```

cc / @Sandman25DCSS

**Comment by jeremygurr** [comment]
Interesting. Okay I think I fixed it. Try that out and tell me if it works.

**Comment by alexjurkiewicz** [comment]
testing now. PS thanks for keeping the README up to date, I think that's the number 1 way people will learn about what this fork changes

**Comment by alexjurkiewicz** [comment]
fixed, thanks
