### ISSUE TITLE
Curse item ability from Ash doesn't seem to work. 

### ISSUE THREAD

**Issue by G0rg0** [jeremygurr/dcssca#80]
I have scrolls or remove curse, but when I select the item to curse, it drops to:

"Curse which item? (1 remove curse scroll left) (Esc to abort) (? for menu, Esc to quit)"

When you hit ? it brings up the standard help menu, not a list of your inventory items to curse. It also burns one of your scrolls without actually cursing anything.

**Comment by jeremygurr** [comment]
Try it now.
