### ISSUE TITLE
Wand of teleportation has 5 max charges

### ISSUE THREAD

**Issue by Sandman25DCSS** [jeremygurr/dcssca#84]
I am not sure it is really needed, scroll of teleportation is a common resource so spending a rare scroll to get 9 teleportations does not seem OP

**Comment by jeremygurr** [comment]
That should only be after it has been recharged once. Each recharge should cut in half the max charges. You found a new wand that only has 5 max?

**Comment by Sandman25DCSS** [comment]
I read-IDed a scroll of recharging and used it on a want of tele with 7 zaps. Now I have the wand with 5 zaps instead of 7, quite frustrating. Scroll of recharging does not seem much more common than wand of tele/haste/heal. How about making it always give N charges instead of "fully" recharging a wand while making it actually have 5, 2 or 1 max charges? It is not fully recharging really.

**Comment by jeremygurr** [comment]
It was supposed to put it at whatever it's maximum was before cutting the max in half, so that should have ended up at 9 charges. Strange, that is a bug. In all my tests it worked right, so it must have something to do with the scroll being unidentified first.

**Comment by Sandman25DCSS** [comment]
Sorry, I am not absolutely sure, I recharged it yesterday but noticed the 5/5 zaps only today. Perhaps my memory causes some problems but at least I don't remember that I recharged it again.
