### ISSUE TITLE
avoiding tab deaths

### ISSUE THREAD

**Issue by jeremygurr** [jeremygurr/dcssca#91]
Dying because you tabbed one too many times (and didn't have warnings or more messages set up properly), is a dumb reason to die. Crawl _should_ punish a player for conscious tactical or strategic mistakes, but not for unavoidable deaths or interface based weaknesses. 

Now I know that crawl has a number of solutions for this (warn when health is below 50%, force more messages, etc.), but these are not going to be there for a newbie, and even for me I get annoyed by the forced more messages, so turn them off, only to die because of tabbing once too many times. Yeah I know, it's dumb, but I don't think that there is any value in the game punishing the player for a interface weakness. 

I propose we find a better way to warn the player, that still allows them to tab to death of that's what they really want, but makes it **very** clear that they are likely to die if they don't do something drastic. Sandman has a script that shows on the message list all powerful damage events against the player. This is a step in the right direction, but even watching the messages can be a bit much sometimes. What if the screen borders turned red for 1 second after each major hit, or each hit? Now if a player dies after many small hits that slowly erode their health, I'm totally fine with that. I'm more worried about the unusual cases where a monster does much more than the expected amount of damage right away, where 2 tabs mean death.  Or we could draw wavy lines pointing to the player from each direction, like a sun, surrounding the player, taking up 1/3 of the screen to be very obvious. Since the player is usually focussed on their character on the screen, indicators around their character are most effective. 

I think this should be done _in addition to_ an added message similar to what Sandman has pop up when a big hit happens. 

Here's another possible approach: The game has two basic modes: normal fighting mode, and danger mode. Danger mode is entered as soon as a "big hit" happens, or when health gets below a preset amount (the warning config in the rc file). Danger mode displays a bright red border around the screen and/or some kind of visual indicator immediately around the player. But entering danger mode forces the player to pause to 1 or 2 seconds, or to press a specified key, like enter to continue. Then once in danger mode, there are no further interruptions to gameplay. Of course danger mode is left when no damage is done to the player for a number of turns. Then when they enter danger mode again, there is the prompt again. Of course this can be disabled in the rc file, but should be the default behavior for new players. 

New players should not have to touch the rc file. Sensible defaults should be in place already.

**Comment by Sandman25DCSS** [comment]
You may want to take a look at "flash_screen_message" option (https://gitorious.org/crawl/crawl/source/e683cc4b791a64578382bcb7ba05d792877ddc7f:crawl-ref/docs/options_guide.txt?p=crawl:crawl.git;a=blob;f=crawl-ref/docs/options_guide.txt;h=146471989ed56d0d3c475855904220fbca74c676;hb=HEAD#l1437) which I added to deal with distortion weapon but it can be easily used to deal with low HP or anything else. Also autofight_stop default value is too low IMHO. https://gitorious.org/crawl/crawl/source/e683cc4b791a64578382bcb7ba05d792877ddc7f:crawl-ref/docs/options_guide.txt?p=crawl:crawl.git;a=blob;f=crawl-ref/docs/options_guide.txt;h=146471989ed56d0d3c475855904220fbca74c676;hb=HEAD#l1155
For example, flash_screen_message+= low hit points warning

**Comment by Sandman25DCSS** [comment]
By the way, several years ago I was playing with RC file which would automatically save game for me when my remaining HP was less than 150% of damage I received during last turn. So I had to load the game again and of course it meant that I didn't die recklessly.

**Comment by Sandman25DCSS** [comment]
You can see an example of game http://dobrazupa.org/morgue/Sandman25/morgue-Sandman25-20141020-003407.txt
  2466 | D:3      | =================== Autoexit: lost:19 current:19

**Comment by jeremygurr** [comment]
Yes these are along the lines of what I'm talking about. I'd like to establish a solid default behavior best suited for new players, which is of course configurable for experienced players. 

What about a default of flashing red, and a forced 2 second pause for entering "danger mode", which only happens once, until danger mode is entered again? And a simple: danger_mode_warning=true setting. Danger mode would be triggered when HP < 150% of damage of the last turn. Or I suppose that could be an option too: danger_mode_threshhold=150. It would also have a message each time danger mode is triggered: Danger!!! Last hit (18) was greater than 150% of your remaining health (20). Danger mode is turned off after there has been no damage to the player for 10 turns. For new players, maybe 200% is a better starting point.

**Comment by jeremygurr** [comment]
We'd probably just have one setting: danger_mode_threadhold. When it is 0, the warning is disabled.

**Comment by Sandman25DCSS** [comment]
Sounds good, I like it.

**Comment by jeremygurr** [comment]
Deployed
