### ISSUE TITLE
Should passwall be interruptable?

### ISSUE THREAD

**Issue by G0rg0** [jeremygurr/dcssca#93]
Seems like the whole reason for passwall is to allow for escape in bad situations. If it gets interrupted it's essentially useless unless I'm missing something?

**Comment by Sandman25DCSS** [comment]
I agree, it must not be interruptible. It's like teleport except you need a wall.

**Comment by jeremygurr** [comment]
I don't think I've done anything to the passwall spell. Is it behaving differently than mainstream crawl? Or are you just suggesting a change from mainstream crawl? If so, then I agree it should probably be uninterruptible, but still take some time, so you might die while merging with the wall.

**Comment by G0rg0** [comment]
Maybe it uses the same underlying code that stairs use and the changes you made there are the reason? 
The way it should work is that you are open to attacks and can die while setting the spell up (which takes wall depth + 1 turns) but you can't be interrupted.

**Comment by jeremygurr** [comment]
Okay this is fixed now.
